//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtCC16DaemoniOSLibrary25SDAirDropSendStateMachine10BaseRunner : NSObject
{
    MISSING_TYPE *endpoints;	// 8 = 0x8
    MISSING_TYPE *deviceStatus;	// 16 = 0x10
    MISSING_TYPE *sendRequest;	// 0 = 0x0
    MISSING_TYPE *currentTransfer;	// 13040 = 0x32f0
    MISSING_TYPE *subject;	// 3828641 = 0x3a6ba1
    MISSING_TYPE *yield;	// 13040 = 0x32f0
    MISSING_TYPE *queue;	// 0 = 0x0
    MISSING_TYPE *log;	// 2147484672 = 0x80000400
    MISSING_TYPE *urls;	// 0 = 0x0
    MISSING_TYPE *hapticsManager;	// 1953718111 = 0x74735f5f
    MISSING_TYPE *transaction;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x0040000000204200
- (id)init;	// IMP=0x00100000002041a0

@end

