//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC16DaemoniOSLibrary23SDAirDropReceiveHandler : NSObject
{
    MISSING_TYPE *id;	// 0 = 0x0
    MISSING_TYPE *serverConnectionIdentity;	// 0 = 0x0
    MISSING_TYPE *delegate;	// 2004049759 = 0x77735f5f
    MISSING_TYPE *queue;	// 0 = 0x0
    MISSING_TYPE *deviceStatus;	// 0 = 0x0
    MISSING_TYPE *nearbyAgent;	// 0 = 0x0
    MISSING_TYPE *transferContinuation;	// 1887007839 = 0x7079745f
    MISSING_TYPE *exchangeContinuation;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *askRequest;	// 0 = 0x0
    MISSING_TYPE *uploadRequest;	// 0 = 0x0
    MISSING_TYPE *exchangeRequest;	// 0 = 0x0
    MISSING_TYPE *receiveCompressionAdapter;	// 0 = 0x0
    MISSING_TYPE *askConnection;	// 0 = 0x0
    MISSING_TYPE *uploadConnection;	// 4518856 = 0x44f3c8
    MISSING_TYPE *exchangeConnection;	// 19422 = 0x4bde
    MISSING_TYPE *totalBytes;	// 0 = 0x0
    MISSING_TYPE *shouldExtractMedia;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x004000000037f650
- (id)init;	// IMP=0x001000000037f5f0

@end

