//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSMutableDictionary, NSString, SDActivityEncryptionKey;

@interface SDActivityEncryptionManager : NSObject
{
    NSMutableDictionary *_deviceIdentifierToDecryptionKey;	// 8 = 0x8
    SDActivityEncryptionKey *_encryptionKey;	// 16 = 0x10
    NSData *_wrappingKey;	// 24 = 0x18
    _Bool _shouldRefreshWrappingKey;	// 32 = 0x20
}

+ (id)sharedEncryptionManager;	// IMP=0x00400000000feabe
- (void).cxx_destruct;	// IMP=0x00200000001013da
- (id)baseDictDecryptionKeyForDeviceIdentifier:(id)arg1;	// IMP=0x0010000000101284
- (id)baseDictEncryptionKey;	// IMP=0x00100000001011a1
- (id)baseDictWrappingKey;	// IMP=0x00100000001010be
- (id)baseDict;	// IMP=0x001000000010104e
- (_Bool)saveDecryptionKeyDataRepresentation:(id)arg1 forDeviceIdentifier:(id)arg2;	// IMP=0x0010000000100fce
- (id)loadDecryptionKeyDataRepresentationForDeviceIdentifier:(id)arg1;	// IMP=0x0010000000100f6f
- (_Bool)saveEncryptionKeyDataRepresentation:(id)arg1;	// IMP=0x0010000000100f00
- (id)loadEncryptionKeyDataRepresentation;	// IMP=0x0010000000100ea1
- (_Bool)saveKeyDataRepresentation:(id)arg1 withBaseDict:(id)arg2;	// IMP=0x0010000000100bf9
- (id)loadKeyDataRepresentationWithBaseDict:(id)arg1;	// IMP=0x0010000000100b4d
- (void)testWrappingKeychainItem;	// IMP=0x0010000000100b47
- (id)loadWrappingKeyData;	// IMP=0x00100000001009ec
- (id)allKeys;	// IMP=0x0010000000100502
- (_Bool)deleteAllEncryptionAndDecryptionKeys;	// IMP=0x00100000001003ae
- (id)newDecryptionKeyFromDataRepresentation:(id)arg1;	// IMP=0x00100000000fff38
- (id)unwrappedDataRepresentationForKey:(id)arg1;	// IMP=0x00100000000ffe2f
@property(readonly, nonatomic) NSData *dataRepresentationForCurrentEncryptionKey;
- (id)cachedDecryptionKeyForDeviceIdentifier:(id)arg1;	// IMP=0x00100000000ffa30
- (id)decryptionKeyForDeviceIdentifier:(id)arg1;	// IMP=0x00100000000ff93c
- (void)setDecryptionKey:(id)arg1 forDeviceIdentifier:(id)arg2;	// IMP=0x00100000000ff740
- (void)getTagAndCounterWhileEncryptingBytesInPlace:(unsigned char [10])arg1 forAdvertisementWithVersion:(unsigned char)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ff4c1
- (void)bumpEncryptionKeyCounterValue;	// IMP=0x00100000000ff2f6
@property(readonly, nonatomic) SDActivityEncryptionKey *encryptionKey;
- (void)generateNewEncryptionKey;	// IMP=0x00100000000fef24
- (void)resetStateRequested:(id)arg1;	// IMP=0x00100000000fef12
- (void)removeObservers;	// IMP=0x00100000000feebf
- (void)addObservers;	// IMP=0x00100000000fee58
@property(readonly) NSString *state;
- (void)dealloc;	// IMP=0x00100000000febc9
- (id)init;	// IMP=0x00100000000feb5f

@end

