//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSMutableData, NSMutableDictionary, NSProgress, NSString, NSURL, SDAirDropFileZipper, SDStatusMonitor;
@protocol OS_dispatch_queue, OS_dispatch_semaphore, OS_os_transaction, SDAirDropConnectionDelegate;

@interface SDAirDropConnection : NSObject
{
    _Bool _discover;	// 8 = 0x8
    _Bool _personAdded;	// 9 = 0x9
    _Bool _stopDeferred;	// 10 = 0xa
    _Bool _userAccepted;	// 11 = 0xb
    _Bool _senderTrusted;	// 12 = 0xc
    _Bool _delayedFinish;	// 13 = 0xd
    _Bool _queueSuspended;	// 14 = 0xe
    _Bool _endEncountered;	// 15 = 0xf
    _Bool _connectionClosed;	// 16 = 0x10
    _Bool _transactionStarted;	// 17 = 0x11
    struct __SFNode *_person;	// 24 = 0x18
    NSURL *_destination;	// 32 = 0x20
    char *_requestBuffer;	// 40 = 0x28
    NSProgress *_progress;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_queue;	// 56 = 0x38
    struct __SecTrust *_clientTrust;	// 64 = 0x40
    double _startTime;	// 72 = 0x48
    SDStatusMonitor *_monitor;	// 80 = 0x50
    long long _lastEvent;	// 88 = 0x58
    NSMutableData *_requestData;	// 96 = 0x60
    struct __CFReadStream *_readStream;	// 104 = 0x68
    SDAirDropFileZipper *_zipper;	// 112 = 0x70
    NSMutableDictionary *_properties;	// 120 = 0x78
    unsigned int _powerAssertionID;	// 128 = 0x80
    NSObject<OS_dispatch_semaphore> *_askSemaphore;	// 136 = 0x88
    struct _CFHTTPServerRequest *_askRequest;	// 144 = 0x90
    struct _CFHTTPServerRequest *_uploadRequest;	// 152 = 0x98
    struct _CFHTTPServerRequest *_discoverRequest;	// 160 = 0xa0
    struct _CFHTTPServerConnection *_connection;	// 168 = 0xa8
    NSData *_mediaCapabilities;	// 176 = 0xb0
    NSObject<OS_os_transaction> *;	// 184 = 0xb8
    _Bool _contactsOnly;	// 192 = 0xc0
    _Bool _shouldExtractMediaFromPhotosBundles;	// 193 = 0xc1
    NSString *_sessionID;	// 200 = 0xc8
    id <SDAirDropConnectionDelegate> _delegate;	// 208 = 0xd0
}

+ (id)disambiguatedModelName;	// IMP=0x002000000014620c
+ (id)validatedItemsArray:(id)arg1;	// IMP=0x0010000000140a5a
+ (id)validatedFilesArray:(id)arg1;	// IMP=0x001000000014078e
+ (id)validatedFileInfo:(id)arg1;	// IMP=0x00100000001403ba
+ (id)fileInfoExpectedClassForKeyMap;	// IMP=0x001000000014025d
- (void).cxx_destruct;	// IMP=0x00200000001469bc
@property __weak id <SDAirDropConnectionDelegate> delegate; // @synthesize delegate=_delegate;
@property _Bool shouldExtractMediaFromPhotosBundles; // @synthesize shouldExtractMediaFromPhotosBundles=_shouldExtractMediaFromPhotosBundles;
@property(copy) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(copy) NSURL *destination; // @synthesize destination=_destination;
@property _Bool contactsOnly; // @synthesize contactsOnly=_contactsOnly;
- (void)stop;	// IMP=0x0010000000146662
- (_Bool)accept;	// IMP=0x0010000000146546
- (void)start;	// IMP=0x0010000000146394
- (void)startPublishingProgressForPlaceholderFiles:(id)arg1;	// IMP=0x001000000014638e
- (void)schedule;	// IMP=0x0010000000146361
- (void)fileZipper:(id)arg1 event:(long long)arg2 withProperty:(void *)arg3;	// IMP=0x0010000000146078
- (_Bool)transferIsOverPrebufferLimit;	// IMP=0x0010000000146019
- (void)setCombinedFileURLsAndItems:(id)arg1;	// IMP=0x0010000000145f49
- (void)setSpotlightMetadata:(id)arg1;	// IMP=0x0010000000145f43
- (id)whereFromInfo;	// IMP=0x0010000000145ea4
- (void)handleClosedConnection;	// IMP=0x0010000000145cc6
- (void)didFailToSendResponse:(struct _CFHTTPServerResponse *)arg1;	// IMP=0x0010000000145c0d
- (void)didSendResponse:(struct _CFHTTPServerResponse *)arg1 forRequest:(struct _CFHTTPServerRequest *)arg2;	// IMP=0x00100000001458a7
- (void)finishOperation;	// IMP=0x00100000001454da
- (void)notifyClientOfBytesCopied:(id)arg1 timeRemaining:(id)arg2;	// IMP=0x001000000014539f
- (long long)getStatusCode:(struct _CFHTTPServerResponse *)arg1;	// IMP=0x001000000014535a
- (void)didReceiveRequest:(struct _CFHTTPServerRequest *)arg1;	// IMP=0x00100000001448a4
- (void)enqueueBadResponseForRequest:(struct _CFHTTPServerRequest *)arg1;	// IMP=0x001000000014471f
- (void)makeDestinationDirectory;	// IMP=0x0010000000144534
- (_Bool)oneHundredContinue:(struct _CFHTTPServerRequest *)arg1;	// IMP=0x00100000001444e6
- (void)enqueueResponse:(struct _CFHTTPServerRequest *)arg1 code:(long long)arg2 body:(struct __CFData *)arg3;	// IMP=0x0010000000144471
- (void)silentlyCancelRequest;	// IMP=0x001000000014439a
- (_Bool)senderInfoAvailable;	// IMP=0x0010000000144314
- (_Bool)thereIsEnoughFreeSpace;	// IMP=0x00100000001441e2
- (_Bool)startReceivingFile:(struct _CFHTTPServerRequest *)arg1 error:(id *)arg2;	// IMP=0x0010000000143de3
- (id)compressionType;	// IMP=0x0010000000143d18
- (_Bool)startReceivingBody:(struct _CFHTTPServerRequest *)arg1 error:(id *)arg2;	// IMP=0x0010000000143b70
- (void)handleReadStreamEvent:(struct __CFReadStream *)arg1 event:(unsigned long long)arg2;	// IMP=0x00100000001439ed
- (void)processRequest;	// IMP=0x001000000014392b
- (void)cancelAndDecline;	// IMP=0x0010000000143877
- (void)handleAskRequest;	// IMP=0x00100000001433e7
- (void)adjustPropertiesForPhotosBundles;	// IMP=0x00100000001430e5
- (void)adjustPropertiesForAutoAcceptSenderIsMe:(_Bool)arg1;	// IMP=0x0010000000142fe0
- (_Bool)transferContainsPhotosAssetBundles;	// IMP=0x0010000000142e3a
- (_Bool)allowAskRequestFromPerson:(struct __SFNode *)arg1;	// IMP=0x0010000000142d63
- (void)parseAskRequest;	// IMP=0x0010000000142b3d
- (void)handleDiscoverRequest;	// IMP=0x00100000001429a3
- (void)parseDiscoverRequest;	// IMP=0x0010000000142869
- (void)convertURLStringsToURLs;	// IMP=0x00100000001426ac
- (void)silentlyCancelRequestOnMainThread;	// IMP=0x001000000014264b
- (_Bool)senderIsMe;	// IMP=0x0010000000142416
- (_Bool)senderIsTrusted:(id)arg1;	// IMP=0x0010000000142263
- (_Bool)senderIsBlocked;	// IMP=0x001000000014225b
- (void)logSenderIsBlocked;	// IMP=0x00100000001421fe
- (struct __SFNode *)createPersonForAskRequest;	// IMP=0x0010000000141d8c
- (void)sendUploadResponse:(long long)arg1;	// IMP=0x0010000000141b95
- (void)releaseIdleSleepAssertion;	// IMP=0x0010000000141a8c
- (void)sendAskResponse:(long long)arg1;	// IMP=0x0010000000141701
- (void)sendDiscoverResponse:(long long)arg1 forKnownAlias:(id)arg2;	// IMP=0x00100000001411a9
- (void)storeIconValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x00100000001410cd
- (void)storeBooleanValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0010000000141036
- (void)storeNumberValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0010000000140f9f
- (void)storeStringValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0010000000140f08
- (void)storeDataValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0010000000140e71
- (void)storeRequestValue:(struct _CFHTTPServerRequest *)arg1 forKey:(struct __CFString *)arg2 convertToNumber:(_Bool)arg3;	// IMP=0x0010000000140d0a
- (void)storeArrayValue:(struct __CFDictionary *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0010000000140b6f
- (void)setProperty:(void *)arg1 forKey:(struct __CFString *)arg2;	// IMP=0x0010000000140241
- (void)didReceiveError:(struct __CFError *)arg1;	// IMP=0x0010000000140150
- (void)notifyClientForEvent:(long long)arg1;	// IMP=0x001000000013f877
- (void)performBlockForAllProgresses:(CDUnknownBlockType)arg1;	// IMP=0x001000000013f865
- (double)getTransferSize;	// IMP=0x001000000013f800
- (double)getTransferRate;	// IMP=0x001000000013f76e
- (void)notifyClient:(long long)arg1 withResults:(id)arg2;	// IMP=0x001000000013f6e6
- (void)handleTerminalCallBack;	// IMP=0x001000000013f67f
- (void)removeObservers;	// IMP=0x001000000013f62c
- (void)addObservers;	// IMP=0x001000000013f5c5
- (void)wirelessPowerChanged:(id)arg1;	// IMP=0x001000000013f4dc
- (void)systemWillSleep:(id)arg1;	// IMP=0x001000000013f40c
- (void)didCloseConnection;	// IMP=0x001000000013f3a3
- (void)dealloc;	// IMP=0x001000000013f26f
- (id)initWithConnection:(struct _CFHTTPServerConnection *)arg1;	// IMP=0x001000000013f0f8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

