//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, SDAirDropHandlerWebLinks;

@interface SDAirDropHandleriWorkLinks
{
    NSString *_appName;	// 8 = 0x8
    SDAirDropHandlerWebLinks *_webLinksHandler;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000dabf0
- (void)updatePossibleActions;	// IMP=0x00100000000dab54
- (id)suitableContentsDescription;	// IMP=0x00100000000da8fd
- (id)documentName;	// IMP=0x00100000000da85c
- (id)bundleProxyForiWorkURL:(id)arg1;	// IMP=0x00100000000da6a7
- (long long)transferTypes;	// IMP=0x00100000000da672
- (_Bool)canHandleTransfer;	// IMP=0x00100000000da462
- (id)initWithTransfer:(id)arg1;	// IMP=0x00100000000da381

@end

