//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerMapsLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x004000000008d99a
- (long long)transferTypes;	// IMP=0x001000000008d966
- (_Bool)canHandleTransfer;	// IMP=0x001000000008d951
- (id)candidateIdentifiers;	// IMP=0x001000000008d8a2
- (id)initWithTransfer:(id)arg1;	// IMP=0x001000000008d86c

@end

