//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, SDUnlockIDSController, SDUnlockSecurityManager, SFPairedUnlockEvent;
@protocol OS_dispatch_source;

@interface SDUnlockSessionManager : NSObject
{
    long long _setupAuthSession;	// 8 = 0x8
    long long _unlockAuthSession;	// 16 = 0x10
    long long _stashBagSession;	// 24 = 0x18
    SDUnlockIDSController *_idsController;	// 32 = 0x20
    SDUnlockSecurityManager *_securityManager;	// 40 = 0x28
    SFPairedUnlockEvent *_metrics;	// 48 = 0x30
    NSObject<OS_dispatch_source> *_unlockTimer;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000170cf9
@property(retain) NSObject<OS_dispatch_source> *unlockTimer; // @synthesize unlockTimer=_unlockTimer;
@property(retain) SFPairedUnlockEvent *metrics; // @synthesize metrics=_metrics;
@property(retain) SDUnlockSecurityManager *securityManager; // @synthesize securityManager=_securityManager;
@property __weak SDUnlockIDSController *idsController; // @synthesize idsController=_idsController;
@property long long stashBagSession; // @synthesize stashBagSession=_stashBagSession;
@property long long unlockAuthSession; // @synthesize unlockAuthSession=_unlockAuthSession;
@property long long setupAuthSession; // @synthesize setupAuthSession=_setupAuthSession;
- (void)logMetrics;	// IMP=0x0010000000170b4e
- (void)logProtoBufReceived:(id)arg1;	// IMP=0x0010000000170a29
- (void)logProtoBufSend:(id)arg1;	// IMP=0x0010000000170904
- (unsigned int)generateSessionID;	// IMP=0x00100000001708f5
- (_Bool)activeDevicesMatch;	// IMP=0x00100000001708ed
- (id)activeDeviceDescription;	// IMP=0x00100000001708e5
- (id)activeDeviceName;	// IMP=0x00100000001708dd
- (id)pairingStorePath;	// IMP=0x00100000001708d5
- (id)pairingID;	// IMP=0x00100000001708cd
- (_Bool)deviceIsPaired;	// IMP=0x00100000001708c5
- (unsigned short)pairingCompatibilityState;	// IMP=0x00100000001708ba
- (_Bool)inConfigureState;	// IMP=0x00100000001708b2
- (_Bool)shouldAbort;	// IMP=0x00100000001708aa
- (void)abortDevicePairingWithReason:(id)arg1;	// IMP=0x00100000001708a4
- (void)sendDisableMessage;	// IMP=0x00100000001707a2
- (void)sendResetMessage:(unsigned int)arg1 reason:(unsigned short)arg2;	// IMP=0x0010000000170669
- (void)invalidateUnlockTimer;	// IMP=0x00100000001705e3
- (void)restartUnlockTimer:(unsigned long long)arg1;	// IMP=0x001000000017041f
- (void)resetStashState;	// IMP=0x00100000001703b0
- (void)resetState;	// IMP=0x0010000000170334
- (void)resetAndClearState;	// IMP=0x0010000000170322
- (void)resetSetupState;	// IMP=0x00100000001702b3
- (void)resetAll;	// IMP=0x0010000000170278
- (void)disableUnlockWithDevice:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000001701a3
- (_Bool)unlockEnabled;	// IMP=0x001000000017015f
- (void)disableUnlockPairingForSecManager:(id)arg1;	// IMP=0x0010000000170096
- (void)disableUnlockPairing;	// IMP=0x0010000000170022
- (void)enableUnlockPairing;	// IMP=0x001000000016ffa5
- (void)deviceDidEnterConfigState:(id)arg1;	// IMP=0x001000000016fef4
- (void)pairingDidBegin:(id)arg1;	// IMP=0x001000000016fe43
- (void)pairingStatusChanged:(id)arg1;	// IMP=0x001000000016fe3d
- (void)updateExitPrevention;	// IMP=0x001000000016fe37
- (void)handleDevicesDidFailToPair;	// IMP=0x001000000016fdc1
- (void)devicesDidFailToPair:(id)arg1;	// IMP=0x001000000016fdaf
- (id)generateDebugInfo;	// IMP=0x001000000016f8e2
- (void)removeObservers;	// IMP=0x001000000016f88f
- (void)addObservers;	// IMP=0x001000000016f7d0
- (void)debugInfoRequested:(id)arg1;	// IMP=0x001000000016f7ca
- (void)preventExitForLocaleIfNeeded;	// IMP=0x001000000016f7c4
- (void)updateSecurityManager;	// IMP=0x001000000016f59b
- (void)updateSecurityManagerIfNeeded;	// IMP=0x001000000016f552
- (void)dealloc;	// IMP=0x001000000016f514
- (id)init;	// IMP=0x001000000016f427

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

