//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CSActivateXPCConnectionDelegate, OS_dispatch_queue, OS_xpc_object;

@interface CSActivationXPCConnection : NSObject
{
    id <CSActivateXPCConnectionDelegate> _delegate;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSObject<OS_xpc_object> *_connection;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000100ab1
@property(retain, nonatomic) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <CSActivateXPCConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_handleActivateEventMesssage:(id)arg1 client:(id)arg2;	// IMP=0x0010000000100867
- (void)_sendReply:(id)arg1 client:(id)arg2 result:(_Bool)arg3 error:(id)arg4;	// IMP=0x0010000000100769
- (void)_handleClientError:(id)arg1 client:(id)arg2;	// IMP=0x001000000010057e
- (void)_handleClientMessage:(id)arg1 client:(id)arg2;	// IMP=0x00100000001003b0
- (void)_handleClientEvent:(id)arg1;	// IMP=0x001000000010024a
- (void)activateConnection;	// IMP=0x001000000010019b
- (id)initWithConnection:(id)arg1;	// IMP=0x00100000001000cf

@end

