//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSAttSiriOSDProvider, CSAudioStream, CSAudioStreamHolding, NSMapTable, NSString;
@protocol OS_dispatch_queue;

@interface CSAttSiriSignalProvider : NSObject
{
    _Bool _audioRequested;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    CSAttSiriOSDProvider *_osdProvider;	// 24 = 0x18
    CSAudioStream *_audioStream;	// 32 = 0x20
    NSMapTable *_observerAndOptions;	// 40 = 0x28
    CSAudioStreamHolding *_audioStreamHolding;	// 48 = 0x30
}

+ (id)sharedProvider;	// IMP=0x0020000000040478
- (void).cxx_destruct;	// IMP=0x002000000003f52b
@property(nonatomic) _Bool audioRequested; // @synthesize audioRequested=_audioRequested;
@property(retain, nonatomic) CSAudioStreamHolding *audioStreamHolding; // @synthesize audioStreamHolding=_audioStreamHolding;
@property(retain, nonatomic) NSMapTable *observerAndOptions; // @synthesize observerAndOptions=_observerAndOptions;
@property(retain, nonatomic) CSAudioStream *audioStream; // @synthesize audioStream=_audioStream;
@property(retain, nonatomic) CSAttSiriOSDProvider *osdProvider; // @synthesize osdProvider=_osdProvider;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)_cancelAudioStreamHold;	// IMP=0x001000000003f3bb
- (void)_holdAudioStreamWithTimeout:(double)arg1;	// IMP=0x001000000003f29a
- (unsigned long long)_observersCount;	// IMP=0x001000000003f1f9
- (id)_startStreamOptionWithMachAbsTime:(unsigned long long)arg1;	// IMP=0x001000000003f186
- (void)_reset;	// IMP=0x001000000003f0c7
- (void)osdProvider:(id)arg1 silenceFramesCountMs:(double)arg2 silenceProbability:(double)arg3 silenceDurationMs:(double)arg4 processedAudioMs:(double)arg5 deviceHasBoronEnabled:(_Bool)arg6 latestBoronActiveSampleCount:(unsigned long long)arg7;	// IMP=0x001000000003f061
- (void)audioStreamProvider:(id)arg1 audioChunkForTVAvailable:(id)arg2;	// IMP=0x001000000003f04c
- (void)audioStreamProvider:(id)arg1 audioBufferAvailable:(id)arg2;	// IMP=0x001000000003efbf
- (void)_stopAllAnalyzers;	// IMP=0x001000000003efa2
- (void)_deliverSignalProviderDidStopUnexpectedly;	// IMP=0x001000000003eed1
- (void)audioStreamProvider:(id)arg1 didStopStreamUnexpectedly:(long long)arg2;	// IMP=0x001000000003ee86
- (void)cancelAudioStreamHoldingIfNeeded;	// IMP=0x001000000003ee3b
- (void)fetchStartSampleCountAndHostTimeByProcessedAudioInMs:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000003ed9e
- (void)stopWithObserver:(id)arg1 holdAudioStream:(_Bool)arg2;	// IMP=0x001000000003ecff
- (void)_startAudioStreamingWithSignalOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000003e92a
- (void)startWithSignalOptions:(id)arg1 observer:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000003e840
- (id)init;	// IMP=0x001000000003e76a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

