//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSObject;
@protocol OS_dispatch_queue;

@interface CSAudioRouteChangeMonitorImplWatch
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    _Bool _isHearstConnected;	// 16 = 0x10
    _Bool _isHearstRouted;	// 17 = 0x11
    _Bool _isSiriInputSourceOutOfBand;	// 18 = 0x12
}

- (void).cxx_destruct;	// IMP=0x00200000000ce711
- (void)_startObservingSystemControllerLifecycle;	// IMP=0x00100000000ce70b
- (void)_systemControllerDied:(id)arg1;	// IMP=0x00100000000ce631
- (void)_notifySiriInputSourceOutOfBandState:(_Bool)arg1;	// IMP=0x00100000000ce550
- (_Bool)_fetchSiriInputSourceOutOfBandState;	// IMP=0x00100000000ce4d4
- (void)_notifyHearstRoutedState:(_Bool)arg1;	// IMP=0x00100000000ce3f3
- (_Bool)_fetchHearstRoutedState;	// IMP=0x00100000000ce3eb
- (void)_stopMonitoring;	// IMP=0x00100000000ce36c
- (void)_startObservingAudioRouteChange;	// IMP=0x00100000000ce366
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00100000000ce281
- (void)activeAudioRouteDidChange:(id)arg1;	// IMP=0x00100000000ce22f
- (long long)hearstOwnership;	// IMP=0x00100000000ce227
- (void)getHearstOwnershipStatus:(CDUnknownBlockType)arg1;	// IMP=0x00100000000ce198
- (void)getSiriInputSourceOutOfBand:(CDUnknownBlockType)arg1;	// IMP=0x00100000000ce0fa
- (_Bool)siriInputSourceOutOfBand;	// IMP=0x00100000000ce065
- (_Bool)carPlayConnected;	// IMP=0x00100000000ce05d
- (_Bool)jarvisConnected;	// IMP=0x00100000000ce055
- (void)getJarvisConnected:(CDUnknownBlockType)arg1;	// IMP=0x00100000000cdfc6
- (_Bool)hearstRouted;	// IMP=0x00100000000cdf31
- (void)getHearstRouted:(CDUnknownBlockType)arg1;	// IMP=0x00100000000cde94
- (_Bool)hearstConnected;	// IMP=0x00100000000cddff
- (void)getHearstConnected:(CDUnknownBlockType)arg1;	// IMP=0x00100000000cdd61
- (id)init;	// IMP=0x00100000000cdd02

@end

