//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSURL;
@protocol OS_dispatch_queue;

@interface CSAudioFileLog : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    struct OpaqueExtAudioFile *_audioFile;	// 16 = 0x10
    struct AudioStreamBasicDescription _asbd;	// 24 = 0x18
    NSURL *_url;	// 64 = 0x40
    unsigned int _audioLength;	// 72 = 0x48
}

+ (id)sharedInstance;	// IMP=0x0040000000014091
- (void).cxx_destruct;	// IMP=0x0020000000013aa8
- (id)_makeTimestampedAudioLogFilenameWithPrefix:(id)arg1 suffix:(id)arg2;	// IMP=0x0010000000013990
- (id)_nowString;	// IMP=0x00100000000138c8
- (id)_getOrCreateAudioLogDirectory;	// IMP=0x00100000000136f0
- (id)_audioLogDirectory;	// IMP=0x00100000000136c0
- (void)stopRecording;	// IMP=0x0010000000013675
- (void)appendAudioData:(id)arg1;	// IMP=0x00100000000135e8
- (void)startRecording;	// IMP=0x001000000001359d
- (void)_closeAudioFile;	// IMP=0x00100000000134e3
- (void)dealloc;	// IMP=0x00100000000134a5
- (id)init;	// IMP=0x001000000001339c

@end

