//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable;
@protocol OS_dispatch_queue;

@interface CSCommandControlBehaviorMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSHashTable *_observers;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00400000000bc43b
- (void).cxx_destruct;	// IMP=0x00200000000bbc85
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)notifyDidStopStream:(id)arg1;	// IMP=0x00100000000bbbc2
- (void)notifyWillStopStream:(id)arg1;	// IMP=0x00100000000bbb35
- (void)notifyDidStartStreamWithContext:(id)arg1 successfully:(_Bool)arg2 option:(id)arg3;	// IMP=0x00100000000bba72
- (void)notifyWillStartStreamWithContext:(id)arg1 option:(id)arg2;	// IMP=0x00100000000bb9bb
- (void)unregisterObserver:(id)arg1;	// IMP=0x00100000000bb92e
- (void)registerObserver:(id)arg1;	// IMP=0x00100000000bb8a1
- (id)init;	// IMP=0x00100000000bb81a

@end

