//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol CSAttendingService, LBAttendingStatesServiceDelegate, OS_dispatch_group, OS_dispatch_queue;

@interface CSLocalAttendingInitiator : NSObject
{
    _Bool _isAttending;	// 8 = 0x8
    id <LBAttendingStatesServiceDelegate> _delegate;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    id <CSAttendingService> _usecaseController;	// 32 = 0x20
    NSString *_rootRequestId;	// 40 = 0x28
    NSString *_rootRequestIdWithMagusDisabled;	// 48 = 0x30
    NSString *_rootRequestIdForLogging;	// 56 = 0x38
    NSString *_rootRequestIdForWillAttendSignal;	// 64 = 0x40
    unsigned long long _startAttendingHostTime;	// 72 = 0x48
    NSString *_mhUUID;	// 80 = 0x50
    NSObject<OS_dispatch_group> *_attendingStartTransitionGroup;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x0020000000142b54
@property(retain, nonatomic) NSObject<OS_dispatch_group> *attendingStartTransitionGroup; // @synthesize attendingStartTransitionGroup=_attendingStartTransitionGroup;
@property(retain, nonatomic) NSString *mhUUID; // @synthesize mhUUID=_mhUUID;
@property(nonatomic) unsigned long long startAttendingHostTime; // @synthesize startAttendingHostTime=_startAttendingHostTime;
@property(retain, nonatomic) NSString *rootRequestIdForWillAttendSignal; // @synthesize rootRequestIdForWillAttendSignal=_rootRequestIdForWillAttendSignal;
@property(retain, nonatomic) NSString *rootRequestIdForLogging; // @synthesize rootRequestIdForLogging=_rootRequestIdForLogging;
@property(retain, nonatomic) NSString *rootRequestIdWithMagusDisabled; // @synthesize rootRequestIdWithMagusDisabled=_rootRequestIdWithMagusDisabled;
@property(retain, nonatomic) NSString *rootRequestId; // @synthesize rootRequestId=_rootRequestId;
@property(nonatomic) _Bool isAttending; // @synthesize isAttending=_isAttending;
@property(retain, nonatomic) id <CSAttendingService> usecaseController; // @synthesize usecaseController=_usecaseController;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <LBAttendingStatesServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_emitSpeechStartDetectedEventWithAttendingTriggerInfo:(id)arg1;	// IMP=0x0010000000142a29
- (void)_handleClientAudioDidStartMessage;	// IMP=0x0010000000142a13
- (void)intuitiveConvAudioCaptureMonitor:(id)arg1 didStartAudioCaptureSuccessfully:(_Bool)arg2 option:(id)arg3 eventUUID:(id)arg4;	// IMP=0x00100000001429c8
- (void)siriClientBehaviorMonitor:(id)arg1 didStopStream:(id)arg2 withEventUUID:(id)arg3;	// IMP=0x00100000001429c2
- (void)siriClientBehaviorMonitor:(id)arg1 willStopStream:(id)arg2 reason:(unsigned long long)arg3;	// IMP=0x00100000001429bc
- (void)siriClientBehaviorMonitor:(id)arg1 didStartStreamWithContext:(id)arg2 successfully:(_Bool)arg3 option:(id)arg4 withEventUUID:(id)arg5;	// IMP=0x0010000000142971
- (void)siriClientBehaviorMonitor:(id)arg1 willStartStreamWithContext:(id)arg2 option:(id)arg3;	// IMP=0x001000000014296b
- (void)_handleSpeechStartDetectedWithEventInfo:(id)arg1;	// IMP=0x00100000001427d8
- (void)speechStartDetectedWithEventInfo:(id)arg1;	// IMP=0x001000000014274b
- (void)attendingStoppedWithReason:(long long)arg1;	// IMP=0x00100000001426fc
- (void)receivedAttendingMagusNotSupportedHintWithInfo:(id)arg1;	// IMP=0x0010000000142644
- (void)receivedAttendingTriggerForSiriPromptHintWithInfo:(id)arg1;	// IMP=0x001000000014258c
- (void)receivedAttendingStopHintWithInfo:(id)arg1;	// IMP=0x0010000000142436
- (void)receivedAttendingStartHintWithInfo:(id)arg1;	// IMP=0x001000000014237e
- (void)receivedAttendingWillStartHintWithInfo:(id)arg1;	// IMP=0x00100000001422c6
- (void)_reset;	// IMP=0x00100000001422a8
- (void)_stopAttendingWithReason:(unsigned long long)arg1;	// IMP=0x0010000000142180
- (void)_startAttendingWithInfo:(id)arg1;	// IMP=0x0010000000141d90
- (void)setAttendingState:(_Bool)arg1;	// IMP=0x0010000000141d42
- (_Bool)fetchIsAttending;	// IMP=0x0010000000141cb4
- (id)initWithAttendingUsecase:(id)arg1;	// IMP=0x0010000000141bdd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

