//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreSpeechFoundation/CSEventMonitor.h>

@class NSObject;
@protocol OS_dispatch_queue;

@interface CSVolumeMonitor : CSEventMonitor
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    float _musicVolumeLevel;	// 16 = 0x10
    float _alarmVolumeLevel;	// 20 = 0x14
}

+ (id)sharedInstance;	// IMP=0x004000000000b2ac
- (void).cxx_destruct;	// IMP=0x002000000000b0ff
- (_Bool)_supportAVSystemVolumeFetch;	// IMP=0x001000000000b0e8
- (void)_startObservingSystemControllerLifecycle;	// IMP=0x001000000000b061
- (void)startObservingSystemVolumes;	// IMP=0x001000000000afa4
- (void)systemControllerDied:(id)arg1;	// IMP=0x001000000000aeea
- (void)systemVolumeDidChange:(id)arg1;	// IMP=0x001000000000aece
- (void)fetchVolumeFromAVSystemControllerForAudioCategory:(id)arg1;	// IMP=0x001000000000ae3a
- (float)alarmVolume;	// IMP=0x001000000000ad9e
- (void)musicVolumeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000000ad00
- (float)musicVolume;	// IMP=0x001000000000ac64
- (void)dealloc;	// IMP=0x001000000000abef
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x001000000000ab48
- (id)init;	// IMP=0x001000000000aab3

@end

