//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CUTDeferredTaskQueue, IDSGameCenterData, IDSRegistration, IDSRegistrationPushHandler, IDSServiceProperties, NSArray, NSDate, NSDictionary, NSHashTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface IDSDAccount : NSObject
{
    NSMutableDictionary *_accountInfo;	// 8 = 0x8
    IDSRegistration *_registrationInfo;	// 16 = 0x10
    IDSServiceProperties *_service;	// 24 = 0x18
    NSString *_uniqueID;	// 32 = 0x20
    NSMutableArray *_setupHandlers;	// 40 = 0x28
    NSHashTable *_registrationListeners;	// 48 = 0x30
    IDSRegistrationPushHandler *_pushHandler;	// 56 = 0x38
    NSDate *_dateOfLastHandlesCheck;	// 64 = 0x40
    NSMutableSet *_localServices;	// 72 = 0x48
    unsigned int _disabledAutomatically:1;	// 80 = 0x50
    unsigned int _duringInit:1;	// 80 = 0x50
    unsigned int _shouldRequeryHandles:1;	// 80 = 0x50
    unsigned int _issuingDependentCheck:1;	// 80 = 0x50
    unsigned int _issuingHandlesCheck:1;	// 80 = 0x50
    unsigned int _pendingDependentCheck:1;	// 80 = 0x50
    unsigned int _pendingHandlesCheck:1;	// 80 = 0x50
    unsigned int _pendingReIdentify:1;	// 80 = 0x50
    unsigned int _pendingReRegister:1;	// 81 = 0x51
    unsigned int _isRegistrationActive:1;	// 81 = 0x51
    unsigned int _pendingAccountInfoBroadcast:1;	// 81 = 0x51
    unsigned int _isBeingRemoved:1;	// 81 = 0x51
    CUTDeferredTaskQueue *_broadcastAccountInfoChangedTask;	// 88 = 0x58
}

+ (_Bool)dependentRegistration:(id)arg1 hasDependentRegistrationWithURI:(id)arg2 token:(id)arg3;	// IMP=0x0020000000173771
+ (void)dependentRegistration:(id)arg1 findDeviceUniqueID:(id *)arg2 btID:(id *)arg3 forURI:(id)arg4 token:(id)arg5 supportsLiveDelivery:(_Bool *)arg6;	// IMP=0x0010000000172d91
+ (void)sendMessageWithSendParameters:(id)arg1 service:(id)arg2 threadContext:(id)arg3 willSendBlock:(CDUnknownBlockType)arg4 progressBlock:(CDUnknownBlockType)arg5 completionBlock:(CDUnknownBlockType)arg6;	// IMP=0x00100000002eccba
+ (void)_sendLocallyWithSendParameters:(id)arg1 service:(id)arg2 uriToLocalDestination:(id)arg3 data:(id)arg4 protobuf:(id)arg5 threadContext:(id)arg6 progressBlock:(CDUnknownBlockType)arg7 completionBlock:(CDUnknownBlockType)arg8;	// IMP=0x00100000002e9caa
+ (void)_splitDestinations:(id)arg1 intoLocalDestinations:(id *)arg2 remoteDestinations:(id *)arg3 threadContext:(id)arg4 sendParameters:(id)arg5;	// IMP=0x00100000002e70ee
- (void).cxx_destruct;	// IMP=0x001000000017c91d
@property(readonly, nonatomic) CUTDeferredTaskQueue *broadcastAccountInfoChangedTask; // @synthesize broadcastAccountInfoChangedTask=_broadcastAccountInfoChangedTask;
@property(nonatomic) _Bool isBeingRemoved; // @synthesize isBeingRemoved=_isBeingRemoved;
@property(readonly, nonatomic) _Bool issuingDependentCheck; // @synthesize issuingDependentCheck=_issuingDependentCheck;
@property(nonatomic) _Bool pendingDependentCheck; // @synthesize pendingDependentCheck=_pendingDependentCheck;
@property(nonatomic) _Bool wasDisabledAutomatically; // @synthesize wasDisabledAutomatically=_disabledAutomatically;
@property(readonly, nonatomic) NSDictionary *accountInfo; // @synthesize accountInfo=_accountInfo;
@property(readonly, nonatomic) IDSRegistration *registration; // @synthesize registration=_registrationInfo;
- (void)didUpdateProtocolForPairedDevice:(id)arg1;	// IMP=0x001000000017c5b1
- (void)didUpdatePairedDevice:(id)arg1;	// IMP=0x001000000017c27e
- (void)didRemovePairedDevice:(id)arg1;	// IMP=0x001000000017bf28
- (void)didAddPairedDevice:(id)arg1;	// IMP=0x001000000017bea3
- (void)_notifyDelegatesAddedLocalDevice:(id)arg1;	// IMP=0x001000000017bb06
- (void)_notifyClientDelegatesWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000017b9e4
@property(readonly, retain, nonatomic) NSDictionary *accountSetupInfo;
- (id)smallDescription;	// IMP=0x001000000017b738
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSArray *linkedAccounts;
- (id)adHocAccounts;	// IMP=0x001000000017aad0
- (_Bool)forEachAdhocAccount:(CDUnknownBlockType)arg1;	// IMP=0x001000000017a13f
- (id)accountAndAdHocAccounts;	// IMP=0x001000000017a0c9
- (void)_updateAccountWithAccountInfo:(id)arg1;	// IMP=0x0010000000179889
- (void)writeAccountDefaults:(id)arg1;	// IMP=0x0010000000179875
- (void)_writeAccountDefaults:(id)arg1 force:(_Bool)arg2 interestedSubservices:(id)arg3;	// IMP=0x0010000000178d65
- (void)_writeAccountDefaults:(id)arg1 force:(_Bool)arg2;	// IMP=0x0010000000178d50
- (void)_broadcastAccountInfoChanged;	// IMP=0x0010000000178bbb
- (void)_notifyListenersWithChanges:(id)arg1;	// IMP=0x0010000000177b72
- (void)_broadcastAccountMessageBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000177a34
- (_Bool)isAdHocAccount;	// IMP=0x00100000001779b8
- (id)primaryServiceName;	// IMP=0x0010000000177918
@property(readonly, nonatomic) IDSRegistration *primaryRegistration;
- (id)primaryAccountUniqueID;	// IMP=0x00100000001777de
- (id)primaryAccount;	// IMP=0x0010000000177742
@property(readonly, nonatomic) long long lastRegistrationFailureError;
@property(readonly, nonatomic) NSDate *lastRegistrationFailureDate;
@property(readonly, nonatomic) NSDate *lastRegistrationSuccessDate;
@property(readonly, nonatomic) NSDate *lastGDRDate;
- (id)dependentRegistrationMatchingUUID:(id)arg1;	// IMP=0x001000000017766f
- (id)dependentRegistrationMatchingUUID:(id)arg1 includingTinker:(_Bool)arg2;	// IMP=0x00100000001773a0
@property(readonly, nonatomic) NSArray *registeredDevices;
@property(readonly, nonatomic) NSArray *dependentRegistrationsIncludingCurrentDevice;
- (id)dependentRegistrationsIncludingTinker:(_Bool)arg1;	// IMP=0x00100000001771b0
@property(readonly, nonatomic) NSArray *dependentRegistrations;
- (id)_dependentRegistrationsForDefaultPairedDevice:(_Bool)arg1 includingCurrentDevice:(_Bool)arg2 includingTinker:(_Bool)arg3;	// IMP=0x0010000000175797
- (id)_dependentRegistrationsForDefaultPairedDevice:(_Bool)arg1 includingTinker:(_Bool)arg2;	// IMP=0x0010000000175741
@property(readonly, nonatomic) IDSDAccount *superAccount;
@property(readonly, nonatomic) NSDictionary *defaultPairedDependentRegistration;
- (id)defaultPairedDependentRegistrationIncludingTinker:(_Bool)arg1;	// IMP=0x00100000001750a7
- (id)_fromIDFromDevice:(id)arg1 withCBUUID:(id)arg2 uniqueID:(id)arg3;	// IMP=0x0010000000174c93
- (id)fromIDForCBUUID:(id)arg1 deviceID:(id)arg2;	// IMP=0x0010000000173f36
- (_Bool)hasDependentRegistrationWithURI:(id)arg1 token:(id)arg2;	// IMP=0x0010000000173dc4
- (void)findDeviceUniqueID:(id *)arg1 btID:(id *)arg2 forURI:(id)arg3 token:(id)arg4 supportsLiveDelivery:(_Bool *)arg5;	// IMP=0x0010000000173496
@property(readonly, nonatomic) _Bool isUsableForSending;
@property(readonly, nonatomic) _Bool hasEverRegistered;
- (id)_certForFromURI:(id)arg1;	// IMP=0x0010000000172b27
- (_Bool)hasVettedAliasURI:(id)arg1;	// IMP=0x0010000000172ab1
- (_Bool)hasAliasURI:(id)arg1;	// IMP=0x0010000000172a10
@property(readonly, nonatomic) NSArray *uris;
@property(readonly, nonatomic) NSArray *aliasStrings;
- (void)setupAccountWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001723b5
@property(readonly, nonatomic) _Bool isEnabled;
@property(readonly, nonatomic) _Bool shouldRegisterUsingDSHandle;
@property(readonly, nonatomic) _Bool shouldAutoRegisterAllHandles;
@property(readonly, nonatomic) _Bool isRegistered;
- (void)authenticationChanged;	// IMP=0x0010000000172264
@property(retain, nonatomic) NSDate *expirationDate;
@property(nonatomic) _Bool isTemporary;
@property(readonly, nonatomic) int manateeRetryCount;
@property(readonly, nonatomic) _Bool shouldRegisterOnManateeAvailability;
@property(readonly, nonatomic) long long registrationError;
@property(readonly, nonatomic) int registrationErrorReason;
@property(readonly, nonatomic) int registrationStatus;
@property(retain, nonatomic) NSString *loginID;
@property(readonly, nonatomic) NSString *dsID;
@property(readonly, nonatomic) NSString *dsHandle;
@property(readonly, nonatomic) int accountType;
@property(nonatomic) _Bool isUserDisabled;
- (void)clearDisplayName;	// IMP=0x00100000001715c6
@property(retain, nonatomic) NSString *displayName;
@property(retain, nonatomic) IDSGameCenterData *gameCenterData;
@property(retain, nonatomic) NSString *userUniqueIdentifier;
@property(readonly, nonatomic) NSString *uniqueID;
@property(readonly, nonatomic) IDSServiceProperties *service;
- (void)setObject:(id)arg1 forKey:(id)arg2;	// IMP=0x0010000000170e2c
- (void)dealloc;	// IMP=0x0010000000170adf
- (void)cleanupAccount;	// IMP=0x0000000000170ac9
- (id)initWithLoginID:(id)arg1 service:(id)arg2 uniqueID:(id)arg3 accountType:(int)arg4 accountConfig:(id)arg5;	// IMP=0x0010000000170aa7
- (id)initAdHocAccountWithLoginID:(id)arg1 service:(id)arg2 uniqueID:(id)arg3 accountType:(int)arg4 accountConfig:(id)arg5 primaryAccount:(id)arg6;	// IMP=0x0010000000170a7c
- (id)_initWithLoginID:(id)arg1 service:(id)arg2 uniqueID:(id)arg3 accountType:(int)arg4 accountConfig:(id)arg5 primaryAccount:(id)arg6 isAdHocAccount:(_Bool)arg7;	// IMP=0x0010000000170472
- (id)initWithDictionary:(id)arg1 service:(id)arg2 uniqueID:(id)arg3;	// IMP=0x001000000016fdd9
- (void)_setupAccount;	// IMP=0x001000000016f212
- (void)_resetVariables;	// IMP=0x001000000016f204
- (void)_cleanupAccount;	// IMP=0x001000000016db48
- (void)_notifyRegistrationListenersAccountDidUpdateRegisteredDevices;	// IMP=0x00100000001fc0fe
- (void)removeRegistrationListener:(id)arg1;	// IMP=0x00100000001fc098
- (void)addRegistrationListener:(id)arg1;	// IMP=0x00100000001fc01b
- (void)systemDidLeaveFirstDataProtectionLock;	// IMP=0x00100000001fbd66
- (id)pushHandler;	// IMP=0x00100000001fbd4e
- (id)serviceType;	// IMP=0x00100000001fbd07
- (void)reportSpamMessage:(id)arg1 toURI:(id)arg2;	// IMP=0x00100000001fbc57
- (void)reportAction:(long long)arg1 ofTempURI:(id)arg2 fromURI:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x00100000001fbba0
- (void)reportiMessageUnknownSender:(id)arg1 messageID:(id)arg2 isBlackholed:(_Bool)arg3 isJunked:(_Bool)arg4 messageServerTimestamp:(id)arg5 toURI:(id)arg6;	// IMP=0x00100000001fbaa6
- (void)reportSpamWithMessages:(id)arg1 toURI:(id)arg2;	// IMP=0x00100000001fba09
- (long long)validationStatusForAlias:(id)arg1;	// IMP=0x00100000001fb9f7
- (id)aliases;	// IMP=0x00100000001fb9e5
- (double)_maxSelectedButVettedGracePeriod;	// IMP=0x00100000001fb83c
- (id)_allUserIntentWithDefaultReason:(_Bool)arg1;	// IMP=0x00100000001fb0f7
- (void)_stopTrackingUserIntentOfAlias:(id)arg1;	// IMP=0x00100000001faed3
- (void)_setUserIntentState:(unsigned char)arg1 forAlias:(id)arg2 withReason:(unsigned char)arg3;	// IMP=0x00100000001faa02
- (id)_userIntentDictForAlias:(id)arg1;	// IMP=0x00100000001fa6ea
- (unsigned char)unselectReasonForAlias:(id)arg1;	// IMP=0x00100000001fa626
- (void)loadAliasUserIntentMetadataIfNeeded;	// IMP=0x00100000001fa606
- (unsigned char)currentAliasState:(id)arg1;	// IMP=0x00100000001fa58d
- (_Bool)wasRecentlySelectedAlias:(id)arg1;	// IMP=0x00100000001fa575
- (void)markAsWasSelectedAlias:(id)arg1;	// IMP=0x00100000001fa555
- (void)markAsVettedAlias:(id)arg1;	// IMP=0x00100000001fa4ee
- (void)markAsUnvettedAlias:(id)arg1;	// IMP=0x00100000001fa475
- (void)markAsUnselectedAlias:(id)arg1 withReason:(unsigned char)arg2;	// IMP=0x00100000001fa458
- (void)markAsSelectedAlias:(id)arg1;	// IMP=0x00100000001fa438
- (id)invisibleAliases;	// IMP=0x00100000001fa3de
- (id)vettedAliases;	// IMP=0x00100000001fa384
- (void)reIdentify;	// IMP=0x00100000001fa36d
- (void)reregister;	// IMP=0x00100000001fa359
- (void)_refreshRegistration;	// IMP=0x00100000001fa098
- (void)validateProfile;	// IMP=0x00100000001f9c8b
- (void)askPeersToClearCacheWithURIs:(id)arg1 fromURI:(id)arg2 forService:(id)arg3;	// IMP=0x00100000001f98b7
- (void)_handleKTOptInStatusUpdateError:(long long)arg1;	// IMP=0x00100000001f9860
- (_Bool)updateKTOptInStatusWithRequest:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001f89f1
- (_Bool)updateKTOptInStatus:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001f7bc8
@property(readonly, nonatomic) NSDictionary *pseudonymURIMap;
@property(readonly, nonatomic) NSArray *pseudonyms;
- (id)pseudonymForPseudonymURIString:(id)arg1;	// IMP=0x00100000001f6d82
- (void)_removePseudonyms:(id)arg1;	// IMP=0x00100000001f67bd
- (void)_removePseudonym:(id)arg1;	// IMP=0x00100000001f6715
- (void)_addPseudonym:(id)arg1;	// IMP=0x00100000001f612f
- (void)_removeAllPseudonyms;	// IMP=0x00100000001f6067
- (_Bool)revokePseudonym:(id)arg1 requestProperties:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000001f5c69
- (_Bool)renewPseudonym:(id)arg1 forUpdatedExpiryEpoch:(double)arg2 requestProperties:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;	// IMP=0x00100000001f58a0
- (_Bool)provisionPseudonymForURI:(id)arg1 properties:(id)arg2 requestProperties:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;	// IMP=0x00100000001f52a4
- (void)_handlePseudonymProvisionError:(long long)arg1;	// IMP=0x00100000001f51c6
- (void)refreshVettedAliases;	// IMP=0x00100000001f5098
- (void)validateCredentialsWithDeliveryCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001f500e
- (void)deactivateAndPurgeIdentify;	// IMP=0x00100000001f4df8
- (void)unvalidateAliases:(id)arg1;	// IMP=0x00100000001f4be8
- (void)_unvalidateAliases:(id)arg1;	// IMP=0x00100000001f464e
- (void)validateAliases:(id)arg1;	// IMP=0x00100000001f443e
- (void)_validateAliases:(id)arg1;	// IMP=0x00100000001f4200
- (void)_validateAliases:(id)arg1 validateAlreadyValid:(_Bool)arg2;	// IMP=0x00100000001f36c7
- (void)addAliases:(id)arg1;	// IMP=0x00100000001f35ca
- (void)_addAliases:(id)arg1;	// IMP=0x00100000001f2dc9
- (void)removeAliases:(id)arg1;	// IMP=0x00100000001f2cf6
- (void)_removeAliases:(id)arg1 withReason:(unsigned char)arg2;	// IMP=0x00100000001f2362
- (void)_setValidationStatus:(long long)arg1 error:(int)arg2 forAlias:(id)arg3 info:(id)arg4 addToCurrentHandlesIfNeeded:(_Bool)arg5 forceAdd:(_Bool)arg6;	// IMP=0x00100000001f2337
- (void)_setValidationStatus:(long long)arg1 error:(int)arg2 forAlias:(id)arg3 info:(id)arg4 addToCurrentHandlesIfNeeded:(_Bool)arg5 forceAdd:(_Bool)arg6 aliasProperties:(id)arg7;	// IMP=0x00100000001f1e69
- (long long)_validationStatusForAlias:(id)arg1;	// IMP=0x00100000001f1bc1
- (id)_aliases;	// IMP=0x00100000001f1aca
- (id)_aliasStrings;	// IMP=0x00100000001f18a9
- (void)_ignoreIncomingPushes;	// IMP=0x00100000001f1887
- (void)_acceptIncomingPushes;	// IMP=0x00100000001f1862
- (void)center:(id)arg1 failedRegionValidation:(id)arg2 error:(long long)arg3 info:(id)arg4;	// IMP=0x00100000001f1494
- (void)center:(id)arg1 succeededRegionValidation:(id)arg2 regionID:(id)arg3 phoneNumber:(id)arg4 extraContext:(id)arg5 verified:(_Bool)arg6;	// IMP=0x00100000001f0feb
- (void)center:(id)arg1 succeededCurrentEmailsRequest:(id)arg2 emailInfo:(id)arg3;	// IMP=0x00100000001f0d50
- (void)center:(id)arg1 failedAuthentication:(id)arg2 error:(long long)arg3 info:(id)arg4;	// IMP=0x00100000001f0981
- (void)center:(id)arg1 succeededAuthentication:(id)arg2;	// IMP=0x00100000001f061f
- (void)center:(id)arg1 startedAuthenticating:(id)arg2;	// IMP=0x00100000001f0428
- (void)registrationControllerNeedsNewRegistration:(id)arg1;	// IMP=0x00100000001f024c
- (void)registrationController:(id)arg1 deregistrationSucceeded:(id)arg2;	// IMP=0x00100000001f0041
- (void)registrationController:(id)arg1 deregistrationWillStart:(id)arg2;	// IMP=0x00100000001efefc
- (void)registrationController:(id)arg1 registrationFailed:(id)arg2 error:(long long)arg3 info:(id)arg4;	// IMP=0x00100000001eea83
- (void)registrationController:(id)arg1 registrationSucceeded:(id)arg2;	// IMP=0x00100000001ed858
- (void)registrationController:(id)arg1 registrationUpdated:(id)arg2;	// IMP=0x00100000001ed668
- (void)registrationController:(id)arg1 registrationWillStart:(id)arg2;	// IMP=0x00100000001ed44d
- (void)centerNeedsNewIdentification:(id)arg1;	// IMP=0x00100000001ed447
- (void)center:(id)arg1 failedIdentification:(id)arg2 error:(long long)arg3;	// IMP=0x00100000001ed441
- (void)center:(id)arg1 succeededIdentification:(id)arg2 phoneNumber:(id)arg3 token:(id)arg4;	// IMP=0x00100000001ed1e4
- (unsigned long long)_unregistered130RetryInterval;	// IMP=0x00100000001ed1ce
- (void)_updateSessionsWithRegisteredURIs:(id)arg1 retryIfNotRegistered:(_Bool)arg2;	// IMP=0x00100000001ec888
- (void)_updateSessionsWithRegisteredURIs:(id)arg1;	// IMP=0x00100000001ec871
- (void)_updateSessionsForAllRegisteredURIs;	// IMP=0x00100000001ec803
- (void)_flushTokensForRegisteredURIs:(id)arg1;	// IMP=0x00100000001ec110
- (void)_processReceivedDependentRegistration:(id)arg1 oldDependentRegistrations:(id)arg2;	// IMP=0x00100000001eb35a
- (void)_issueDependentCheck;	// IMP=0x00100000001ea489
- (void)_issueCriticalDependentCheck;	// IMP=0x00100000001ea45b
- (_Bool)_issueForcedDependentCheckIfPossible;	// IMP=0x00100000001ea413
- (void)_saveAndNotifyGDRUpdate;	// IMP=0x00100000001e9f05
- (void)_notifyListenersAndSetDependentRegistrations:(id)arg1 onRegistrationInfo:(id)arg2;	// IMP=0x00100000001e9c76
- (void)gdrReAuthenticateIfNecessary;	// IMP=0x00100000001e97e5
- (void)_clearGDRState;	// IMP=0x00100000001e96eb
- (void)handler:(id)arg1 flushCacheForURIs:(id)arg2;	// IMP=0x00100000001e92e8
- (void)handler:(id)arg1 profileHandlesUpdated:(id)arg2 status:(id)arg3 allowGDR:(id)arg4;	// IMP=0x00100000001e8a48
- (void)handler:(id)arg1 profile:(id)arg2 deviceUpdated:(id)arg3 service:(id)arg4;	// IMP=0x00100000001e80d8
- (void)_updateHandles:(_Bool)arg1;	// IMP=0x00100000001e7831
- (void)_parseHandlesInfo:(id)arg1 currentAliases:(id)arg2 currentVettedAliases:(id)arg3;	// IMP=0x00100000001e5cea
- (void)handler:(id)arg1 reloadBag:(id)arg2;	// IMP=0x00100000001e576b
- (void)handler:(id)arg1 pushTokenChanged:(id)arg2;	// IMP=0x00100000001e5343
- (void)updateAuthorizationCredentials:(id)arg1 token:(id)arg2;	// IMP=0x00100000001e4fc3
- (void)passwordUpdated;	// IMP=0x00100000001e4cf5
- (void)unregisterAccount;	// IMP=0x00100000001e4add
- (void)_unregisterAccount;	// IMP=0x00100000001e46e2
- (void)registerAccount;	// IMP=0x00100000001e44f8
- (void)_registerAccount;	// IMP=0x00100000001e392f
- (_Bool)_migrateRegistrationIfNeeded;	// IMP=0x00100000001e31d5
- (void)_retryRegister;	// IMP=0x00100000001e303b
- (void)authenticateAccount;	// IMP=0x00100000001e2e23
- (_Bool)_isPasswordPromptPermissibleDuringAuthentication;	// IMP=0x00100000001e2d31
- (void)_authenticateAccount;	// IMP=0x00100000001e28e8
- (void)deactivateRegistration;	// IMP=0x00100000001e2135
- (void)activateRegistration;	// IMP=0x00100000001e140a
- (void)systemRestoreStateDidChange;	// IMP=0x00100000001e128e
- (void)systemDidStartBackup;	// IMP=0x00100000001e11f1
- (void)systemDidFinishMigration;	// IMP=0x00100000001e1156
- (void)_reregister;	// IMP=0x00100000001e1142
- (void)_reregisterAndReidentify:(_Bool)arg1;	// IMP=0x00100000001e0d20
- (void)_removeAuthenticationCredentialsIncludingAuthToken:(_Bool)arg1;	// IMP=0x00100000001e09a8
- (void)_removeAuthenticationCredentials;	// IMP=0x00100000001e0991
- (void)_reregisterAndReProvision;	// IMP=0x00100000001e0728
- (void)_reAuthenticate;	// IMP=0x00100000001e06c3
- (_Bool)_stopRegistrationAgent;	// IMP=0x00100000001e04ba
- (void)_updateRegistrationStatusWithError:(long long)arg1 info:(id)arg2;	// IMP=0x00100000001df462
- (void)setRegistrationStatus:(int)arg1 error:(long long)arg2 alertInfo:(id)arg3;	// IMP=0x00100000001def8d
- (void)_checkRegistration;	// IMP=0x00100000001de2d7
- (void)_updateVettedAliases:(id)arg1 emailInfo:(id)arg2 addToCurrentHandlesIfNeeded:(_Bool)arg3;	// IMP=0x00100000001dd9c8
- (void)_updatePseudonymsFromEmailInfo:(id)arg1;	// IMP=0x00100000001dd0ab
- (void)_keychainMigrationComplete:(id)arg1;	// IMP=0x00100000001dcc9c
- (void)_needsEncryptionIdentityRoll:(id)arg1;	// IMP=0x00100000001dcc37
- (void)_identityGenerated:(id)arg1;	// IMP=0x00100000001dcb8a
- (void)_identityRebuilt:(id)arg1;	// IMP=0x00100000001dcb25
- (void)_deregisterDeviceCenterNotifications;	// IMP=0x00100000001dc9c8
- (void)_registerForDeviceCenterNotifications;	// IMP=0x00100000001dc82f
- (void)_registrationAbilityChanged:(id)arg1;	// IMP=0x00100000001dc6a2
- (_Bool)isRegistrationActive;	// IMP=0x00100000001dc68b
- (_Bool)isDeviceAuthenticated;	// IMP=0x00100000001dc642
- (_Bool)isDeviceRegistered;	// IMP=0x00100000001dc5a5
- (void)refreshAdHocServiceNames;	// IMP=0x00100000001dc063
- (_Bool)_rebuildRegistrationInfo:(_Bool)arg1;	// IMP=0x00100000001d95a0
- (int)_neededRegistrationType;	// IMP=0x00100000001d954d
- (void)_updateCallerIDToTemporaryPhone;	// IMP=0x00100000001d928b
- (void)_updatePhoneNumberCallerID;	// IMP=0x00100000001d8de9
- (_Bool)_hasBudgetForForcedGDR;	// IMP=0x00100000001d89f2
- (void)_updatePerformedForcedGDRDate;	// IMP=0x00100000001d88cf
- (id)_performedForcedGDRDatePeriod;	// IMP=0x00100000001d87d4
- (void)_clearForcedGDRDate;	// IMP=0x00100000001d8790
- (void)_clearForcedGDRCount;	// IMP=0x00100000001d874c
- (void)_incrementForcedGDRCount;	// IMP=0x00100000001d86bd
- (int)_currentForcedGDRCount;	// IMP=0x00100000001d8648
- (_Bool)_isBuddyShowing;	// IMP=0x00100000001d862f
- (id)userDefaults;	// IMP=0x00100000001d8616
- (id)systemMonitor;	// IMP=0x00100000001d85fd
- (id)peerIDManager;	// IMP=0x00100000001d85e4
- (id)serviceController;	// IMP=0x00100000001d85cb
- (id)accountController;	// IMP=0x00100000001d85b2
- (id)appleIDNotificationCenter;	// IMP=0x00100000001d8599
- (id)registrationCenter;	// IMP=0x00100000001d8580
- (_Bool)shouldIncludeDefaultDeviceAsDestinationForMessageForFromID:(id)arg1;	// IMP=0x001000000030227a
- (id)pairingManager;	// IMP=0x0010000000302261
- (void);	// IMP=0x0010000000301b2c
- (void)sendMessage:(id)arg1 params:(id)arg2 bulkedPayload:(id)arg3 fromID:(id)arg4 toDestinations:(id)arg5 useDictAsTopLevel:(_Bool)arg6 dataToEncrypt:(id)arg7 encryptPayload:(_Bool)arg8 wantsResponse:(_Bool)arg9 expirationDate:(id)arg10 command:(id)arg11 wantsDeliveryStatus:(_Bool)arg12 wantsCertifiedDelivery:(_Bool)arg13 deliveryStatusContext:(id)arg14 messageUUID:(id)arg15 priority:(long long)arg16 localDelivery:(_Bool)arg17 disallowRefresh:(_Bool)arg18 willSendBlock:(CDUnknownBlockType)arg19 completionBlock:(CDUnknownBlockType)arg20;	// IMP=0x001000000030165f
- (void)sendMessageWithSendParameters:(id)arg1 willSendBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000002fdf6a
- (void)_rapportSendWithSendParameters:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000002fdc1b
- (void)_sendRemotelyWithSendParameters:(id)arg1 data:(id)arg2 protobuf:(id)arg3 willSendBlock:(CDUnknownBlockType)arg4 completionBlock:(CDUnknownBlockType)arg5;	// IMP=0x00100000002f93b0
- (void)_sendLocallyWithSendParameters:(id)arg1 uriToLocalDestination:(id)arg2 data:(id)arg3 protobuf:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;	// IMP=0x00100000002f67f2
- (id)utunDeliveryController;	// IMP=0x00100000002f67d9
- (void)_splitDestinations:(id)arg1 intoLocalDestinations:(id *)arg2 remoteDestinations:(id *)arg3 rapportDestinations:(id *)arg4 sendParameters:(id)arg5;	// IMP=0x00100000002f38fb
- (void)sendServerMessage:(id)arg1 command:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000002f337b
- (void)_sendMessageWithSendParametersOnMainThread:(id)arg1 filteredDestinations:(id)arg2 data:(id)arg3 compressedData:(id)arg4 protobufToSend:(id)arg5 willSendBlock:(CDUnknownBlockType)arg6 completionBlock:(CDUnknownBlockType)arg7;	// IMP=0x00100000002f1d03
- (id)newSendMessageContext;	// IMP=0x00100000002f17cb
- (long long)maxRemoteMessagingPayloadSize;	// IMP=0x00100000002f1743

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

