//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSXPCConnection, NSString;
@protocol OS_dispatch_queue;

@interface IDSDXPCInternalTesting : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    IDSXPCConnection *_connection;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000d94cc
@property(readonly, nonatomic) IDSXPCConnection *connection; // @synthesize connection=_connection;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)fetchXPCStateDescriptionForProcesses:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d8c23
- (void)triggerRestrictedMessageCleanup;	// IMP=0x00100000000d8bdf
- (void)triggerAllFirewallNotificationsWithHandle:(id)arg1 delay:(double)arg2 service:(id)arg3;	// IMP=0x00100000000d8862
- (void)triggerFirewallDBCleanupWithInterval:(double)arg1;	// IMP=0x00100000000d880c
- (id)_registeredIdentityTimestamps;	// IMP=0x00100000000d86ab
- (void)assertTransportThreadRealTimeMode:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d8633
- (void)deviceChangedForDeviceID:(id)arg1 isNearby:(_Bool)arg2 isConnected:(_Bool)arg3 isCloudConnected:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x00100000000d837d
- (void)removeConnectionWithConnectionName:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d81d3
- (void)clearCacheAndUpdatePeersForService:(id)arg1;	// IMP=0x00100000000d8166
- (void)fetchPrivateDeviceDataDescription:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d80b9
- (void)fetchPrivateClientDataDescriptionForService:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d7b11
- (void)fetchStoredUserDescriptions:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d71bd
- (void)nukeTransparencyStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d70ce
- (void)updateCurrentDeviceInKVS:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d7004
- (void)fetchCurrentDeviceKVSKey:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d6f3a
- (void)removeAllKVSTrustedDevices:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d6e70
- (void)fetchVerifierKVSTrustedDevicesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d6da6
- (void)kickVerificationForServiceIdentifier:(id)arg1 localURI:(id)arg2 remoteURI:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000d6c6c
- (void)fetchTransparentEndpointsForServiceIdentifier:(id)arg1 localURI:(id)arg2 remoteURI:(id)arg3 verifyAgainstTrustCircle:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00100000000d68bb
- (void)fetchEndpointCacheStateForServiceIdentifier:(id)arg1 localURI:(id)arg2 remoteURI:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000d6176
- (id)transparentEndpointViewer;	// IMP=0x00100000000d611f
- (void)postNewDeviceNotification:(id)arg1 iCloudSignIn:(_Bool)arg2 iMessageSignIn:(_Bool)arg3 facetimeSignIn:(_Bool)arg4 forAppleID:(id)arg5;	// IMP=0x00100000000d5f76
- (void)toggleDisableDeviceUserToDisabled:(_Bool)arg1;	// IMP=0x00100000000d5ec9
- (void)sendFakePushFromFile:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d5ec3
- (_Bool)hasEntitlementForPushReplay;	// IMP=0x00100000000d5de8
- (void)forceAccountRenewalOnService:(id)arg1;	// IMP=0x00100000000d5c13
- (void)autoBugCaptureWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d5b66
- (void)popupPromptWithTitle:(id)arg1 message:(id)arg2 defaultButton:(id)arg3 defaultUrl:(id)arg4 alternateButton:(id)arg5 alternatrUrl:(id)arg6 completion:(CDUnknownBlockType)arg7;	// IMP=0x00100000000d5a4e
- (void)tapToRadarWithTitle:(id)arg1 message:(id)arg2 context:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000d595d
- (void)checkServerStorageForService:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d58c6
- (void)setECVersion:(unsigned int)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d5844
- (void)currentECVersionWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d57aa
- (void)setForceKeyRoll:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d572c
- (void)triggerKeyRollWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d52ea
- (void)registeredIdentityTimestampsWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d528a
- (void)clearCacheWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d51e4
- (void)oneToOneECCQuicktestEncryptionWithData:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d4a67
- (id)initWithQueue:(id)arg1 connection:(id)arg2;	// IMP=0x00100000000d49aa

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

