//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface IDSLinkPreferencesManager : NSObject
{
    struct _opaque_pthread_mutex_t _preferencesLock;	// 8 = 0x8
    NSMutableDictionary *_servicesWithPreferences;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_power_log_queue;	// 80 = 0x50
}

+ (id)sharedInstance;	// IMP=0x0040000000126f75
- (void).cxx_destruct;	// IMP=0x002000000012801d
- (void)_logRequestInPowerDictionaryForService:(id)arg1 preferences:(id)arg2;	// IMP=0x0010000000127f3e
- (id)accumulativePreferencesForAllServices;	// IMP=0x0010000000127980
- (id)preferencesForService:(id)arg1;	// IMP=0x0010000000127919
- (_Bool)_validatePreferences:(id)arg1 forService:(id)arg2;	// IMP=0x0010000000127711
- (void)resetPreferencesForAllServices;	// IMP=0x00100000001272f9
- (void)updateService:(id)arg1 withPreferences:(id)arg2;	// IMP=0x00100000001270d3
- (void)dealloc;	// IMP=0x0010000000127071
- (id)init;	// IMP=0x0010000000126fca

@end

