//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSQueryKeyTransparencyContext, NSArray;

@interface IDSPeerIDValue : NSObject
{
    NSArray *_endpoints;	// 8 = 0x8
    IDSQueryKeyTransparencyContext *_keyTransparencyContext;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000001cdbdd
+ (id)peerIDValueWithEndpoints:(id)arg1 keyTransparencyContext:(id)arg2;	// IMP=0x00100000001cd75b
- (void).cxx_destruct;	// IMP=0x00200000001cdda8
@property(readonly, nonatomic) IDSQueryKeyTransparencyContext *keyTransparencyContext; // @synthesize keyTransparencyContext=_keyTransparencyContext;
@property(readonly, nonatomic) NSArray *endpoints; // @synthesize endpoints=_endpoints;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000001cdce6
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000001cdbe5
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000001cdbd2
- (id)description;	// IMP=0x00100000001cdb0a
- (unsigned long long)hash;	// IMP=0x00100000001cdac6
- (_Bool)isEqualToPeerIDValue:(id)arg1;	// IMP=0x00100000001cd8e5
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001cd882
- (id)initWithEndpoints:(id)arg1 keyTransparencyContext:(id)arg2;	// IMP=0x00100000001cd7c9

@end

