//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@protocol TVSSNowPlayingTransportBarObserver <NSObject>
- (void)transportBarDidUpdateWithTimeElapsed:(double)arg1 timeRemaining:(double)arg2 percentComplete:(double)arg3;
@end

