//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemPanelUI/TVSPPlatterController.h>

@class MRNowPlayingAudioFormatController, NSString, PBSVolumeButtonEventAssertion, PBSVolumeHUDAssertion, TVCSAudioRoutingController, TVSSAudioNowPlayingController, TVSSMenuModeController;
@protocol TVCSAudioRoute;

@interface TVSSHeadphonesPanelPlatterController : TVSPPlatterController
{
    TVCSAudioRoutingController *_routingController;	// 8 = 0x8
    MRNowPlayingAudioFormatController *_audioFormatController;	// 16 = 0x10
    id <TVCSAudioRoute> _primaryRoute;	// 24 = 0x18
    id <TVCSAudioRoute> _secondaryRoute;	// 32 = 0x20
    PBSVolumeButtonEventAssertion *_volumeButtonAssertion;	// 40 = 0x28
    PBSVolumeHUDAssertion *_volumeHUDAssertion;	// 48 = 0x30
    id <TVCSAudioRoute> _focusedVolumeRoute;	// 56 = 0x38
    TVSSAudioNowPlayingController *_audioNowPlayingController;	// 64 = 0x40
    TVSSMenuModeController *_menuModeController;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x00200000000dae60
@property(retain, nonatomic) TVSSMenuModeController *menuModeController; // @synthesize menuModeController=_menuModeController;
@property(retain, nonatomic) TVSSAudioNowPlayingController *audioNowPlayingController; // @synthesize audioNowPlayingController=_audioNowPlayingController;
@property(retain, nonatomic) id <TVCSAudioRoute> focusedVolumeRoute; // @synthesize focusedVolumeRoute=_focusedVolumeRoute;
@property(retain, nonatomic) PBSVolumeHUDAssertion *volumeHUDAssertion; // @synthesize volumeHUDAssertion=_volumeHUDAssertion;
@property(retain, nonatomic) PBSVolumeButtonEventAssertion *volumeButtonAssertion; // @synthesize volumeButtonAssertion=_volumeButtonAssertion;
@property(retain, nonatomic) id <TVCSAudioRoute> secondaryRoute; // @synthesize secondaryRoute=_secondaryRoute;
@property(retain, nonatomic) id <TVCSAudioRoute> primaryRoute; // @synthesize primaryRoute=_primaryRoute;
@property(retain, nonatomic) MRNowPlayingAudioFormatController *audioFormatController; // @synthesize audioFormatController=_audioFormatController;
@property(retain, nonatomic) TVCSAudioRoutingController *routingController; // @synthesize routingController=_routingController;
- (id)_routeFromItemIdentifier:(id)arg1;	// IMP=0x00100000000daa70
- (id)_hierarchicalColorsForMenuOffPersonSymbol;	// IMP=0x00100000000da870
- (id)_packageNameForCurrentSpatializeStereoState;	// IMP=0x00100000000da7d0
- (id)_packageNameForCurrentSpatialState;	// IMP=0x00100000000da730
- (id)_packageNameForListeningMode:(long long)arg1;	// IMP=0x00100000000da650
- (id)_localizedValueForCurrentSpatializeStereoState;	// IMP=0x00100000000da520
- (id)_localizedValueForCurrentSpatialState;	// IMP=0x00100000000da430
- (id)_localizedValueFromConversationDetectState:(_Bool)arg1;	// IMP=0x00100000000da3c0
- (id)_systemImageForListeningMode:(long long)arg1;	// IMP=0x00100000000da220
- (id)_localizedValueFromListeningMode:(long long)arg1;	// IMP=0x00100000000da130
- (void)_toggleSpatializeStereoForBothHeadsets;	// IMP=0x00100000000d9f20
- (void)_setHeadTrackingEnabledOnBothHeadsets:(_Bool)arg1;	// IMP=0x00100000000d9dd0
- (void)_setSpatialAudioModeOnBothHeadsets:(long long)arg1;	// IMP=0x00100000000d9c80
- (_Bool)_bothHeadsetsSupportSpatialWhileSharing;	// IMP=0x00100000000d9b50
- (_Bool)_splitterSpatialActive;	// IMP=0x00100000000d9a60
- (_Bool)_splitterPreventingSpatial;	// IMP=0x00100000000d9960
- (_Bool)_spatializeStereoEnabled;	// IMP=0x00100000000d97e0
- (_Bool)_spatialAndHeadTrackingEnabled;	// IMP=0x00100000000d96e0
- (_Bool)_spatialFixedEnabled;	// IMP=0x00100000000d95e0
- (_Bool)_currentModeAllowsSpatialAudio;	// IMP=0x00100000000d9510
- (id)_currentAppBundleID;	// IMP=0x00100000000d92d0
- (_Bool)_spatialEnabledGlobally;	// IMP=0x00100000000d90a0
- (_Bool)_currentAppCanBeIneligibleForSpatialization;	// IMP=0x00100000000d9030
- (_Bool)_headTrackingDisabled;	// IMP=0x00100000000d9010
- (_Bool)_spatialUnavailable;	// IMP=0x00100000000d8f80
- (id)_resolvedAudioFormat;	// IMP=0x00100000000d8d40
- (_Bool)_headTrackingCurrentlySupported;	// IMP=0x00100000000d8ce0
- (_Bool)_currentAppSupportsHeadTracking;	// IMP=0x00100000000d8c70
- (_Bool)_deviceSupportsSpatial;	// IMP=0x00100000000d8c50
- (_Bool)_currentAudioContentInfoEligibleForSpatialization;	// IMP=0x00100000000d8aa0
- (_Bool)_currentAppSupportsSpatial;	// IMP=0x00100000000d89c0
- (_Bool)_resolvedSpatialAudioModeIsOff;	// IMP=0x00100000000d8930
- (_Bool)_resolvedSpatialAudioModeIsFixed;	// IMP=0x00100000000d8880
- (_Bool)_resolvedSpatialAudioModeIsHeadTracked;	// IMP=0x00100000000d87f0
- (id)_symbolForBatteryLevel:(id)arg1;	// IMP=0x00100000000d85c0
- (_Bool)_shouldShowSeparateBatteryPercentagesForBatteryLevel:(id)arg1;	// IMP=0x00100000000d8410
- (void)_toggleSpatializeStereoForHeadphone:(id)arg1;	// IMP=0x00100000000d8230
- (void)_updateSpatialModeForHeadphone:(id)arg1 spatialMode:(long long)arg2 headTrackingEnabled:(_Bool)arg3;	// IMP=0x00100000000d8020
- (void)_updateListeningModeForHeadphone:(id)arg1 listeningMode:(long long)arg2;	// IMP=0x00100000000d7f80
- (id)_headTrackingRendererForHeadphone:(id)arg1;	// IMP=0x00100000000d7ce0
- (id)_speechDetectRendererForIdentifier:(id)arg1;	// IMP=0x00100000000d7a70
- (id)_noiseControlRendererForIdentifier:(id)arg1;	// IMP=0x00100000000d77e0
- (void)_updateContent:(id)arg1 withBatteryLevel:(id)arg2;	// IMP=0x00100000000d6fa0
- (void)_refreshVolumeRenderers;	// IMP=0x00100000000d6a60
- (void)_refreshSpatializeStereoRenderer;	// IMP=0x00100000000d6760
- (void)_refreshHeadTrackingRenderer;	// IMP=0x00100000000d64a0
- (void)_refreshAudioFormatRenderer;	// IMP=0x00100000000d6060
- (void)_refreshConversationDetectRenderer;	// IMP=0x00100000000d5dc0
- (void)_refreshNoiseControlRenderers;	// IMP=0x00100000000d5890
- (void)_refreshHeadphoneSettingsRenderers;	// IMP=0x00100000000d5830
- (void)_updatePanelAnimated:(_Bool)arg1;	// IMP=0x00100000000d48c0
- (void)accessorySettingsChanged:(id)arg1;	// IMP=0x00100000000d4870
- (void)nowPlayingAudioFormatController:(id)arg1 didChangeAudioFormatContentInfo:(id)arg2;	// IMP=0x00100000000d47f0
- (void)audioRoutingController:(id)arg1 routeDidUpdate:(id)arg2 withChangedProperties:(id)arg3;	// IMP=0x00100000000d4600
- (void)audioRoutingController:(id)arg1 didUpdateAvailableRoutes:(id)arg2;	// IMP=0x00100000000d44e0
- (void)didPressMute:(id)arg1;	// IMP=0x00100000000d43e0
- (void)handleVolumeDown;	// IMP=0x00100000000d4280
- (void)handleVolumeUp;	// IMP=0x00100000000d4120
- (void)rendererWasUpdated:(id)arg1;	// IMP=0x00100000000d3f10
- (id)contextMenuConfigurationForRenderer:(id)arg1;	// IMP=0x00100000000d2930
- (void)rendererLostFocus:(id)arg1;	// IMP=0x00100000000d2800
- (void)rendererGainedFocus:(id)arg1;	// IMP=0x00100000000d2600
- (void)rendererWasSelected:(id)arg1 context:(id)arg2;	// IMP=0x00100000000d22e0
- (void)platterControllerDidActivate;	// IMP=0x00100000000d2220
- (void)dealloc;	// IMP=0x00100000000d20c0
- (id)initWithAudioNowPlayingController:(id)arg1 menuModeController:(id)arg2;	// IMP=0x00100000000d0ab0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

