//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemPanelUI/TVSPRenderer.h>

@class MISSING_TYPE;

@interface TVSSGameControllersHelpTextRenderer : TVSPRenderer
{
}

+ (id)rendererWithIdentifier:(id)arg1 text:(id)arg2;	// IMP=0x0040000000054030
- (MISSING_TYPE *)stylingForState:identifier: /* Error: Ran out of types for this method. */;	// IMP=0x0040000000054b40

@end

