//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class TVSSPrivacyState, TVSSPrivacyView;

@interface TVSSPrivacyStateAdapterView : UIView
{
    long long _displayLocation;	// 8 = 0x8
    TVSSPrivacyState *_privacyState;	// 16 = 0x10
    TVSSPrivacyView *_privacyView;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000ee7d0
@property(retain, nonatomic) TVSSPrivacyView *privacyView; // @synthesize privacyView=_privacyView;
@property(retain, nonatomic) TVSSPrivacyState *privacyState; // @synthesize privacyState=_privacyState;
@property(readonly, nonatomic) long long displayLocation; // @synthesize displayLocation=_displayLocation;
- (void)_updateLocationIndicatorView;	// IMP=0x00100000000ee610
- (void)_updateRecordingIndicatorView;	// IMP=0x00100000000ee330
- (void)_updatePrivacyStackView;	// IMP=0x00100000000ee2f0
- (void)dealloc;	// IMP=0x00100000000ee1d0
- (id)initWithDisplayLocation:(long long)arg1;	// IMP=0x00100000000edd20

@end

