//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemPanelUI/TVSPRenderer.h>

@interface TVSSCriticalInfoRenderer : TVSPRenderer
{
}

- (id)layoutConstraintsWithSubviews:(id)arg1 contentView:(id)arg2;	// IMP=0x00400000000fed50
- (id)subviewIdentifiersWantingAutolayout;	// IMP=0x00100000000febf0
- (id)stylingForState:(unsigned long long)arg1 identifier:(id)arg2;	// IMP=0x00100000000fe750
- (id)initWithIdentifier:(id)arg1 criticalInfo:(id)arg2;	// IMP=0x00100000000fdf60

@end

