//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSSet, TVSSBannerManager;

@protocol TVSSBannerManagerDelegate
- (void)bannerManagerRelinquishesFocus:(TVSSBannerManager *)arg1;
- (void)bannerManagerRequestsFocus:(TVSSBannerManager *)arg1;
- (void)bannerManager:(TVSSBannerManager *)arg1 relinquishesExternalGestures:(NSSet *)arg2;
- (void)bannerManager:(TVSSBannerManager *)arg1 requestsExternalGestures:(NSSet *)arg2;
@end

