//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSTimer, TVSSImageContent, TVSSMenuItem;

@interface TVSSExampleMenuItemProvider
{
    long long _counter;	// 8 = 0x8
    NSTimer *_timer;	// 16 = 0x10
    TVSSMenuItem *_primaryItem;	// 24 = 0x18
    TVSSMenuItem *_secondaryItem;	// 32 = 0x20
    TVSSMenuItem *_tertiaryItem;	// 40 = 0x28
    TVSSMenuItem *_countItem;	// 48 = 0x30
    TVSSImageContent *_imageContent1;	// 56 = 0x38
    TVSSImageContent *_imageContent2;	// 64 = 0x40
    TVSSImageContent *_imageContent3;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x002000000005f300
@property(retain, nonatomic) TVSSImageContent *imageContent3; // @synthesize imageContent3=_imageContent3;
@property(retain, nonatomic) TVSSImageContent *imageContent2; // @synthesize imageContent2=_imageContent2;
@property(retain, nonatomic) TVSSImageContent *imageContent1; // @synthesize imageContent1=_imageContent1;
@property(retain, nonatomic) TVSSMenuItem *countItem; // @synthesize countItem=_countItem;
@property(retain, nonatomic) TVSSMenuItem *tertiaryItem; // @synthesize tertiaryItem=_tertiaryItem;
@property(retain, nonatomic) TVSSMenuItem *secondaryItem; // @synthesize secondaryItem=_secondaryItem;
@property(retain, nonatomic) TVSSMenuItem *primaryItem; // @synthesize primaryItem=_primaryItem;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void)_handleTimerTick;	// IMP=0x001000000005ebc0
- (void)dealloc;	// IMP=0x001000000005eb60
- (id)init;	// IMP=0x001000000005e650

@end

