//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TVSSDebugAllProvidersViewController
{
}

- (id)debugEntries;	// IMP=0x004000000001d460

@end

