//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface NSObject
{
    Class isa;	// 0 = 0x0
}

+ (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000235ed
+ (id)mutableCopy;	// IMP=0x00100000000235e9
+ (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000235e5
+ (id)copy;	// IMP=0x00100000000235e1
+ (struct _NSZone *)zone;	// IMP=0x00100000000235de
+ (void)dealloc;	// IMP=0x00100000000235dd
+ (id)init;	// IMP=0x00100000000235d9
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000235d4
+ (id)alloc;	// IMP=0x00100000000235cf
+ (unsigned long long)retainCount;	// IMP=0x00100000000235c7
+ (id)autorelease;	// IMP=0x00100000000235c3
+ (oneway void)release;	// IMP=0x00100000000235c2
+ (_Bool)retainWeakReference;	// IMP=0x00100000000235bf
+ (_Bool)allowsWeakReference;	// IMP=0x00100000000235bc
+ (_Bool)_isDeallocating;	// IMP=0x00100000000235b9
+ (_Bool)_tryRetain;	// IMP=0x00100000000235b6
+ (id)retain;	// IMP=0x00100000000235b2
+ (id)new;	// IMP=0x0010000000023580
+ (id)debugDescription;	// IMP=0x0010000000023573
+ (id)description;	// IMP=0x0010000000023570
+ (id)forwardingTargetForSelector:(SEL)arg1;	// IMP=0x001000000002356d
+ (void)forwardInvocation:(id)arg1;	// IMP=0x0010000000023532
+ (id)methodSignatureForSelector:(SEL)arg1;	// IMP=0x0010000000023520
+ (id)instanceMethodSignatureForSelector:(SEL)arg1;	// IMP=0x001000000002350e
+ (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;	// IMP=0x00100000000234c6
+ (id)performSelector:(SEL)arg1 withObject:(id)arg2;	// IMP=0x0010000000023483
+ (id)performSelector:(SEL)arg1;	// IMP=0x001000000002344f
+ (void)doesNotRecognizeSelector:(SEL)arg1;	// IMP=0x001000000002341b
+ (_Bool)resolveInstanceMethod:(SEL)arg1;	// IMP=0x0010000000023418
+ (_Bool)resolveClassMethod:(SEL)arg1;	// IMP=0x0010000000023415
+ (CDUnknownFunctionPointerType)methodForSelector:(SEL)arg1;	// IMP=0x00100000000233f1
+ (CDUnknownFunctionPointerType)instanceMethodForSelector:(SEL)arg1;	// IMP=0x00100000000233cd
+ (_Bool)isProxy;	// IMP=0x00100000000233ca
+ (_Bool)isFault;	// IMP=0x00100000000233c7
+ (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000233c0
+ (unsigned long long)hash;	// IMP=0x00100000000233bc
+ (_Bool)conformsToProtocol:(id)arg1;	// IMP=0x0010000000023386
+ (_Bool)respondsToSelector:(SEL)arg1;	// IMP=0x0010000000023378
+ (_Bool)instancesRespondToSelector:(SEL)arg1;	// IMP=0x0010000000023368
+ (_Bool)isAncestorOfObject:(id)arg1;	// IMP=0x001000000002332d
+ (_Bool)isSubclassOfClass:(Class)arg1;	// IMP=0x0010000000023317
+ (_Bool)isKindOfClass:(Class)arg1;	// IMP=0x00100000000232ff
+ (_Bool)isMemberOfClass:(Class)arg1;	// IMP=0x00100000000232f8
+ (Class)superclass;	// IMP=0x00100000000232f3
+ (Class)class;	// IMP=0x00100000000232ef
+ (id)self;	// IMP=0x00100000000232eb
+ (void)initialize;	// IMP=0x00100000000232ea
- (id)mutableCopy;	// IMP=0x000000000002394b
- (id)copy;	// IMP=0x000000000002393c
- (struct _NSZone *)zone;	// IMP=0x0000000000023939
- (void)finalize;	// IMP=0x0000000000023938
- (void)dealloc;	// IMP=0x0000000000023916
- (id)init;	// IMP=0x0000000000023912
- (unsigned long long)retainCount;	// IMP=0x0000000000023905
- (id)autorelease;	// IMP=0x0000000000023900
- (oneway void)release;	// IMP=0x00000000000238fb
- (_Bool)retainWeakReference;	// IMP=0x00000000000238ee
- (_Bool)allowsWeakReference;	// IMP=0x00000000000238d9
- (_Bool)_isDeallocating;	// IMP=0x00000000000238cd
- (_Bool)_tryRetain;	// IMP=0x00000000000238c1
- (id)retain;	// IMP=0x00000000000238bc
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (id)forwardingTargetForSelector:(SEL)arg1;	// IMP=0x00000000000238a9
- (void)forwardInvocation:(id)arg1;	// IMP=0x000000000002386e
- (id)methodSignatureForSelector:(SEL)arg1;	// IMP=0x000000000002385c
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;	// IMP=0x0000000000023814
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;	// IMP=0x00000000000237d1
- (id)performSelector:(SEL)arg1;	// IMP=0x000000000002379d
- (void)doesNotRecognizeSelector:(SEL)arg1;	// IMP=0x0000000000023769
- (CDUnknownFunctionPointerType)methodForSelector:(SEL)arg1;	// IMP=0x0000000000023745
- (_Bool)isProxy;	// IMP=0x0000000000023742
- (_Bool)isFault;	// IMP=0x000000000002373f
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000000023738
@property(readonly) unsigned long long hash;
- (_Bool)conformsToProtocol:(id)arg1;	// IMP=0x00000000000236ef
- (_Bool)respondsToSelector:(SEL)arg1;	// IMP=0x00000000000236c3
- (_Bool)isKindOfClass:(Class)arg1;	// IMP=0x000000000002368b
- (_Bool)isMemberOfClass:(Class)arg1;	// IMP=0x0000000000023668
@property(readonly) Class superclass;
- (Class)class;	// IMP=0x0000000000023612
- (id)self;	// IMP=0x000000000002360e

@end

