//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppleMediaServices/AMSTask.h>

@interface FamilyRequestTask : AMSTask
{
}

- (long long)_familyMemberTypeFromFamily:(id)arg1;	// IMP=0x004000000000de7c
- (id)_performWithFamilyRequest:(id)arg1;	// IMP=0x001000000000d8d3
- (id)perform;	// IMP=0x001000000000d887

@end

