//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppleMediaServices/AMSURLSession.h>

@interface URLSession : AMSURLSession
{
}

+ (id)sharedSession;	// IMP=0x00200000000200af
- (id)delegate;	// IMP=0x0040000000020154
- (id)initWithConfiguration:(id)arg1;	// IMP=0x0010000000020035

@end

