//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface MASAutoAssetSetProgress : NSObject
{
}

+ (id)newShimmedFromFrameworkMessage:(id)arg1 forKey:(id)arg2;	// IMP=0x008000000013417d
+ (id)newShimmedFromFramework:(id)arg1;	// IMP=0x0080000000133f8c
+ (id)newShimmedToFramework:(id)arg1;	// IMP=0x0080000000133db9
+ (id)newServerMessageClasses:(id)arg1;	// IMP=0x0080000000133d3c

@end

