//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface MASAutoAssetSetOverview : NSObject
{
}

+ (id)newShimmedFromFrameworkMessage:(id)arg1 forKey:(id)arg2;	// IMP=0x0080000000003393
+ (id)newShimmedFromFramework:(id)arg1;	// IMP=0x008000000000315a
+ (id)newShimmedArrayToFramework:(id)arg1;	// IMP=0x0080000000002df5
+ (id)newShimmedToFramework:(id)arg1;	// IMP=0x0080000000002d60
+ (id)newServerMessageClasses:(id)arg1;	// IMP=0x0080000000002c8f

@end

