//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APSDecayTimer, CUTWeakReference, NSDate, NSMutableArray, NSString, PCSimpleTimer;
@protocol APSNetworkMonitorDelegate;

@interface APSNetworkMonitor : NSObject
{
    CUTWeakReference *_delegate;	// 8 = 0x8
    NSString *_lastSSID;	// 16 = 0x10
    NSMutableArray *_wifiMeasurements;	// 24 = 0x18
    unsigned long long _wifiGrowAttemptsBeforeSSID;	// 32 = 0x20
    unsigned long long _wifiGrowAttempts;	// 40 = 0x28
    double _wifiKeepAliveInterval;	// 48 = 0x30
    APSDecayTimer *_decayTimer;	// 56 = 0x38
    PCSimpleTimer *_connectionThrottleTimer;	// 64 = 0x40
    PCSimpleTimer *_piggybackConnectionTimer;	// 72 = 0x48
    _Bool _shouldThrottleConnection;	// 80 = 0x50
    _Bool _serverSupportsDualMode;	// 81 = 0x51
    long long _dualMode;	// 88 = 0x58
    NSDate *_lastPiggybackReset;	// 96 = 0x60
    NSDate *_lastPiggybackConnection;	// 104 = 0x68
    unsigned long long _piggybackCount;	// 112 = 0x70
    unsigned long long _maxCostDrivenConnectionsPerDay;	// 120 = 0x78
    unsigned long long _maxPiggybackConnectionsPerDay;	// 128 = 0x80
    _Bool _disableCostDrivenDualMode;	// 136 = 0x88
    _Bool _shouldUseDualMode;	// 137 = 0x89
    _Bool _criticalReliability;	// 138 = 0x8a
    _Bool _isWoWEnabled;	// 139 = 0x8b
    _Bool _isPiggybacking;	// 140 = 0x8c
    _Bool _disableDualModePiggybackTimer;	// 141 = 0x8d
}

+ (unsigned long long)powerCostForPushOnRAT:(int)arg1 withLinkQuality:(int)arg2;	// IMP=0x00200000000bf7d4
- (void).cxx_destruct;	// IMP=0x00200000000bfca8
@property(nonatomic) _Bool isWoWEnabled; // @synthesize isWoWEnabled=_isWoWEnabled;
@property(readonly, nonatomic) _Bool shouldUseDualMode; // @synthesize shouldUseDualMode=_shouldUseDualMode;
@property(nonatomic) _Bool serverSupportsDualMode; // @synthesize serverSupportsDualMode=_serverSupportsDualMode;
- (void)setDisableDualModePiggybackTimer:(id)arg1;	// IMP=0x00100000000bfb7f
- (void)setPiggybackDualChannelAttempts:(id)arg1;	// IMP=0x00100000000bfa8f
- (void)setCostDrivenDualChannelAttempts:(id)arg1;	// IMP=0x00100000000bf9a5
- (void)setDisableCostDrivenDualChannelAttempts:(id)arg1;	// IMP=0x00100000000bf8a9
- (void)setCriticalReliability:(_Bool)arg1;	// IMP=0x00100000000bf7df
- (void)closedSecondChannel:(long long)arg1;	// IMP=0x00100000000bf486
- (void)openedSecondChannel;	// IMP=0x00100000000befbb
@property(readonly, nonatomic) _Bool isPiggybacking;
- (void)_piggybackConnectionTimerFired;	// IMP=0x00100000000bef70
- (void)_clearPiggybackConnectionTimer;	// IMP=0x00100000000bef3e
- (void)_connectionThrottleTimerFired;	// IMP=0x00100000000bef0c
- (void)_clearConnectionThrottleTimer;	// IMP=0x00100000000beeda
- (void)_toggleWiFiAutoAssociateIfNecessary;	// IMP=0x00100000000bede7
- (void)__toggleWiFiAutoAssociateIfNecessary;	// IMP=0x00100000000be8b2
- (_Bool)_checkPiggybackBudget;	// IMP=0x00100000000be66f
- (int)secondsBetweenPiggybacks;	// IMP=0x00100000000be664
- (void)notePushWithCost:(unsigned long long)arg1;	// IMP=0x00100000000be632
- (void)_handleSignificantTimeChange;	// IMP=0x00100000000be604
- (void)_flushStaleElementsFrom:(id *)arg1 withThreshold:(double)arg2;	// IMP=0x00100000000be368
- (void)setCurrentWiFiKeepAliveInterval:(double)arg1 growAttempts:(unsigned long long)arg2;	// IMP=0x00100000000be2a8
- (_Bool)_wifiIsHistoricallyCheap;	// IMP=0x00100000000be190
- (double)_accumulatedAwakePercentage;	// IMP=0x00100000000bdedb
- (void)_flushStaleWiFiMeasurements;	// IMP=0x00100000000bdebd
- (void)_processSSIDChangeWithSSID:(id)arg1 querySSID:(_Bool)arg2;	// IMP=0x00100000000bdd46
- (void)cutWiFiManager:(id)arg1 generatedPowerReading:(id)arg2;	// IMP=0x00100000000bd87b
- (void)cutWiFiManagerLinkDidChange:(id)arg1 context:(id)arg2;	// IMP=0x00100000000bd671
- (void)systemDidUnlock;	// IMP=0x00100000000bd5e8
- (void)systemDidLock;	// IMP=0x00100000000bd54d
- (void)decayTimerFired:(id)arg1;	// IMP=0x00100000000bd4c4
- (void)_reloadDualMode;	// IMP=0x00100000000bd471
@property(nonatomic) id <APSNetworkMonitorDelegate> delegate;
- (void)dealloc;	// IMP=0x00100000000bd200
- (id)init;	// IMP=0x00100000000bcf58
- (void)_deregisterFromWoWNotifications;	// IMP=0x00100000000bcf52
- (void)_registerForWoWNotifications;	// IMP=0x00100000000bcf4c
- (id)systemMonitor;	// IMP=0x00100000000bcf33
- (id)wifiManager;	// IMP=0x00100000000bcf1a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

