//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APSCPPowerAssertion, NSMutableArray, NSTimer;

@interface APSOutgoingQueue : NSObject
{
    NSMutableArray *;	// 8 = 0x8
    NSTimer *_timer;	// 16 = 0x10
    double _lastReceivedAckOrReconnect;	// 24 = 0x18
    APSCPPowerAssertion *_powerAssertion;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000098ab2
- (void)_timerFired:(id)arg1;	// IMP=0x00100000000986b4
- (void)_recalculatePowerAssertion;	// IMP=0x001000000009843f
- (void)_recalculateTimer;	// IMP=0x0010000000097fe4
- (void)_queueChanged;	// IMP=0x0010000000097d86
- (void)clearEnqueuedSendsOnInterface:(id)arg1;	// IMP=0x0010000000097b7e
- (void)handleConnectionClosedOnInterface:(id)arg1;	// IMP=0x001000000009791f
- (void)handleConnectionOpened;	// IMP=0x00100000000978e5
- (void)handleResponseForPendingItem:(id)arg1 error:(id)arg2 onInterface:(id)arg3;	// IMP=0x00100000000975da
- (void)enqueueSendBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000097442

@end

