//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APSEnvironment, NSMutableDictionary;

@interface APSPushHistory : NSObject
{
    APSEnvironment *_environment;	// 8 = 0x8
    NSMutableDictionary *_history;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000006a879
- (_Bool)hasPayload:(id)arg1 forTopic:(id)arg2 tokens:(id)arg3;	// IMP=0x001000000006a49e
- (id)timestampForTopic:(id)arg1 token:(id)arg2;	// IMP=0x001000000006a30a
- (void)receivedPushWithTopic:(id)arg1 token:(id)arg2 payload:(id)arg3 timestamp:(id)arg4;	// IMP=0x001000000006a09b
- (id)_keyForTopic:(id)arg1 token:(id)arg2;	// IMP=0x001000000006a01d
- (void)_pruneHistory;	// IMP=0x0010000000069d76
- (id)initWithEnvironment:(id)arg1;	// IMP=0x0010000000069d0b

@end

