//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APSPayloadMessageStatsCount, APSPayloadMessageStatsCountsByWakeState;

@interface APSPayloadMessageStatsCounts : NSObject
{
    APSPayloadMessageStatsCount *_total;	// 8 = 0x8
    APSPayloadMessageStatsCountsByWakeState *_byWakeState;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000008206a
@property(retain, nonatomic) APSPayloadMessageStatsCountsByWakeState *byWakeState; // @synthesize byWakeState=_byWakeState;
@property(retain, nonatomic) APSPayloadMessageStatsCount *total; // @synthesize total=_total;
- (void)prepareForFullWake;	// IMP=0x0010000000081fe4
- (void)prepareForDarkWake;	// IMP=0x0010000000081f94
- (void)appendPrettyStatusToStatusPrinter:(id)arg1 total:(_Bool)arg2 direction:(id)arg3;	// IMP=0x0010000000081be6
- (void)_appendPrettyStatusToStatusPrinter:(id)arg1 time:(double)arg2 type:(id)arg3 direction:(id)arg4;	// IMP=0x0010000000081b43
- (void)countTopic:(id)arg1 now:(double)arg2;	// IMP=0x0010000000081ad5
- (id)init;	// IMP=0x0010000000081a60

@end

