//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface TASKNotifyAck : PBCodable
{
}

- (void)mergeFrom:(id)arg1;	// IMP=0x004000000007d4de
- (unsigned long long)hash;	// IMP=0x001000000007d4d6
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000007d493
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000007d45a
- (void)copyTo:(id)arg1;	// IMP=0x001000000007d454
- (void)writeTo:(id)arg1;	// IMP=0x001000000007d44e
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000007d441
- (id)dictionaryRepresentation;	// IMP=0x001000000007d32d
- (id)description;	// IMP=0x001000000007d27e

@end

