//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class UNUserNotificationCenter;

@interface NotificationManager : NSObject
{
    UNUserNotificationCenter *_notificationCenter;	// 8 = 0x8
}

+ (unsigned long long)_authorizationOptions;	// IMP=0x004000000007b532
+ (id)_notificationCategories;	// IMP=0x001000000007b3a1
+ (id)sharedManager;	// IMP=0x001000000007aebe
- (void).cxx_destruct;	// IMP=0x002000000007b53d
- (void)removeNotificationRequestWithIdentifier:(id)arg1;	// IMP=0x001000000007b2f8
- (void)postNotificationRequest:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000007af43
- (id)init;	// IMP=0x001000000007ad58

@end

