//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AKAccountManager, AKAuthorizationEndorserRapportDiscovery, AKAuthorizationRapportClient, AKAuthorizationSessionManager, AKClient, AKCredentialRequestContext, NSArray, NSString;
@protocol AKAuthorizationClientProtocol, AKAuthorizationDaemonServiceDelegate;

@interface AKAuthorizationDaemonService : NSObject
{
    struct os_unfair_lock_s _authorizationRealUserLock;	// 8 = 0x8
    id <AKAuthorizationClientProtocol>;	// 16 = 0x10
    AKAuthorizationSessionManager *_authSessionManager;	// 24 = 0x18
    NSString *_realUserVerificationResults;	// 32 = 0x20
    AKAccountManager *_accountManager;	// 40 = 0x28
    AKClient *_client;	// 48 = 0x30
    id <AKAuthorizationDaemonServiceDelegate> _delegate;	// 56 = 0x38
    AKAuthorizationRapportClient *_rapportClient;	// 64 = 0x40
    AKAuthorizationEndorserRapportDiscovery *_endorserRapportDiscovery;	// 72 = 0x48
    NSArray *_credentials;	// 80 = 0x50
    AKCredentialRequestContext *_originalRequestContext;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x0020000000096149
@property(retain, nonatomic) AKCredentialRequestContext *originalRequestContext; // @synthesize originalRequestContext=_originalRequestContext;
@property(copy, nonatomic) NSArray *credentials; // @synthesize credentials=_credentials;
@property(retain, nonatomic) AKAuthorizationEndorserRapportDiscovery *endorserRapportDiscovery; // @synthesize endorserRapportDiscovery=_endorserRapportDiscovery;
@property(retain, nonatomic) AKAuthorizationRapportClient *rapportClient; // @synthesize rapportClient=_rapportClient;
@property(nonatomic) __weak id <AKAuthorizationDaemonServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) AKClient *client; // @synthesize client=_client;
- (void)_processUserResponse:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000095b61
- (void)_validateAndProcessUserResponse:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000009586e
- (void)performAuthorizationWithContext:(id)arg1 withUserProvidedInformation:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000095675
- (void)presentAuthorizationUIForContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000009542c
- (void)_extractWebSessionAuthorizationFromResponse:(id)arg1;	// IMP=0x00100000000952c8
- (id)authorizationContextWithRequest:(id)arg1 client:(id)arg2;	// IMP=0x0010000000094d9e
- (id)authorizationContextHelperWithContext:(id)arg1 client:(id)arg2;	// IMP=0x0010000000094cd1
- (void)_completeAuthorizationWithServerResponse:(id)arg1 userResponse:(id)arg2 client:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000946ac
- (void)_performSRPAuthorizationForUserResponse:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000943f0
- (void)_safePerformSRPWithUserResponse:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000094232
- (void)_requestUserAuthorizationForContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000093ec6
- (void)_fetchCredentialsForAssociatedDomains:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000093d75
- (void)_fetchSafariCredentialsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000093bee
- (void)_setupLoginChoicesForPresentationContext:(id)arg1;	// IMP=0x00100000000936e1
- (long long)_credentialStateForRequestContext:(id)arg1;	// IMP=0x001000000009366b
- (void)_prepareRequestContext:(id)arg1 forCredentialState:(long long)arg2;	// IMP=0x001000000009336d
- (_Bool)_isPCSAccessForContext:(id)arg1;	// IMP=0x001000000009327a
- (_Bool)_shouldAllowPCSKeyAccessForContext:(id)arg1;	// IMP=0x001000000009324c
- (void)_getPresentationContextForRequestContext:(id)arg1 client:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000929f6
- (void)storeAuthorization:(id)arg1 forProxiedRequest:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000009273d
- (_Bool)_shouldStartSatoriVerificationForRequestContext:(id)arg1;	// IMP=0x00100000000926cd
- (void)_initiateRapportAuthorizationWithRequestContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000092516
- (void)_initiateAuthorizationWithRequestContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000009239e
- (_Bool)_verifyEntitlementsForRequest:(id)arg1;	// IMP=0x0010000000091ff8
- (void)_performSilentRequest:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000091d0e
- (void)_performRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000091c13
- (void)_determineUIAndPerformRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000091b43
- (_Bool)_shouldEarlyReturnRequest:(id)arg1 forCredentialState:(long long)arg2;	// IMP=0x0010000000091ac0
- (void)_createAndPerformRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000914da
- (id)_clientForContext:(id)arg1;	// IMP=0x00100000000913d0
- (void)getPresentationContextForRequestContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000910e0
- (void)establishConnectionWithStateBroadcastHandlerEndpoint:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000090e6b
- (void)establishConnectionWithNotificationHandlerEndpoint:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000090ba7
- (void)continueFetchingIconForRequestContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000090a92
- (void)fetchPrimaryApplicationInformationForWebServiceWithInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000908d0
- (void)fetchAppleIDAuthorizeHTMLResponseTemplateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000904f8
- (void)revokeUpgradeWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000009023f
- (void)fetchAppleOwnedDomainSetWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000901ad
- (void)fetchNativeTakeoverURLSetWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000009006b
- (void)fetchAppleIDAuthorizationURLSetWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000008ffd9
- (void)startDiscoveryWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000008fe5f
- (void)getCredentialStateForClientID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008fdcc
- (void)getCredentialStateForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008fbc6
- (void)performAuthorization:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008f0f5
- (void)dealloc;	// IMP=0x001000000008f089
- (id)initWithClient:(id)arg1;	// IMP=0x001000000008ef00
- (id)init;	// IMP=0x001000000008eed5

@end

