//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AKCommandMessage
{
}

- (id)description;	// IMP=0x002000000002f960
// Error: Property attributes should begin with the type ('T') attribute, property name: argument
// Property attributes: (null)

@property(nonatomic) unsigned long long command;
- (id)init;	// IMP=0x001000000002f821

@end

