//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSDictionary, NSString;
@protocol OS_dispatch_queue;

@interface AKURLBagService : NSObject
{
    NSObject<OS_dispatch_queue> *_bagFetchQueue;	// 8 = 0x8
    NSDictionary *_lastUpdated;	// 16 = 0x10
    NSDictionary *_cachedBags;	// 24 = 0x18
}

+ (MISSING_TYPE *)sharedBagService;	// IMP=0x002000000008d751
- (void).cxx_destruct;	// IMP=0x002000000008ec6c
- (id)_updateCacheWithData:(id)arg1 forAltDSID:(id)arg2;	// IMP=0x001000000008e8d4
- (void)forceURLBagUpdateForAltDSID:(id)arg1 urlSwitchData:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008e80d
- (void)_updateURLBagIfNecessaryFromCache:(_Bool)arg1 altDSID:(id)arg2 urlSwitchData:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000008e12d
- (id)_updateURLBagIfNecessaryFromCache:(_Bool)arg1 altDSID:(id)arg2 error:(id *)arg3;	// IMP=0x001000000008ded5
- (id)_cachedURLBagForAltDSID:(id)arg1;	// IMP=0x001000000008dce1
- (id)urlBagFromCache:(_Bool)arg1 altDSID:(id)arg2 error:(id *)arg3;	// IMP=0x001000000008dc04
- (id)urlBagForAltDSID:(id)arg1 error:(id *)arg2;	// IMP=0x001000000008dbea
- (void)fetchURLBagForAltDSID:(id)arg1 fromCache:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008daf5
- (void)fetchURLBagForAltDSID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008da06
- (void)clearSerializedMemoryCache;	// IMP=0x001000000008d918
- (void)clearSessionCache;	// IMP=0x001000000008d893
- (void)clearCache;	// IMP=0x001000000008d865
- (id)init;	// IMP=0x001000000008d7f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

