//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@interface TVUPSGroupRecommendationsAddUserViewController : UIViewController
{
}

+ (id)_remoteViewControllerInterface;	// IMP=0x00400000000027a0
+ (id)_exportedInterface;	// IMP=0x0010000000002640
- (void)viewServiceEndPresentationWithOptions:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00400000000024c0
- (void)viewServiceBeginPresentationWithOptions:(id)arg1;	// IMP=0x0010000000002090
- (void)_dismiss;	// IMP=0x0010000000002030

@end

