//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBRequest.h>

@class NSData;

@interface _ADPBLocationSetPeerLocationRequest : PBRequest
{
    NSData *_codedLocation;	// 8 = 0x8
}

+ (unsigned short)_ADPBLocationRequestType;	// IMP=0x0020000000257527
- (void).cxx_destruct;	// IMP=0x00200000001216b5
@property(retain, nonatomic) NSData *codedLocation; // @synthesize codedLocation=_codedLocation;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000012166c
- (unsigned long long)hash;	// IMP=0x001000000012164f
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001215bf
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000121547
- (void)copyTo:(id)arg1;	// IMP=0x001000000012151d
- (void)writeTo:(id)arg1;	// IMP=0x00100000001214f9
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000001213b0
- (id)dictionaryRepresentation;	// IMP=0x0010000000121354
- (id)description;	// IMP=0x00100000001212a5
@property(readonly, nonatomic) _Bool hasCodedLocation;
- (void)_ad_performForPeerLocationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000010d6cf
- (void)ad_setLocation:(id)arg1;	// IMP=0x00100000001ddeac
- (id)ad_location;	// IMP=0x00100000001dddfa

@end

