//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADAnalyticsEventRecordBuilder, NSString, SiriCoreSQLiteDatabase;
@protocol OS_dispatch_queue;

@interface ADAnalyticsStore : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    SiriCoreSQLiteDatabase *_database;	// 16 = 0x10
    ADAnalyticsEventRecordBuilder *_eventRecordBuilder;	// 24 = 0x18
    NSString *_path;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000012848c
@property(readonly, copy, nonatomic) NSString *path; // @synthesize path=_path;
- (_Bool)_updateRecordsWithSpeechId:(id)arg1 toUpdatedSpeechId:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000128152
- (void)_countQueuedEventRecordsWithCriteria:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000128035
- (void)countQueuedEventRecordsForDeliveryStream:(unsigned long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000127f95
- (void)countQueuedEventRecordsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000127f08
- (id)_fetchEventRecordsCreatedAfterDate:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000127b3c
- (id)_fetchEventRecords:(unsigned long long)arg1 afterTimestamp:(unsigned long long)arg2 eventStreamUID:(id)arg3 streamSpeechId:(id)arg4 deliveryStream:(unsigned long long)arg5 error:(id *)arg6;	// IMP=0x001000000012762a
- (id)_fetchEventStreamUIDsWithError:(id *)arg1;	// IMP=0x0010000000127117
- (_Bool)_purgeDeletedEventRecordsBeforeOrEqualToDate:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000126e56
- (_Bool)_deleteEventRecordsWithRecordIDs:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001269e3
- (_Bool)_deleteEventRecordsFromStartTime:(unsigned long long)arg1 toEndTime:(unsigned long long)arg2 eventStreamUID:(id)arg3 error:(id *)arg4;	// IMP=0x0010000000126582
- (_Bool)_deleteEventRecordsBeforeOrEqualToTimestamp:(unsigned long long)arg1 deliveryStream:(unsigned long long)arg2 eventStreamUID:(id)arg3 streamSpeechId:(id)arg4 error:(id *)arg5;	// IMP=0x001000000012614d
- (_Bool)_insertEventRecords:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000125ae5
- (id)_preparedDatabaseWithError:(id *)arg1;	// IMP=0x0010000000123d17
- (_Bool)_resetForReason:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000123930
- (void)updateRecordsWithSpeechId:(id)arg1 toUpdatedSpeechId:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001237b5
- (void)checkpointWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000012366d
- (void)resetWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000123553
- (void)purgeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000123439
- (void)fetchEventRecordsCreatedAfterDate:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000123382
- (void)purgeDeletedEventRecordsBeforeOrEqualToDate:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000123235
- (void)deleteEventRecordsFromStartTime:(unsigned long long)arg1 toEndTime:(unsigned long long)arg2 eventStreamUID:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000123165
- (void)deleteEventRecordsWithRecordIDs:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000122ff0
- (void)deleteEventRecordsBeforeOrEqualToTimestamp:(unsigned long long)arg1 deliveryStream:(unsigned long long)arg2 eventStreamUID:(id)arg3 streamSpeechId:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000122ef5
- (void)fetchEventRecords:(unsigned long long)arg1 eventStreamUID:(id)arg2 streamSpeechId:(id)arg3 deliveryStream:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000122ecf
- (void)fetchEventRecords:(unsigned long long)arg1 afterTimestamp:(unsigned long long)arg2 eventStreamUID:(id)arg3 streamSpeechId:(id)arg4 deliveryStream:(unsigned long long)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x0010000000122dcc
- (void)fetchEventStreamUIDsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000122d3f
- (void)insertEventRecords:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000122c54
- (id)initWithPath:(id)arg1;	// IMP=0x0010000000122b54
- (void)dealloc;	// IMP=0x0010000000122b10

@end

