//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface ADIntentsUserActivityManager : NSObject
{
    NSMutableDictionary *_userActivitiesStore;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000001e718d
- (id)description;	// IMP=0x00100000001e70f1
- (void)reset;	// IMP=0x00100000001e70db
- (void)setUserActivity:(id)arg1 forID:(id)arg2;	// IMP=0x00100000001e7051
- (id)userActivityForID:(id)arg1;	// IMP=0x00100000001e7005
- (id)init;	// IMP=0x00100000001e6f9a

@end

