//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface ADServiceCommandType : NSObject
{
    NSString *_domainName;	// 8 = 0x8
    NSString *;	// 16 = 0x10
}

+ (id)domainObjectCommitTypeForDomainNamed:(id)arg1;	// IMP=0x004000000011ddbb
+ (id)domainObjectCancelTypeForDomainNamed:(id)arg1;	// IMP=0x001000000011dd9f
+ (id)domainObjectDeleteTypeForDomainNamed:(id)arg1;	// IMP=0x001000000011dd83
+ (id)domainObjectUpdateTypeForDomainNamed:(id)arg1;	// IMP=0x001000000011dd67
+ (id)domainObjectRetrieveTypeForDomainNamed:(id)arg1;	// IMP=0x001000000011dd4b
+ (id)domainObjectCreateTypeForDomainNamed:(id)arg1;	// IMP=0x001000000011dd2f
+ (id)_serviceCommandTypeWithDomainName:(id)arg1 className:(id)arg2;	// IMP=0x001000000011dcc1
- (void).cxx_destruct;	// IMP=0x002000000011dc99
- (unsigned long long)hash;	// IMP=0x001000000011dc5a
- (_Bool)isEqualToServiceCommandType:(id)arg1;	// IMP=0x001000000011db9b
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000011db3e
- (id)description;	// IMP=0x001000000011dab6
- (id)qualifiedCommandName;	// IMP=0x001000000011da4d
- (id)className;	// IMP=0x001000000011da3f
- (id)domainName;	// IMP=0x001000000011da31
- (id)initWithDomainName:(id)arg1 className:(id)arg2;	// IMP=0x001000000011d978

@end

