//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ADAuthenticator, ADRetryManager, AFInstanceContext, MISSING_TYPE, NSData, NSDate, NSError, NSMutableArray, NSObject, NSString, NSURL;
@protocol OS_dispatch_group, OS_dispatch_queue, SiriCoreSiriConnection;

@interface ADSessionRemoteServer
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    id <SiriCoreSiriConnection> _serverConnection;	// 16 = 0x10
    NSURL *_currentConnectionURL;	// 24 = 0x18
    struct __CFDictionary *_commandMap;	// 32 = 0x20
    ADAuthenticator *_authenticator;	// 40 = 0x28
    NSDate *_cachedValidationDataExpiration;	// 48 = 0x30
    NSData *_cachedValidationData;	// 56 = 0x38
    _Bool _usingCachedCertificateData;	// 64 = 0x40
    _Bool _usingCachedValidationData;	// 65 = 0x41
    _Bool _forceValidationRefresh;	// 66 = 0x42
    _Bool _checkForWiFiTransitionOnRequestEnd;	// 67 = 0x43
    _Bool _prefersWWAN;	// 68 = 0x44
    _Bool _skipPeer;	// 69 = 0x45
    NSError *_skipPeerError;	// 72 = 0x48
    _Bool _forceReconnect;	// 80 = 0x50
    _Bool _hasCachedAuthDisabled;	// 81 = 0x51
    _Bool _cachedAuthDisabled;	// 82 = 0x52
    NSString *_peerType;	// 88 = 0x58
    NSString *_peerVersion;	// 96 = 0x60
    NSString *_productTypePrefix;	// 104 = 0x68
    _Bool _siriConnectionUsesPeerManagedSync;	// 112 = 0x70
    _Bool _useWiFiHint;	// 113 = 0x71
    _Bool _hasActiveRequest;	// 114 = 0x72
    double _aceHeaderTimeout;	// 120 = 0x78
    void *_dormancySuspendAssertion;	// 128 = 0x80
    _Bool _isAttemptingRetry;	// 136 = 0x88
    _Bool _waitingForDelayedRetry;	// 137 = 0x89
    double _requestStartTime;	// 144 = 0x90
    double _requestEndTime;	// 152 = 0x98
    double _lastRetryTimeOnQueue;	// 160 = 0xa0
    double _loadRetryStartTime;	// 168 = 0xa8
    NSString *_sessionInitCommandId;	// 176 = 0xb0
    NSString *_createSessionInfoRequestId;	// 184 = 0xb8
    ADRetryManager *_retryManager;	// 192 = 0xc0
    unsigned long long _badCachedCertRetryCounter;	// 200 = 0xc8
    unsigned long long _certificateFailureCounter;	// 208 = 0xd0
    NSMutableArray *_metricsCache;	// 216 = 0xd8
    NSString *_pairedWatchUniqueId;	// 224 = 0xe0
    NSObject<OS_dispatch_group> *_metricsGroup;	// 232 = 0xe8
    _Bool _isRequestRetry;	// 240 = 0xf0
    AFInstanceContext *_instanceContext;	// 248 = 0xf8
}

+ (void)_getReportSymptomsBasedNetworkQualityMetrics:(CDUnknownBlockType)arg1;	// IMP=0x0020000000269679
- (void).cxx_destruct;	// IMP=0x0020000000267080
- (id)currentConnectionPreCachedMetrics;	// IMP=0x0010000000266fab
- (void)getConnectionMetrics:(CDUnknownBlockType)arg1;	// IMP=0x0010000000266dbc
- (void)assistantDataManagerDictationHIPAAMDMStatusDidChange;	// IMP=0x0010000000266d6a
- (void)_generateAWDMetricsForConnectionError:(id)arg1;	// IMP=0x0010000000266d64
- (MISSING_TYPE *)_generateAWDMetricsForOpenedConnection:type: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000266d5e
- (void)_generateAWDMetricsForWillStartConnection:(id)arg1;	// IMP=0x0010000000266d58
- (void)_generateAWDTransportMetrics:(id)arg1 moreComing:(_Bool)arg2 transportRecord:(id)arg3;	// IMP=0x0010000000266d52
- (id)_generateAnalyticsContextWithError:(id)arg1;	// IMP=0x00100000002666d3
- (void)_probeSessionIfIdle;	// IMP=0x00100000002665d2
- (void)_createAssistant;	// IMP=0x001000000026620e
- (void)_adjustAceHeaderTimeout:(_Bool)arg1;	// IMP=0x00100000002661c0
- (void)_resetConnectionPolicyBlacklisting;	// IMP=0x0010000000266172
- (void)_releaseDormancySuspension;	// IMP=0x0010000000266118
- (void)_forceFastDormancy;	// IMP=0x00100000002660db
- (void)networkManagerNetworkUnreachable:(id)arg1;	// IMP=0x00100000002660d5
- (void)_recheckForWiFiTransition;	// IMP=0x0010000000265f18
- (void)networkManagerLostNonWWANConnectivity:(id)arg1;	// IMP=0x0010000000265ec6
- (void)networkManagerNonWWANDidBecomeAvailable:(id)arg1;	// IMP=0x0010000000265e74
- (void)_multiUsersDidChange:(id)arg1;	// IMP=0x0010000000265e22
- (void)_homeContextDidChange:(id)arg1;	// IMP=0x0010000000265d8e
- (void)_homeInfoDidChange:(id)arg1;	// IMP=0x0010000000265d3c
- (void)barrier:(CDUnknownBlockType)arg1;	// IMP=0x0010000000265c43
- (void)_retrieveAndSendHomeContext;	// IMP=0x0010000000265bbe
- (void)_sendHomeContext:(id)arg1;	// IMP=0x00100000002659f3
- (void)_sendUserProfiles;	// IMP=0x0010000000265974
- (void)_sendMultiUserInfo;	// IMP=0x00100000002658c8
- (void)sendRemoteGizmoDeviceToServer:(id)arg1;	// IMP=0x0010000000265818
- (void)_sendSetRemoteDevicesWithAccount:(id)arg1;	// IMP=0x0010000000265804
- (void)_sendSetRemoteDevicesWithAccount:(id)arg1 multiUserInfo:(id)arg2;	// IMP=0x001000000026493d
- (void)_sendLoadAssistantWithAccount:(id)arg1 validationData:(id)arg2;	// IMP=0x0010000000264181
- (void)_triggerABCForEmptyLocale;	// IMP=0x0010000000263ff0
- (void)_sendCreateSessionInfoRequestWithData:(id)arg1;	// IMP=0x0010000000263e07
- (void)_sendGetSessionCertificateData;	// IMP=0x0010000000263c9f
- (void)_sendServerCommands:(id)arg1;	// IMP=0x0010000000263994
- (void)_sendServerCommand:(id)arg1;	// IMP=0x0010000000263798
- (void)_sendServerCommandLogErrorForCommand:(id)arg1 withContext:(id)arg2;	// IMP=0x00100000002636b4
- (void)doSendPostProcessing:(id)arg1;	// IMP=0x00100000002636ae
- (void)doSendPreProcessing:(id)arg1;	// IMP=0x00100000002635f0
- (void)_saCommandFailed:(id)arg1;	// IMP=0x0010000000263359
- (void)_assistantFailedForReason:(id)arg1 error:(id)arg2;	// IMP=0x0010000000262fc3
- (void)_saSetConnectionHeader:(id)arg1;	// IMP=0x0010000000262bb3
- (void)_saAssistantNotReady:(id)arg1;	// IMP=0x001000000026298e
- (void)_saAssistantNotFound:(id)arg1;	// IMP=0x0010000000262804
- (void)_saAssistantDestroyed:(id)arg1;	// IMP=0x0010000000262617
- (void)_saAssistantLoaded:(id)arg1;	// IMP=0x001000000026224b
- (void)_saAssistantCreated:(id)arg1;	// IMP=0x00100000002621c6
- (void)_saCreateSessionInfoResponse:(id)arg1;	// IMP=0x0010000000261edc
- (void)_saGetSessionCertificateResponse:(id)arg1;	// IMP=0x0010000000261d85
- (void)_saSessionValidationFailed:(id)arg1;	// IMP=0x0010000000261893
- (void)_handleAceObject:(id)arg1;	// IMP=0x0010000000261695
- (void)delegateDidHandleCommand:(id)arg1 didRecognizeSpeech:(_Bool)arg2;	// IMP=0x0010000000261627
- (void)_eagerAuthDidComplete;	// IMP=0x00100000002614b7
- (void)_connectionOpened;	// IMP=0x001000000026139f
- (void)_startSession;	// IMP=0x001000000026113e
- (void)refreshValidationData;	// IMP=0x0010000000260f54
- (void)_continueAuthentication;	// IMP=0x00100000002609a7
- (void)_continueAuthWithCertificateData:(id)arg1;	// IMP=0x00100000002608d8
- (void)_continueSessionInitWithValidationData:(id)arg1;	// IMP=0x0010000000260719
- (void)_authenticationFailed;	// IMP=0x001000000026060b
- (id)connection;	// IMP=0x00100000002605f6
- (_Bool)sessionIsAttemptingTryOrRetry;	// IMP=0x00100000002605af
- (void)_retryForFailedConnection:(id)arg1 withType:(id)arg2 onError:(id)arg3;	// IMP=0x0010000000260121
- (void)_reallyRetryPreferringWWAN:(_Bool)arg1 skipPeer:(_Bool)arg2 skipPeerError:(id)arg3 useWiFiHint:(_Bool)arg4 causedByError:(id)arg5 forceReconnect:(_Bool)arg6 useSecondary:(_Bool)arg7;	// IMP=0x001000000025f789
- (void)_retryWithParameters:(_Bool)arg1 skipPeer:(_Bool)arg2 skipPeerError:(id)arg3 causedByError:(id)arg4 useSecondary:(_Bool)arg5;	// IMP=0x001000000025f75e
- (id)_authDataToSign;	// IMP=0x001000000025f648
- (_Bool)_persistValidationData:(id)arg1 withExpiration:(id)arg2;	// IMP=0x001000000025f4ab
- (void)_setCachedValidationData:(id)arg1 withDuration:(double)arg2;	// IMP=0x001000000025f324
- (id)_cachedValidationData;	// IMP=0x001000000025f08e
- (void)_setCachedServerCertificate:(id)arg1;	// IMP=0x001000000025ef68
- (id)_cachedServerCertificate;	// IMP=0x001000000025ee13
- (_Bool)_versionForCachedValidationDataMatchesCurrentVersion;	// IMP=0x001000000025ed67
- (id)_authenticator;	// IMP=0x001000000025eca8
- (_Bool)_authenticationDisabled;	// IMP=0x001000000025ec46
- (void)_informDelegateOfError:(id)arg1;	// IMP=0x001000000025e912
- (void)endRetryableRequestForCommandAceId:(id)arg1 refId:(id)arg2;	// IMP=0x001000000025e8f5
- (void)resetRetryManager;	// IMP=0x001000000025e839
- (void)startRetry;	// IMP=0x001000000025e57d
- (_Bool)_connectionErrorIsTimeout:(id)arg1;	// IMP=0x001000000025e493
- (_Bool)_connectionErrorSuggestsConnectionPolicyReset:(id)arg1;	// IMP=0x001000000025e3fd
- (_Bool)_connectionErrorIsRedirect:(id)arg1;	// IMP=0x001000000025e308
- (void)_updateConnectionPolicyFailureCount:(id)arg1;	// IMP=0x001000000025df3a
- (_Bool)_shouldRetry;	// IMP=0x001000000025de7e
- (void)siriConnection:(id)arg1 didEncounterIntermediateError:(id)arg2;	// IMP=0x001000000025de62
- (void)_siriConnection:(id)arg1 didEncounterError:(id)arg2 analysisInfo:(id)arg3;	// IMP=0x001000000025d1ee
- (void)siriConnection:(id)arg1 didEncounterError:(id)arg2 analysisInfo:(id)arg3;	// IMP=0x001000000025d103
- (void)siriConnectionDidClose:(id)arg1;	// IMP=0x001000000025d06f
- (void)siriConnection:(id)arg1 didReceiveAceObject:(id)arg2;	// IMP=0x001000000025cfb1
- (void)siriConnection:(id)arg1 didOpenWithConnectionType:(id)arg2 routeId:(id)arg3 delay:(double)arg4 method:(id)arg5;	// IMP=0x001000000025cc96
- (void)siriConnection:(id)arg1 willStartWithConnectionType:(id)arg2;	// IMP=0x001000000025cb79
- (void)_cancelSynchronously:(_Bool)arg1;	// IMP=0x001000000025cac7
- (void)_startConnectionPreferringWWAN:(_Bool)arg1 skipPeer:(_Bool)arg2 skipPeerError:(id)arg3 useWiFiHint:(_Bool)arg4 forceReconnect:(_Bool)arg5;	// IMP=0x001000000025bf1c
- (void)setHasActiveRequest:(_Bool)arg1;	// IMP=0x001000000025bc41
- (id)_networkManager;	// IMP=0x001000000025bc28
- (_Bool)_connectionIsWWAN;	// IMP=0x001000000025bbe4
- (void)_resetServerConnectionSynchronously:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000025b907
- (void)_resetServerConnection;	// IMP=0x001000000025b8f1
- (id)_serverConnection;	// IMP=0x001000000025b50f
- (void)_startConnection;	// IMP=0x001000000025b42a
- (id)_connectionURL;	// IMP=0x001000000025b274
- (void)beginRetryableRequest:(id)arg1;	// IMP=0x001000000025b20b
- (void)retryNakedCommandsIfNeeded;	// IMP=0x001000000025b0e5
- (id)_retryManager;	// IMP=0x001000000025b0a4
- (void)setCoreSiriConnection:(id)arg1;	// IMP=0x001000000025b010
- (_Bool)supportsSync;	// IMP=0x001000000025b008
- (void)dealloc;	// IMP=0x001000000025ae7b
- (id)initOnQueue:(id)arg1 withAccount:(id)arg2 languageCode:(id)arg3 connectionMode:(id)arg4 sharedUserIdentifier:(id)arg5 loggingSharedUserIdentifier:(id)arg6 instanceContext:(id)arg7;	// IMP=0x001000000025ab7b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

