//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SASUpdateAudioInfo.h>

@interface SASUpdateAudioInfo (ADSAExtensions)
- (id)ad_deferredMetricsContext;	// IMP=0x00100000002f5c4e
- (void)ad_updateWithRecordingInfo:(id)arg1 speechRequestOptions:(id)arg2 clientConfiguration:(id)arg3;	// IMP=0x00100000002f5067
- (_Bool)ad_isDifferentFromStartSpeech:(id)arg1;	// IMP=0x00100000002f4e63
@end

