//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class AVCMoments, AVCMomentsRequest, MISSING_TYPE, NSError, NSURL;

@protocol AVCMomentsDelegate <NSObject>
- (void)moments:(AVCMoments *)arg1 didStartProcessingRequest:(AVCMomentsRequest *)arg2 error:(NSError *)arg3;
- (void)moments:(AVCMoments *)arg1 didFinishRequest:(AVCMomentsRequest *)arg2 error:(NSError *)arg3;
- (void)moments:(AVCMoments *)arg1 capabilitiesDidChange:(unsigned int)arg2;

@optional
- (MISSING_TYPE *)momentsServerDidDisconnect: /* Error: Ran out of types for this method. */;
- (void)moments:(AVCMoments *)arg1 didEndProcessingRequest:(AVCMomentsRequest *)arg2 url:(NSURL *)arg3 error:(NSError *)arg4;
- (void)moments:(AVCMoments *)arg1 didEndProcessingRequest:(AVCMomentsRequest *)arg2 stillImageURL:(NSURL *)arg3 movieURL:(NSURL *)arg4 error:(NSError *)arg5;
@end

