//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSUUID, TUHandle;

@interface CSDGroupIDSPendingChat : NSObject
{
    MISSING_TYPE *uuid;	// 1651466079 = 0x626f5f5f
    MISSING_TYPE *handle;	// 1936941420 = 0x7373616c
}

- (void).cxx_destruct;	// IMP=0x0040000000296b78
- (id)init;	// IMP=0x0010000000296b38
- (id)initWithUUID:(id)arg1 handle:(id)arg2;	// IMP=0x0010000000296ab6
@property(nonatomic, readonly) TUHandle *handle; // @synthesize handle;
@property(nonatomic, readonly) NSUUID *uuid;

@end

