//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CSDMomentsControllerLocalCapabilities : NSObject
{
}

- (id)init;	// IMP=0x0040000000267411
- (_Bool)isRegionBlocked;	// IMP=0x0010000000267389
- (_Bool)isEnabled;	// IMP=0x0010000000267355

// Remaining properties
@property(nonatomic, readonly) _Bool enabled;
@property(nonatomic, readonly) _Bool regionBlocked;

@end

