//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface CSDOwnNumberCallFilter
{
    MISSING_TYPE *idsCTAdapter;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00400000002c15d1
- (id)initWithQueue:(id)arg1;	// IMP=0x00100000002c1581
- (_Bool)shouldFilterIncomingCall:(id)arg1 from:(id)arg2;	// IMP=0x00100000002c1464

@end

