//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC4Siri37SRCarPlayVisualResponseViewController : UIViewController
{
    MISSING_TYPE *maxNonScrollableListSize;	// 8 = 0x8
    MISSING_TYPE *aceSnippet;	// 16 = 0x10
    MISSING_TYPE *pluginSnippet;	// 24 = 0x18
    MISSING_TYPE *requestOptions;	// 32 = 0x20
    MISSING_TYPE *delegate;	// 40 = 0x28
    MISSING_TYPE *snippet;	// 56 = 0x38
    MISSING_TYPE *proceedToNextCommandAtSpeechSynthesisEnd;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0040000000087e10
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000087db0
- (void)viewWillLayoutSubviews;	// IMP=0x0010000000087d80
- (void)viewDidLoad;	// IMP=0x0010000000087a30
- (void)loadView;	// IMP=0x00100000000877b0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000087700

@end

