//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SiriUI/SiriUIAceObjectViewController.h>

@class SAUIListItem, SRUserUtteranceView;

@interface SRDisambiguationSelectionController : SiriUIAceObjectViewController
{
}

- (long long)_pinAnimationType;	// IMP=0x0020000000005276
- (double)baselineOffsetFromBottom;	// IMP=0x0010000000005226
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x00100000000051c4
- (void)loadView;	// IMP=0x001000000000505e

// Remaining properties
@property(retain, nonatomic) SAUIListItem *aceObject; // @dynamic aceObject;
@property(retain, nonatomic) SRUserUtteranceView *view; // @dynamic view;

@end

