//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AFQueue, AFVoiceInfo, MISSING_TYPE, NSMutableArray, NSMutableDictionary, NSString, SiriTTSDaemonSession, VSSpeechSynthesizer;
@protocol OS_dispatch_group, OS_dispatch_queue, SRTTSManagerClientStateManagerDelegate, SRTTSManagerDelegate;

@interface SRTTSManager : NSObject
{
    VSSpeechSynthesizer *_synthesizer;	// 8 = 0x8
    AFVoiceInfo *_outputVoice;	// 16 = 0x10
    NSMutableDictionary *_availableVoicesForLanguage;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_processingTasksQueue;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_pendingTasksQueue;	// 40 = 0x28
    NSObject<OS_dispatch_group> *_pendingTasksGroup;	// 48 = 0x30
    unsigned int _audioSessionID;	// 56 = 0x38
    id <SRTTSManagerDelegate> _delegate;	// 64 = 0x40
    id <SRTTSManagerClientStateManagerDelegate> _clientStateManagerDelegate;	// 72 = 0x48
    AFQueue *_taskQueue;	// 80 = 0x50
    NSMutableArray *_activeTasks;	// 88 = 0x58
    NSMutableDictionary *_delayedTasks;	// 96 = 0x60
    SiriTTSDaemonSession *_ttsSession;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x0020000000063ac7
@property(retain, nonatomic) SiriTTSDaemonSession *ttsSession; // @synthesize ttsSession=_ttsSession;
@property(readonly, nonatomic, getter=_delayedTasks) NSMutableDictionary *delayedTasks; // @synthesize delayedTasks=_delayedTasks;
@property(readonly, nonatomic, getter=_activeTasks) NSMutableArray *activeTasks; // @synthesize activeTasks=_activeTasks;
@property(readonly, nonatomic, getter=_taskQueue) AFQueue *taskQueue; // @synthesize taskQueue=_taskQueue;
@property(nonatomic) unsigned int audioSessionID; // @synthesize audioSessionID=_audioSessionID;
@property(nonatomic) __weak id <SRTTSManagerClientStateManagerDelegate> clientStateManagerDelegate; // @synthesize clientStateManagerDelegate=_clientStateManagerDelegate;
@property(nonatomic) __weak id <SRTTSManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_setSynthesizer:(id)arg1;	// IMP=0x0010000000063a27
- (MISSING_TYPE *)_processProvisionalTasks;	// IMP=0x001000000006381b
- (id)_filterVoices:(id)arg1 gender:(id)arg2;	// IMP=0x0010000000063578
- (long long)_genderForString:(id)arg1;	// IMP=0x00100000000634e4
- (void)_findVoiceForLanguage:(id)arg1 gender:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000630ce
- (id)_activeTaskWithSpeechRequest:(id)arg1;	// IMP=0x0010000000062f11
- (id)_activeTaskWithPresynthesizedAudioRequest:(id)arg1;	// IMP=0x0010000000062d54
- (id)_activeTaskWithTTSRequest:(id)arg1;	// IMP=0x0010000000062b97
- (void)_processTaskQueue;	// IMP=0x00100000000622fd
- (void)_handleText:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000600b9
- (void)_handleAudioData:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000005f7c5
- (void)processDelayedItem:(id)arg1;	// IMP=0x001000000005f6cf
- (void)enqueueText:(id)arg1 identifier:(id)arg2 sessionId:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000005f671
- (void)_enqueueText:(id)arg1 audioData:(id)arg2 identifier:(id)arg3 sessionId:(id)arg4 language:(id)arg5 gender:(id)arg6 isPhonetic:(_Bool)arg7 provisionally:(_Bool)arg8 eligibleAfterDuration:(double)arg9 delayed:(_Bool)arg10 canUseServerTTS:(_Bool)arg11 preparationIdentifier:(id)arg12 shouldCache:(_Bool)arg13 completion:(CDUnknownBlockType)arg14 analyticsContext:(id)arg15 speakableContextInfo:(id)arg16;	// IMP=0x001000000005ef76
- (void)enqueuePhaticWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000005ee29
- (void)enqueueAudioData:(id)arg1 identifier:(id)arg2 sessionId:(id)arg3 provisionally:(_Bool)arg4 eligibleAfterDuration:(double)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x001000000005edc6
- (void)enqueueText:(id)arg1 identifier:(id)arg2 sessionId:(id)arg3 language:(id)arg4 gender:(id)arg5 isPhonetic:(_Bool)arg6 provisionally:(_Bool)arg7 eligibleAfterDuration:(double)arg8 delayed:(_Bool)arg9 canUseServerTTS:(_Bool)arg10 preparationIdentifier:(id)arg11 completion:(CDUnknownBlockType)arg12 analyticsContext:(id)arg13 speakableContextInfo:(id)arg14;	// IMP=0x001000000005ed31
- (void)setOutputVoice:(id)arg1;	// IMP=0x001000000005ec11
- (void)speechSynthesizer:(id)arg1 didFinishSpeakingRequest:(id)arg2 withInstrumentMetrics:(id)arg3;	// IMP=0x001000000005e49f
- (void)speakTask:(id)arg1 didGenerateMetrics:(id)arg2;	// IMP=0x001000000005dcfc
- (void)didFinishSpeakTask:(id)arg1 legacyRequest:(id)arg2 withError:(id)arg3;	// IMP=0x001000000005d1cc
- (void)speechSynthesizer:(id)arg1 didFinishSpeakingRequest:(id)arg2 successfully:(_Bool)arg3 phonemesSpoken:(id)arg4 withError:(id)arg5;	// IMP=0x001000000005d1b4
- (void)didStartSpeakTask:(id)arg1 legacyRequest:(id)arg2;	// IMP=0x001000000005cec6
- (void)speechSynthesizer:(id)arg1 didStartSpeakingRequest:(id)arg2;	// IMP=0x001000000005ceb2
- (void)didFinishAudioTask:(id)arg1 legacyRequest:(id)arg2 withError:(id)arg3;	// IMP=0x001000000005c828
- (void)speechSynthesizer:(id)arg1 didFinishPresynthesizedAudioRequest:(id)arg2 withInstrumentMetrics:(id)arg3 error:(id)arg4;	// IMP=0x001000000005c811
- (void)speechSynthesizer:(id)arg1 didStopPresynthesizedAudioRequest:(id)arg2 atEnd:(_Bool)arg3 error:(id)arg4;	// IMP=0x001000000005c70a
- (void)didStartAudioTask:(id)arg1 legacyRequest:(id)arg2;	// IMP=0x001000000005c4e3
- (void)speechSynthesizer:(id)arg1 didStartPresynthesizedAudioRequest:(id)arg2;	// IMP=0x001000000005c4cf
- (void)taskEligibilityDidChange:(id)arg1;	// IMP=0x001000000005c40f
- (void)queue:(id)arg1 didEnqueueObjects:(id)arg2;	// IMP=0x001000000005c3fd
- (void)invalidate;	// IMP=0x001000000005c347
- (void)invalidateOnMainThread;	// IMP=0x001000000005c335
- (void)_cancelByCancellingActiveTasksOnly:(_Bool)arg1;	// IMP=0x001000000005be33
- (void)skipCurrentSynthesis;	// IMP=0x001000000005be1c
- (void)cancel;	// IMP=0x001000000005be08
- (void)_duckTTSVolumeTo:(float)arg1 rampTime:(double)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000005bc4b
- (void)duckTTSVolumeTo:(float)arg1 rampTime:(double)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000005baee
- (_Bool)_isSynthesisQueueEmpty;	// IMP=0x001000000005ba5b
- (void)isSynthesisQueueEmpty:(CDUnknownBlockType)arg1;	// IMP=0x001000000005b92a
- (_Bool)isSpeaking;	// IMP=0x001000000005b7ab
- (void)prewarmIfNeeded;	// IMP=0x001000000005b4cf
- (id)_synthesizer;	// IMP=0x001000000005b4b3
- (id)init;	// IMP=0x001000000005b2b7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

