//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface SRWindowSceneDelegate : NSObject
{
}

- (void)sceneDidEnterBackground:(id)arg1;	// IMP=0x002000000004f588
- (void)sceneWillEnterForeground:(id)arg1;	// IMP=0x001000000004f46e
- (void)sceneWillResignActive:(id)arg1;	// IMP=0x001000000004f361
- (void)sceneDidBecomeActive:(id)arg1;	// IMP=0x001000000004f254
- (void)sceneDidDisconnect:(id)arg1;	// IMP=0x001000000004f0f9
- (void)scene:(id)arg1 willConnectToSession:(id)arg2 options:(id)arg3;	// IMP=0x001000000004eea1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
// Error: Property attributes should begin with the type ('T') attribute, property name: window
// Property attributes: (null)


@end

