//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface PQLStatement : NSObject
{
    struct sqlite3_stmt *_stmt;	// 8 = 0x8
    PQLStatement *_next;	// 16 = 0x10
    NSMutableArray *_aliveBinds;	// 24 = 0x18
    CDUnknownBlockType _profilingHook;	// 32 = 0x20
    union {
        unsigned char inlined[8];
        unsigned char *ptr;
    } _specUnion;	// 40 = 0x28
    _Bool _inUse;	// 48 = 0x30
    _Bool _isTraced;	// 49 = 0x31
    short _specLength;	// 50 = 0x32
}

- (void).cxx_destruct;	// IMP=0x000000000000d851
- (void)unbindForDB:(id)arg1 returnedRows:(unsigned long long)arg2;	// IMP=0x000000000000d779
- (void)bindArguments:(struct __va_list_tag [1])arg1 db:(id)arg2;	// IMP=0x000000000000cf9f
- (id)description;	// IMP=0x000000000000cf3c
- (void)dealloc;	// IMP=0x000000000000ceee
- (void)invalidate;	// IMP=0x000000000000cec2
- (id)initWithFormat:(id)arg1 arguments:(struct __va_list_tag [1])arg2 db:(id)arg3 cache:(struct cache_s *)arg4;	// IMP=0x000000000000c8dc
- (id)initWithStatement:(id)arg1 forDB:(id)arg2;	// IMP=0x000000000000c7b9
- (_Bool)_prepare:(const char *)arg1 withDB:(id)arg2;	// IMP=0x000000000000c62c
- (id)translate:(id)arg1 hasInjections:(_Bool *)arg2 arguments:(struct __va_list_tag [1])arg3;	// IMP=0x000000000000bd05
- (void)keepBindAlive:(id)arg1;	// IMP=0x000000000000bc91
@property(readonly, nonatomic) _Bool isTraced;
- (void)bindFromArray:(id)arg1 db:(id)arg2;	// IMP=0x000000000000e538
- (id)initWithQueryBuilder:(CDUnknownBlockType)arg1 db:(id)arg2 cache:(struct cache_s *)arg3;	// IMP=0x000000000000e01b
- (id)translate:(id)arg1 withBuilder:(id)arg2;	// IMP=0x000000000000dec4

@end

