//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, UIWindow;

@interface _TtC12PreviewShell26SimulatorMainSceneDelegate
{
    MISSING_TYPE *window;	// 24 = 0x18
    MISSING_TYPE *previewShellScene;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x004000000003b9d0
- (id)init;	// IMP=0x001000000003b990
@property(nonatomic, retain) UIWindow *window; // @synthesize window;

@end

