//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class NSIndexPath, NSString, PBAppSwitcherDataSource, PBAppSwitcherItem, PBAppSwitcherTitleView, TVSStateMachine, UIInterpolatingMotionEffect, UIPanGestureRecognizer, UITapGestureRecognizer, UIViewPropertyAnimator, _PBAppSwitcherCollectionView;
@protocol PBWorkspaceGeometry;

@interface PBAppSwitcherCollectionViewController : UIViewController
{
    _Bool _panningVertically;	// 8 = 0x8
    _Bool _panningHorizontally;	// 9 = 0x9
    _Bool _scrolling;	// 10 = 0xa
    _Bool _peekEffectEnabled;	// 11 = 0xb
    id <PBWorkspaceGeometry> _workspaceGeometry;	// 16 = 0x10
    PBAppSwitcherDataSource *_appSwitcherDataSource;	// 24 = 0x18
    TVSStateMachine *_stateMachine;	// 32 = 0x20
    NSIndexPath *_preferredIndexPath;	// 40 = 0x28
    _PBAppSwitcherCollectionView *_collectionView;	// 48 = 0x30
    PBAppSwitcherTitleView *_titleView;	// 56 = 0x38
    UIInterpolatingMotionEffect *_peekEffect;	// 64 = 0x40
    UIPanGestureRecognizer *_panRecognizer;	// 72 = 0x48
    UITapGestureRecognizer *_upRecognizer;	// 80 = 0x50
    PBAppSwitcherItem *_focusedItem;	// 88 = 0x58
    PBAppSwitcherItem *_pendingLaunchItem;	// 96 = 0x60
    PBAppSwitcherItem *_killedItem;	// 104 = 0x68
    CDUnknownBlockType _launchCompletionHandler;	// 112 = 0x70
    UIViewPropertyAnimator *_switcherAnimator;	// 120 = 0x78
    CDUnknownBlockType _presentationCompletion;	// 128 = 0x80
    CDUnknownBlockType _dismissalCompletion;	// 136 = 0x88
    struct CGPoint _initialDragLocation;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x002000000017024c
@property(copy, nonatomic) CDUnknownBlockType dismissalCompletion; // @synthesize dismissalCompletion=_dismissalCompletion;
@property(copy, nonatomic) CDUnknownBlockType presentationCompletion; // @synthesize presentationCompletion=_presentationCompletion;
@property(retain, nonatomic) UIViewPropertyAnimator *switcherAnimator; // @synthesize switcherAnimator=_switcherAnimator;
- (void);	// IMP=0x00100000001701ce
@property(copy, nonatomic) CDUnknownBlockType launchCompletionHandler; // @synthesize launchCompletionHandler=_launchCompletionHandler;
@property(retain, nonatomic) PBAppSwitcherItem *killedItem; // @synthesize killedItem=_killedItem;
@property(retain, nonatomic) PBAppSwitcherItem *pendingLaunchItem; // @synthesize pendingLaunchItem=_pendingLaunchItem;
@property(retain, nonatomic) PBAppSwitcherItem *focusedItem; // @synthesize focusedItem=_focusedItem;
@property(readonly, nonatomic) UITapGestureRecognizer *upRecognizer; // @synthesize upRecognizer=_upRecognizer;
@property(readonly, nonatomic) UIPanGestureRecognizer *panRecognizer; // @synthesize panRecognizer=_panRecognizer;
@property(readonly, nonatomic) UIInterpolatingMotionEffect *peekEffect; // @synthesize peekEffect=_peekEffect;
@property(nonatomic) _Bool peekEffectEnabled; // @synthesize peekEffectEnabled=_peekEffectEnabled;
@property(retain, nonatomic) PBAppSwitcherTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) _PBAppSwitcherCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSIndexPath *preferredIndexPath; // @synthesize preferredIndexPath=_preferredIndexPath;
@property(nonatomic, getter=isScrolling) _Bool scrolling; // @synthesize scrolling=_scrolling;
@property(nonatomic, getter=isPanningHorizontally) _Bool panningHorizontally; // @synthesize panningHorizontally=_panningHorizontally;
@property(nonatomic, getter=isPanningVertically) _Bool panningVertically; // @synthesize panningVertically=_panningVertically;
@property(nonatomic) struct CGPoint initialDragLocation; // @synthesize initialDragLocation=_initialDragLocation;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(readonly, nonatomic) PBAppSwitcherDataSource *appSwitcherDataSource; // @synthesize appSwitcherDataSource=_appSwitcherDataSource;
@property(readonly, nonatomic) id <PBWorkspaceGeometry> workspaceGeometry; // @synthesize workspaceGeometry=_workspaceGeometry;
- (void)presentationElementFocusCoordinator:(id)arg1 didUpdateToActiveLayoutLevel:(long long)arg2 fromLevel:(long long)arg3;	// IMP=0x001000000016ff15
- (struct CGPoint)_preferredContentOffsetForIndexPath:(id)arg1;	// IMP=0x001000000016fe23
- (void)_invalidateSceneViewForCell:(id)arg1;	// IMP=0x001000000016fdb3
- (void)_prepareToLaunchItemImmediately:(id)arg1;	// IMP=0x001000000016fb62
- (_Bool)_servicePendingUpdatesWithAnimation:(_Bool)arg1;	// IMP=0x001000000016f856
- (void)__applyPendingUpdatesToCollectionView;	// IMP=0x001000000016f289
- (void)_handleCollectionViewUpdatesWithAnimation:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000016f08c
- (void)_finishKillSwipeWithVelocity:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000016ecba
- (void)_cancelKillSwipeWithVelocity:(double)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000016e9e8
- (void)_updateKillSwipeWithOffset:(double)arg1;	// IMP=0x001000000016e92b
- (void)_setKillGestureRecognizersEnabled:(_Bool)arg1;	// IMP=0x001000000016e8e0
- (void)_launchItem:(id)arg1 shouldAnimateLayoutSwitch:(_Bool)arg2;	// IMP=0x001000000016e2ea
- (_Bool)_shouldScrollToItem:(id)arg1 scrollIfNeeded:(_Bool)arg2 forced:(_Bool)arg3;	// IMP=0x001000000016e12c
- (_Bool)_activateItem:(id)arg1;	// IMP=0x001000000016dfdb
- (void)_activatePendingLaunchItem;	// IMP=0x001000000016de0d
- (void)_showAppSwitcher;	// IMP=0x001000000016d789
- (void)_initializeStateMachine;	// IMP=0x001000000016ae6a
- (void)dataSource:(id)arg1 didReceiveLaunchRequestForItem:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000016ad75
- (void)dataSourceDidEnqueuePendingUpdates:(id)arg1 animated:(_Bool)arg2;	// IMP=0x001000000016ac9c
- (void)panGestureRecognizerMoved:(id)arg1;	// IMP=0x001000000016a318
- (void)upDoubleTapped:(id)arg1;	// IMP=0x001000000016a146
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;	// IMP=0x001000000016a072
- (void)scrollViewDidEndDecelerating:(id)arg1;	// IMP=0x001000000016a04d
- (void)scrollViewWillBeginDecelerating:(id)arg1;	// IMP=0x001000000016a028
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0010000000169f1f
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x0010000000169d28
- (_Bool)collectionView:(id)arg1 shouldUpdateFocusInContext:(id)arg2;	// IMP=0x0010000000169c46
- (struct CGPoint)collectionView:(id)arg1 targetContentOffsetForProposedContentOffset:(struct CGPoint)arg2;	// IMP=0x0010000000169c28
- (id)indexPathForPreferredFocusedViewInCollectionView:(id)arg1;	// IMP=0x0010000000169c12
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x0010000000169ba3
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x001000000016992c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00100000001697f4
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x00100000001697a5
- (void)invalidateSceneLayoutElements;	// IMP=0x0010000000169642
- (void)transitionToSwitcherWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000016956f
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x001000000016940c
- (void)_userInterfaceStyleDidChange;	// IMP=0x00100000001693a3
- (id)preferredFocusEnvironments;	// IMP=0x0010000000169329
- (void)viewDidLayoutSubviews;	// IMP=0x0010000000169205
- (void)dealloc;	// IMP=0x001000000016916a
- (void)viewDidLoad;	// IMP=0x00100000001688df
- (id)initWithWorkspaceGeometry:(id)arg1 dataSource:(id)arg2;	// IMP=0x001000000016878e
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000168780
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000168772

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

