//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSMutableDictionary, NSMutableSet, NSString, NSThread;
@protocol OS_dispatch_queue;

@interface PBDataReportingService : NSObject
{
    NSMutableSet *_seenEDIDs;	// 8 = 0x8
    NSMutableDictionary *_toReportEDIDData;	// 16 = 0x10
    NSDate *_lastSentEDIDTimestamp;	// 24 = 0x18
    NSMutableDictionary *_keyTimingStarts;	// 32 = 0x20
    NSMutableDictionary *_keyTimingTotals;	// 40 = 0x28
    NSMutableDictionary *_buttonPressTotals;	// 48 = 0x30
    NSThread *_NANDReportingThread;	// 56 = 0x38
    NSObject<OS_dispatch_queue> *_serialQueue;	// 64 = 0x40
    NSDictionary *_cachedCoreControlUsage;	// 72 = 0x48
    long long _persistentDisplayModeValue;	// 80 = 0x50
    NSString *_persistentDisplayModeString;	// 88 = 0x58
}

+ (unsigned long long)_roundDiskUsageInBytesToMB:(unsigned long long)arg1;	// IMP=0x00200000000b8385
+ (unsigned long long)_averageDiskUsageInMB:(unsigned long long)arg1 numberOfApps:(unsigned long long)arg2;	// IMP=0x00100000000b82d0
+ (id)_userAppsMetricsDictionaryWithSortedApplicationRecords:(id)arg1;	// IMP=0x00100000000b7e6f
+ (unsigned long long)_totalDiskUsageInBytesWithLSApplicationRecord:(id)arg1;	// IMP=0x00100000000b7d94
+ (id)_userAppsMetricsDictionary;	// IMP=0x00100000000b72e8
+ (id)serviceLog;	// IMP=0x00100000000b3521
+ (id)_sharedInstance;	// IMP=0x00100000000b32c7
+ (void)noteGuideEventResultForAction:(unsigned long long)arg1;	// IMP=0x00100000000b31a8
+ (void)incrementEventCountForRemoteButtonWithType:(long long)arg1;	// IMP=0x00100000000b2ff6
+ (void)stopTimingForAction:(unsigned long long)arg1;	// IMP=0x00100000000b2c3c
+ (void)startTimingForAction:(unsigned long long)arg1;	// IMP=0x00100000000b2a63
+ (void)incrementLongTVButtonPresses:(struct __IOHIDEvent *)arg1;	// IMP=0x00100000000b294c
+ (void)incrementLongMenuButtonPresses:(struct __IOHIDEvent *)arg1;	// IMP=0x00100000000b2835
+ (void)incrementEventCountForRemoteApp;	// IMP=0x00100000000b2828
+ (void)incrementEventCountForGameController;	// IMP=0x00100000000b281b
+ (void)incrementEventCountForBluetoothKeyboard;	// IMP=0x00100000000b280e
+ (void)incrementEventCountForCEC;	// IMP=0x00100000000b2801
+ (void)incrementEventCountForIRRemote;	// IMP=0x00100000000b27f4
+ (void)incrementEventCountForAppleBluetoothRemote;	// IMP=0x00100000000b27e7
+ (void)incrementB239TVButtonPresses;	// IMP=0x00100000000b27da
+ (void)incrementB239ButtonPresses;	// IMP=0x00100000000b27cd
+ (void)incrementOccurrenceCountForAction:(unsigned long long)arg1;	// IMP=0x00100000000b2656
+ (void)noteApplicationExit;	// IMP=0x00100000000b2611
+ (void)reportNow;	// IMP=0x00100000000b2520
+ (void)startService;	// IMP=0x00100000000b24b4
- (void).cxx_destruct;	// IMP=0x00200000000ba3cb
@property(copy, nonatomic) NSString *persistentDisplayModeString; // @synthesize persistentDisplayModeString=_persistentDisplayModeString;
@property(nonatomic) long long persistentDisplayModeValue; // @synthesize persistentDisplayModeValue=_persistentDisplayModeValue;
@property(copy, nonatomic) NSDictionary *cachedCoreControlUsage; // @synthesize cachedCoreControlUsage=_cachedCoreControlUsage;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) NSThread *NANDReportingThread; // @synthesize NANDReportingThread=_NANDReportingThread;
@property(retain, nonatomic) NSMutableDictionary *buttonPressTotals; // @synthesize buttonPressTotals=_buttonPressTotals;
@property(retain, nonatomic) NSMutableDictionary *keyTimingTotals; // @synthesize keyTimingTotals=_keyTimingTotals;
@property(retain, nonatomic) NSMutableDictionary *keyTimingStarts; // @synthesize keyTimingStarts=_keyTimingStarts;
@property(retain, nonatomic) NSDate *lastSentEDIDTimestamp; // @synthesize lastSentEDIDTimestamp=_lastSentEDIDTimestamp;
@property(retain, nonatomic) NSMutableDictionary *toReportEDIDData; // @synthesize toReportEDIDData=_toReportEDIDData;
@property(retain, nonatomic) NSMutableSet *seenEDIDs; // @synthesize seenEDIDs=_seenEDIDs;
- (unsigned long long)_integer:(unsigned long long)arg1 quantizedBy:(unsigned long long)arg2;	// IMP=0x00100000000ba277
- (unsigned long long)_quantizedTimeForKey:(id)arg1;	// IMP=0x00100000000ba133
- (void)powerManager:(id)arg1 willWakeSystemWithReason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000ba03c
- (void)powerManager:(id)arg1 willSleepSystemWithReason:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000b9eb9
- (void)_reportCurrentAudioOutputConfiguration;	// IMP=0x00100000000b9afe
- (void)_reportCurrentSystemSettingsMetrics;	// IMP=0x00100000000b991e
- (void)_reportCurrentVideoSettingsMetrics;	// IMP=0x00100000000b96f0
- (void)_reportCurrentAudioSettingsMetrics;	// IMP=0x00100000000b95a0
- (void)_reportRecoveryActions;	// IMP=0x00100000000b92d5
- (void)_threadReportNANDStatistics;	// IMP=0x00100000000b92cf
- (void)_reportNANDStatistics;	// IMP=0x00100000000b92c9
- (void)_reportButtonEventMetrics;	// IMP=0x00100000000b9093
- (void)_reportButtonPressMetrics;	// IMP=0x00100000000b83e0
- (void)_reportUserAppMetrics;	// IMP=0x00100000000b7207
- (void)_reportBluetoothDeviceMetrics;	// IMP=0x00100000000b6739
- (void)_sendToURL:(id)arg1 withSubtopic:(id)arg2 andParameters:(id)arg3;	// IMP=0x00100000000b63bd
- (id)_reportingURLForTopic:(id)arg1;	// IMP=0x00100000000b5fbc
- (void)_sendCoreControlUsage;	// IMP=0x00100000000b5d22
- (void)_sendEDIDURLRequest:(id)arg1;	// IMP=0x00100000000b591c
- (void)_sendEDIDLogs;	// IMP=0x00100000000b56b9
- (void)_recordEDID;	// IMP=0x00100000000b56b3
- (void)_cacheCoreControlUsageNow;	// IMP=0x00100000000b52f4
- (id)_coreControlCapabilityDataForDisplay:(id)arg1;	// IMP=0x00100000000b4e34
- (id)_arcPreferenceData;	// IMP=0x00100000000b4868
- (id)_coreControlDisplayAttributesForCurrentDisplay:(id)arg1;	// IMP=0x00100000000b4550
- (id)_dataReportingGUID;	// IMP=0x00100000000b44bd
- (void)_handleDisplayModeDidChange;	// IMP=0x00100000000b4443
- (void)tvs_bindDisplayModeBindingToObject:(id)arg1 withKeyPath:(id)arg2 options:(id)arg3;	// IMP=0x00100000000b434d
- (id)DisplayModeBinding;	// IMP=0x00100000000b42fb
- (void)_reportOptInConditionalMetrics;	// IMP=0x00100000000b42c1
- (void)_reportOptInUnconditionalMetrics;	// IMP=0x00100000000b42bb
- (void)_computeDisplayMetrics;	// IMP=0x00100000000b3e2d
- (void)_reportDailyDataNow;	// IMP=0x00100000000b3d76
- (void)_reportFrequentDataNow;	// IMP=0x00100000000b3cf1
- (void)_configureSleepWakeReporting;	// IMP=0x00100000000b3c9d
- (void)_schedulePeriodicTrigger;	// IMP=0x00100000000b38c7
- (void)_configureEDIDReporting;	// IMP=0x00100000000b3862
- (void)_configureMemoryPressureReporting;	// IMP=0x00100000000b37e0
- (void)_configureAggregateDataReporting;	// IMP=0x00100000000b3724
- (_Bool)_isDiagnosticsSubmissionAllowed;	// IMP=0x00100000000b3698
- (void)_incrementButtonEventCount:(id)arg1;	// IMP=0x00100000000b357f
- (id)init;	// IMP=0x00100000000b331e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

