//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, PBCoordinatedTransitionToken, PBProcessLaunchAgent, PBSSystemHomeUIStreamState, PBSystemHomeUIServiceRemoteViewController, PBSystemOverlayController, TVSObserverSet;

@interface PBHomeUIManager : NSObject
{
    _Bool _presenting;	// 8 = 0x8
    PBCoordinatedTransitionToken *_coordinatedTransitionToken;	// 16 = 0x10
    PBSystemOverlayController *_overlayController;	// 24 = 0x18
    TVSObserverSet *_observers;	// 32 = 0x20
    PBSystemHomeUIServiceRemoteViewController *_remoteViewController;	// 40 = 0x28
    PBProcessLaunchAgent *_processLaunchAgent;	// 48 = 0x30
}

+ (id)_sceneWorkspace;	// IMP=0x00200000000cc4ca
+ (id)_systemHomeUIServiceApplication;	// IMP=0x00100000000cc472
+ (id)sharedInstance;	// IMP=0x00100000000cb58e
+ (id)dependencyDescription;	// IMP=0x00100000000cb46d
- (void).cxx_destruct;	// IMP=0x00200000000cca41
@property(readonly, nonatomic) PBProcessLaunchAgent *processLaunchAgent; // @synthesize processLaunchAgent=_processLaunchAgent;
@property(readonly, nonatomic) __weak PBSystemHomeUIServiceRemoteViewController *remoteViewController; // @synthesize remoteViewController=_remoteViewController;
@property(readonly, nonatomic) TVSObserverSet *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) PBSystemOverlayController *overlayController; // @synthesize overlayController=_overlayController;
@property(readonly, nonatomic) PBCoordinatedTransitionToken *coordinatedTransitionToken; // @synthesize coordinatedTransitionToken=_coordinatedTransitionToken;
@property(readonly, nonatomic, getter=isPresenting) _Bool presenting; // @synthesize presenting=_presenting;
- (id)transitionCoordinator:(id)arg1 willDismissTransitionWithToken:(id)arg2 withContext:(id)arg3;	// IMP=0x00100000000cc7f4
- (void)pictureInPictureManager:(id)arg1 didCancelPictureInPictureForApplication:(id)arg2;	// IMP=0x00100000000cc755
- (void)remoteViewController:(id)arg1 didUpdateStreamState:(id)arg2;	// IMP=0x00100000000cc73f
- (void)remoteViewController:(id)arg1 didUpdateRequestsVisibility:(_Bool)arg2;	// IMP=0x00100000000cc623
- (void)overlayController:(id)arg1 didDismissSession:(id)arg2;	// IMP=0x00100000000cc5d6
- (void)overlayController:(id)arg1 willPresentSession:(id)arg2;	// IMP=0x00100000000cc591
- (void)_notifyObserversStreamStateDidUpdate:(id)arg1;	// IMP=0x00100000000cc3bb
- (_Bool)_tryActivatingCameraUsingExistingSceneWithContext:(id)arg1;	// IMP=0x00100000000cc2b1
- (void)_dismiss:(CDUnknownBlockType)arg1;	// IMP=0x00100000000cc0ad
- (void)_updateIsPresenting;	// IMP=0x00100000000cbffc
- (id)preheatSystemHomeUIServiceForReason:(id)arg1;	// IMP=0x00100000000cbe66
- (_Bool)dismissWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000cbdfd
- (void)presentCameraWithContext:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000cb976
- (id)addObserver:(id)arg1;	// IMP=0x00100000000cb94f
@property(readonly, nonatomic) PBSSystemHomeUIStreamState *currentStreamState;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000000cb86e
- (void)dealloc;	// IMP=0x00100000000cb822
- (id)init;	// IMP=0x00100000000cb615

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

