//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PBMainDisplaySystemGestureRecognizerManager
{
}

+ (id)sharedInstance;	// IMP=0x004000000002b7c9
- (id)initWithDisplayIdentity:(id)arg1;	// IMP=0x004000000002b8b6
- (id)init;	// IMP=0x001000000002b850

@end

