//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PBOSUpdateAssetManager : NSObject
{
    _Bool processingSpaceRequest;	// 8 = 0x8
    _Bool processingAssetRequest;	// 9 = 0x9
    _Bool processedAssetCatalogDownloadResponse;	// 10 = 0xa
}

+ (long long)_compareOSVersion:(id)arg1 andBuild:(id)arg2 withOSVersion:(id)arg3 andBuild:(id)arg4;	// IMP=0x004000000013f730
+ (id)sharedManager;	// IMP=0x0010000000137824
@property(nonatomic) _Bool processedAssetCatalogDownloadResponse; // @synthesize processedAssetCatalogDownloadResponse;
@property(nonatomic) _Bool processingAssetRequest; // @synthesize processingAssetRequest;
@property(nonatomic) _Bool processingSpaceRequest; // @synthesize processingSpaceRequest;
- (long long)_purgeAsset:(id)arg1;	// IMP=0x001000000013f348
- (void)_reportAssetCatalogDownloadWithResult:(long long)arg1 forAttempt:(long long)arg2;	// IMP=0x001000000013ee06
- (void)_refreshAssetCatalogUsingOptions:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000013e2bd
- (id)_downloadOptionsForScanOptions:(id)arg1;	// IMP=0x001000000013dae0
- (long long)_purgeableSizeFor:(id)arg1;	// IMP=0x001000000013d743
- (id)_postedDateForQuery:(id)arg1;	// IMP=0x001000000013d2be
- (long long)_performMetadataQuery:(id)arg1;	// IMP=0x001000000013ce48
- (id)_queryForLocalAssetSearch;	// IMP=0x001000000013cd8b
- (id)_queryForAssetDownload;	// IMP=0x001000000013cce0
- (id)_queryForAssetPurge;	// IMP=0x001000000013cc23
- (_Bool)_asset:(id)arg1 withReleaseDate:(id)arg2 matchesUpdate:(id)arg3;	// IMP=0x001000000013cba3
- (long long)_compareAsset:(id)arg1 withAsset:(id)arg2;	// IMP=0x001000000013c853
- (_Bool)_isAsset:(id)arg1 eligibleForAction:(unsigned long long)arg2 delayingUpdates:(_Bool)arg3;	// IMP=0x001000000013bd8d
- (void)_finishInstalledAssetForUpdate:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000013b379
- (void)_finishAssetForAction:(unsigned long long)arg1 options:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000013a434
- (void)_configureForVPN;	// IMP=0x001000000013a42e
- (void)dateAtWhichDelayedUpdatesExpireWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000139d1f
- (void)descriptorForCurrentlyInstalledAssetWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001397b1
- (id)descriptorForAsset:(id)arg1 withReleaseDate:(id)arg2;	// IMP=0x0010000000139039
- (void)installedAssetForUpdate:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000138da6
- (void)assetForAction:(unsigned long long)arg1 options:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000013884d
- (void)purgeLocalAssetsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001380c3
- (void)purgeableAssetSpaceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001378d1
- (id)init;	// IMP=0x001000000013787b

@end

