//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AXElement, NSDictionary, NSString;

@interface PBSiriScreenActionItem : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    NSDictionary *_semanticContext;	// 16 = 0x10
    AXElement *_accessibilityElement;	// 24 = 0x18
    NSString *_actionName;	// 32 = 0x20
    NSDictionary *_parameters;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000ad9d3
@property(copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(copy, nonatomic) NSString *actionName; // @synthesize actionName=_actionName;
@property(retain, nonatomic) AXElement *accessibilityElement; // @synthesize accessibilityElement=_accessibilityElement;
@property(retain, nonatomic) NSDictionary *semanticContext; // @synthesize semanticContext=_semanticContext;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)_firstAvailableChooseActionName;	// IMP=0x00100000000ad715
- (_Bool)_isEqualToSiriScreenItem:(id)arg1;	// IMP=0x00100000000ad684
- (id)_defaultIdentifier;	// IMP=0x00100000000ad541
- (id)_defaultSemanticContext;	// IMP=0x00100000000ad4ae
- (void)storeDeferredActionWithName:(id)arg1 parameters:(id)arg2;	// IMP=0x00100000000ad443
- (_Bool)performDeferredAction;	// IMP=0x00100000000ad214
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000ad0f3
- (id)description;	// IMP=0x00100000000ad017
- (unsigned long long)hash;	// IMP=0x00100000000acfd3
- (id)initWithAccessibilityElement:(id)arg1;	// IMP=0x00100000000acf68

@end

