//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BSAnimationSettings, NSMutableArray;

@interface PBWorkspaceTransitionRequest : NSObject
{
    NSMutableArray *_completionBlocks;	// 8 = 0x8
    _Bool _animated;	// 16 = 0x10
    long long _layout;	// 24 = 0x18
    BSAnimationSettings *_animationSettings;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000012a30a
@property(copy, nonatomic) BSAnimationSettings *animationSettings; // @synthesize animationSettings=_animationSettings;
@property(nonatomic) _Bool animated; // @synthesize animated=_animated;
@property(nonatomic) long long layout; // @synthesize layout=_layout;
- (id)description;	// IMP=0x001000000012a149
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000129f19
- (unsigned long long)hash;	// IMP=0x0010000000129e76
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000129dd6
- (unsigned long long)_completionBlockCount;	// IMP=0x0010000000129dbf
- (CDUnknownBlockType)_completionBlock;	// IMP=0x0010000000129ccf
- (void)addCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000129b9a
- (void)dealloc;	// IMP=0x0010000000129b6b
- (id)init;	// IMP=0x0010000000129b2b

// Remaining properties
// Error: Property attributes should begin with the type ('T') attribute, property name: completionBlockCount
// Property attributes: (null)


@end

