//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface RemoteConnectedStandbySM
{
    int _remoteConnectedStandbyAvailabilityDidChangeNotificationToken;	// 40 = 0x28
}

- (void)_notifyRemoteConnectedStandbyAvailabilityDidChange:(_Bool)arg1;	// IMP=0x002000000000ef4d
- (void)_initializeRemoteConnectedStandbyAvailability;	// IMP=0x001000000000ed58
- (void)_enterOffStateAutomatically;	// IMP=0x001000000000ed43
- (void)_enterOnStateAutomatically;	// IMP=0x001000000000ed2b
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x001000000000eb78
- (void)automaticDisable;	// IMP=0x001000000000eb72
- (id)init;	// IMP=0x001000000000eb04

@end

