//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MRContentItem, MRDNowPlayingPlayerClientPlaybackState, MRDPlaybackQueue, MRNowPlayingState, MROSTransaction, MRPlaybackQueue, MRPlaybackQueueSubscriptionController, MRPlayer, MRPlayerPath, NSArray, NSData, NSDate, NSMutableDictionary;
@protocol MRDNowPlayingPlayerClientDelegate, OS_dispatch_queue;

@interface MRDNowPlayingPlayerClient : NSObject
{
    MRPlayerPath *_playerPath;	// 8 = 0x8
    NSArray *_supportedRemoteControlCommands;	// 16 = 0x10
    NSData *_supportedRemoteControlCommandsData;	// 24 = 0x18
    MRDPlaybackQueue *_playbackQueueInternal;	// 32 = 0x20
    unsigned long long _playbackQueueCapabilities;	// 40 = 0x28
    NSDate *_canBeNowPlayingPlayerTimestamp;	// 48 = 0x30
    MRDNowPlayingPlayerClientPlaybackState *_playerPlaybackState;	// 56 = 0x38
    MRDNowPlayingPlayerClientPlaybackState *_inferredPlayerPlaybackState;	// 64 = 0x40
    NSMutableDictionary *_playbackStateHistory;	// 72 = 0x48
    _Bool _pictureInPictureEnabled;	// 80 = 0x50
    _Bool _canBeNowPlayingPlayer;	// 81 = 0x51
    MROSTransaction *_hasNowPlayingDataTransaction;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_serialQueue;	// 96 = 0x60
    _Bool _pushStateIsPlaying;	// 104 = 0x68
    _Bool _pushStateHasNowPlayingData;	// 105 = 0x69
    _Bool _pushStatePictureInPictureEnabled;	// 106 = 0x6a
    _Bool _pushStateCanBeNowPlayingPlayer;	// 107 = 0x6b
    NSDate *_lastPlayingDate;	// 112 = 0x70
    MRPlaybackQueueSubscriptionController *_subscriptionController;	// 120 = 0x78
    id <MRDNowPlayingPlayerClientDelegate> _delegate;	// 128 = 0x80
    MRDNowPlayingPlayerClientPlaybackState *_pushStatePlaybackState;	// 136 = 0x88
    MRPlayer *_pushStatePlayer;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x0010000000026580
@property(nonatomic) _Bool pushStateCanBeNowPlayingPlayer; // @synthesize pushStateCanBeNowPlayingPlayer=_pushStateCanBeNowPlayingPlayer;
@property(nonatomic) _Bool pushStatePictureInPictureEnabled; // @synthesize pushStatePictureInPictureEnabled=_pushStatePictureInPictureEnabled;
@property(nonatomic) _Bool pushStateHasNowPlayingData; // @synthesize pushStateHasNowPlayingData=_pushStateHasNowPlayingData;
@property(retain, nonatomic) MRPlayer *pushStatePlayer; // @synthesize pushStatePlayer=_pushStatePlayer;
@property(retain, nonatomic) MRDNowPlayingPlayerClientPlaybackState *pushStatePlaybackState; // @synthesize pushStatePlaybackState=_pushStatePlaybackState;
@property(nonatomic) _Bool pushStateIsPlaying; // @synthesize pushStateIsPlaying=_pushStateIsPlaying;
@property(nonatomic) __weak id <MRDNowPlayingPlayerClientDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) MRPlaybackQueueSubscriptionController *subscriptionController; // @synthesize subscriptionController=_subscriptionController;
@property(readonly, nonatomic) NSDate *lastPlayingDate; // @synthesize lastPlayingDate=_lastPlayingDate;
- (void)_onQueue_popState;	// IMP=0x0010000000025adc
- (void)_onQueue_pushState;	// IMP=0x00100000000259bd
- (void)_onQueue_playbackQueueContentItemsArtworkDidChange:(id)arg1;	// IMP=0x001000000002590b
- (void)_onQueue_playbackQueueContentItemsDidChange:(id)arg1;	// IMP=0x0010000000025859
- (void)_onQueue_playbackQueueCapabilitiesDidChange:(unsigned long long)arg1;	// IMP=0x0010000000025808
- (void)_onQueue_playbackQueueDidChange:(id)arg1 nowPlayingItemChanged:(_Bool)arg2;	// IMP=0x0010000000025779
- (void)_onQueue_supportedCommandsDidChange:(id)arg1;	// IMP=0x00100000000256ef
- (void)_onQueue_playbackStateDidChanged:(id)arg1;	// IMP=0x00100000000255e7
- (void)_onQueue_pictureInPictureEnabledDidChanged:(_Bool)arg1;	// IMP=0x0010000000025598
- (void)_onQueue_isPlayingDidChange:(_Bool)arg1;	// IMP=0x0010000000025517
- (void)_onQueue_canBeNowPlayingDidChange:(_Bool)arg1;	// IMP=0x00100000000254c8
- (void)_handleNowPlayingAppDidChange:(id)arg1;	// IMP=0x00100000000253d4
- (id)cachedArtworkForContentItem:(id)arg1;	// IMP=0x00100000000253cc
- (id)playbackQueueForRequest:(id)arg1 cachingPolicy:(unsigned int)arg2 playerPath:(id)arg3 partiallyCachedItems:(id *)arg4;	// IMP=0x00100000000250af
- (id)_sortSnapshots:(id)arg1;	// IMP=0x001000000002507b
@property(readonly, nonatomic) NSArray *snapshots;
- (id)snapshotForIsPlaying:(_Bool)arg1;	// IMP=0x0010000000024eff
- (id)snapshotsForIsPlaying:(_Bool)arg1;	// IMP=0x0010000000024cbe
- (id)snapshotForPlaybackState:(unsigned int)arg1;	// IMP=0x0010000000024b85
- (void)notifyArtworkChangedForContentItems:(id)arg1;	// IMP=0x0010000000024a9b
- (void)_onQueue_updatePlaybackQueue:(id)arg1 fromRequest:(id)arg2;	// IMP=0x0010000000024510
- (void)updatePlaybackQueue:(id)arg1 fromRequest:(id)arg2;	// IMP=0x0010000000024437
- (void)updatePlaybackQueue:(id)arg1;	// IMP=0x0010000000024423
- (void)updatePlayer:(id)arg1;	// IMP=0x0010000000024322
- (void)updateClient:(id)arg1;	// IMP=0x0010000000024247
@property(nonatomic, getter=isPictureInPictureEnabled) _Bool pictureInPictureEnabled;
@property(retain, nonatomic) MRPlayerPath *playerPath;
- (id)_onQueue_lastPlayingDate;	// IMP=0x001000000002403d
@property(readonly, nonatomic) double timeSincePlaying;
@property(readonly, nonatomic) MRNowPlayingState *nowPlayingState;
@property(readonly, nonatomic) _Bool hasNowPlayingData;
- (_Bool)_onQueue_isPlaying;	// IMP=0x0010000000023a2b
@property(readonly, nonatomic) _Bool isPlaying;
@property(nonatomic) unsigned long long playbackQueueCapabilities;
- (id)_onQueue_playbackState;	// IMP=0x0010000000023468
@property(readonly, nonatomic) NSDate *playbackStateTimestamp;
@property(readonly, nonatomic) unsigned int playbackState;
@property(copy, nonatomic) NSDate *canBeNowPlayingPlayerTimestamp;
@property(nonatomic) _Bool canBeNowPlayingPlayer;
- (void)updateLastPlayingDate:(id)arg1;	// IMP=0x0010000000022e84
- (void)updatePlaybackState:(unsigned int)arg1 date:(id)arg2;	// IMP=0x0010000000022bc8
@property(nonatomic) unsigned int inferredPlaybackState;
@property(readonly, nonatomic) MRContentItem *nowPlayingContentItem;
@property(copy, nonatomic) MRPlaybackQueue *playbackQueue;
@property(copy, nonatomic) NSData *supportedRemoteControlCommandsData;
@property(retain, nonatomic) NSArray *supportedRemoteControlCommands;
@property(readonly, nonatomic) MRPlayer *player;
- (id)description;	// IMP=0x0010000000021558
- (id)initWithPlayerPath:(id)arg1;	// IMP=0x001000000002135c
- (id)activeContent;	// IMP=0x00100000000212b9
- (_Bool)isActiveStream;	// IMP=0x00100000000212a7

@end

