//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MediaRemote/MRAVRoutingDiscoverySession.h>

@class MISSING_TYPE, MRAVConcreteRoutingDiscoverySession, MRAVOutputDevice, MRAVRoutingDiscoverySessionConfiguration, MRAirPlayTransportConnection, MRCompanionConnectionController, MRDIDSDiscoverySession, MRDeviceInfo, NSArray, NSObject, NSSet, NSString, NSUserDefaults, _TtC12mediaremoted31MRDGroupSessionDiscoverySession;
@protocol OS_dispatch_queue;

@interface MRDRemoteControlDiscoverySession : MRAVRoutingDiscoverySession
{
    unsigned int _discoveryMode;	// 8 = 0x8
    MISSING_TYPE *_scheduledAvailableOutputDevicesReload;	// 12 = 0xc
    NSArray *_availableOutputDevices;	// 16 = 0x10
    NSArray *_unclusteredOutputDevices;	// 24 = 0x18
    MRAVOutputDevice *_unclusteredLocalOutputDevice;	// 32 = 0x20
    NSString *_routingContextID;	// 40 = 0x28
    MRDeviceInfo *_deviceInfo;	// 48 = 0x30
    id _externalDiscoverySessionToken;	// 56 = 0x38
    NSSet *_lastReportedClientIdentifiers;	// 64 = 0x40
    MRAVConcreteRoutingDiscoverySession *_avDiscoverySession;	// 72 = 0x48
    MRDIDSDiscoverySession *_idsDiscoverySession;	// 80 = 0x50
    _TtC12mediaremoted31MRDGroupSessionDiscoverySession *_groupSessionDiscoverySession;	// 88 = 0x58
    MRAVRoutingDiscoverySession *_companionDiscoverySession;	// 96 = 0x60
    MRAVRoutingDiscoverySession *_externalDiscoverySession;	// 104 = 0x68
    MRCompanionConnectionController *_companionController;	// 112 = 0x70
    MRAirPlayTransportConnection *_localEndpointConnection;	// 120 = 0x78
    NSObject<OS_dispatch_queue> *_workerQueue;	// 128 = 0x80
    NSArray *_allowList;	// 136 = 0x88
    NSArray *_denyList;	// 144 = 0x90
    NSUserDefaults *_userDefaults;	// 152 = 0x98
}

- (void).cxx_destruct;	// IMP=0x002000000004662a
@property(readonly, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(readonly, nonatomic) NSArray *denyList; // @synthesize denyList=_denyList;
@property(readonly, nonatomic) NSArray *allowList; // @synthesize allowList=_allowList;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workerQueue; // @synthesize workerQueue=_workerQueue;
@property(retain, nonatomic) MRAirPlayTransportConnection *localEndpointConnection; // @synthesize localEndpointConnection=_localEndpointConnection;
@property(retain, nonatomic) MRCompanionConnectionController *companionController; // @synthesize companionController=_companionController;
@property(retain, nonatomic) MRAVRoutingDiscoverySession *externalDiscoverySession; // @synthesize externalDiscoverySession=_externalDiscoverySession;
@property(retain, nonatomic) MRAVRoutingDiscoverySession *companionDiscoverySession; // @synthesize companionDiscoverySession=_companionDiscoverySession;
@property(retain, nonatomic) _TtC12mediaremoted31MRDGroupSessionDiscoverySession *groupSessionDiscoverySession; // @synthesize groupSessionDiscoverySession=_groupSessionDiscoverySession;
@property(retain, nonatomic) MRDIDSDiscoverySession *idsDiscoverySession; // @synthesize idsDiscoverySession=_idsDiscoverySession;
@property(retain, nonatomic) MRAVConcreteRoutingDiscoverySession *avDiscoverySession; // @synthesize avDiscoverySession=_avDiscoverySession;
- (void)_setupProxiedDiscoveryWithDestinationEndpoint:(id)arg1;	// IMP=0x0010000000046244
- (void)_setupStandaloneDiscovery;	// IMP=0x0010000000045ff3
- (void)_initializeDiscoverySessions;	// IMP=0x0010000000045c6d
- (_Bool)_shouldCreateClusterOutputDevices;	// IMP=0x0010000000045c22
- (_Bool)shouldUseDeviceInfoForLocalDevice;	// IMP=0x0010000000045b97
- (void)_loadDefaults;	// IMP=0x0010000000045832
- (void)_loadLocalEndpointConnection;	// IMP=0x0010000000044f27
- (void)_logChangesInModifyingOutputDevice:(id)arg1 toOutputDevice:(id)arg2 reason:(id)arg3;	// IMP=0x0010000000044b29
- (id)_addUndiscoveredOutputContextOutputDevices:(id)arg1;	// IMP=0x0010000000044031
- (id)_applyLocalReservedOutputContextValuesToOutputDevices:(id)arg1;	// IMP=0x0010000000043cf0
- (id)_applyDeviceInfoValuesToOutputDevices:(id)arg1 withDeviceInfo:(id)arg2;	// IMP=0x0010000000043a17
- (id)_applyOutputContextValuesToOutputDevices:(id)arg1;	// IMP=0x00100000000434a6
- (id)_applyLocallySourcedValuesToOutputDevices:(id)arg1;	// IMP=0x001000000004333d
- (id)_fetchAvailableOutputDevicesFromDiscoverySessions;	// IMP=0x0010000000043131
- (id)_clusterOutputDevicesFromUnclusteredDevices:(id)arg1;	// IMP=0x0010000000042d84
- (void)_reloadOutputDevices;	// IMP=0x001000000004291b
- (void)_scheduleAvailableOutputDevicesReload;	// IMP=0x0010000000042843
- (void)controllerDidUndiscoverCompanion:(id)arg1;	// IMP=0x00100000000427db
- (void)controller:(id)arg1 didDiscoverCompanion:(id)arg2;	// IMP=0x001000000004272a
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0010000000042670
- (void)transportDidClose:(id)arg1 error:(id)arg2;	// IMP=0x00100000000425af
- (void)transport:(id)arg1 didReceiveData:(id)arg2;	// IMP=0x00100000000425a9
@property(readonly, nonatomic) NSSet *lastReportedClientIdentifiers;
@property(retain, nonatomic) MRDeviceInfo *deviceInfo;
- (id)routingContextUID;	// IMP=0x0010000000042451
- (void)setRoutingContextUID:(id)arg1;	// IMP=0x00100000000423f0
@property(retain, nonatomic) MRAVOutputDevice *unclusteredLocalOutputDevice;
@property(retain, nonatomic) NSArray *unclusteredOutputDevices;
@property(retain, nonatomic) NSArray *availableOutputDevices;
- (id)availableEndpoints;	// IMP=0x00100000000421b0
- (_Bool)devicePresenceDetected;	// IMP=0x0010000000042168
- (unsigned int)endpointFeatures;	// IMP=0x001000000004215d
- (unsigned int)discoveryMode;	// IMP=0x0010000000042121
- (void)setDiscoveryMode:(unsigned int)arg1;	// IMP=0x00100000000420cb
- (void)setDiscoveryMode:(unsigned int)arg1 forClientIdentifiers:(id)arg2;	// IMP=0x0010000000041e1f
@property(readonly, nonatomic) MRAVRoutingDiscoverySessionConfiguration *configuration;
@property(readonly, copy) NSString *debugDescription;
- (id)init;	// IMP=0x00100000000410dc

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

