//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;
@protocol MRDVirtualAudioInputServerDelegate, OS_dispatch_queue;

@interface MRDVirtualAudioInputServer : NSObject
{
    NSMutableArray *_recordingEndpointClients;	// 8 = 0x8
    NSMutableArray *_registeredDevices;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_serialQueue;	// 24 = 0x18
    id <MRDVirtualAudioInputServerDelegate> _delegate;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000123d68
@property(nonatomic) __weak id <MRDVirtualAudioInputServerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_handleRecordingEndpointAvailabilityMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000123bfd
- (void)_handleVoiceDataReceivedMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000123aab
- (void)_handleRecordingStateChangedMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x001000000012390a
- (void)_handleInputDeviceDisconnectedMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x00100000001233fe
- (void)_handleInputDeviceConnectedMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000123008
- (void)_handleGetDevicesMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000122d81
- (void)collectDiagnostic:(id)arg1;	// IMP=0x0010000000122cb0
- (void)handleXPCMessage:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000122c2a
- (void)clearRecordingEndpointsForClient:(id)arg1;	// IMP=0x0010000000122a3b
- (void)clearRegisteredDevicesForClient:(id)arg1;	// IMP=0x00100000001227e7
- (id)registeredDeviceWithID:(unsigned int)arg1;	// IMP=0x00100000001225c9
@property(readonly, copy, nonatomic) NSArray *registeredDevices;
@property(readonly, copy, nonatomic) NSArray *recordingEndpointClients;
- (id)init;	// IMP=0x00100000001222fb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

