//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface VOTConfiguration : NSObject
{
}

+ (id)rootConfiguration;	// IMP=0x00400000000137c0
+ (void)initialize;	// IMP=0x0010000000013736
- (void)setPreferenceSync:(id)arg1 forKey:(id)arg2;	// IMP=0x0040000000013910
- (void)setPreference:(id)arg1 forKey:(id)arg2;	// IMP=0x00100000000137fc
- (id)preferenceForKey:(id)arg1;	// IMP=0x00100000000137d1

@end

