//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class SecureBackupTermsInfo;

@interface StoredTermsInfo : PBCodable
{
    unsigned long long _storageVersion;	// 8 = 0x8
    SecureBackupTermsInfo *_termsInfo;	// 16 = 0x10
    struct {
        unsigned int storageVersion:1;
    } _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000005ea4f
@property(retain, nonatomic) SecureBackupTermsInfo *termsInfo; // @synthesize termsInfo=_termsInfo;
@property(nonatomic) unsigned long long storageVersion; // @synthesize storageVersion=_storageVersion;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000005e99f
- (unsigned long long)hash;	// IMP=0x001000000005e955
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000005e899
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000005e805
- (void)copyTo:(id)arg1;	// IMP=0x001000000005e7a1
- (void)writeTo:(id)arg1;	// IMP=0x001000000005e73b
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000005e72e
- (id)dictionaryRepresentation;	// IMP=0x001000000005e408
- (id)description;	// IMP=0x001000000005e359
@property(readonly, nonatomic) _Bool hasTermsInfo;
@property(nonatomic) _Bool hasStorageVersion;

@end

