//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCAirPlaySecurityPayloadHandler
{
}

- (void)_setAccessType:(id)arg1 securityType:(id)arg2 password:(id)arg3;	// IMP=0x0040000000073b67
- (void)_unsetAirPlaySecurityConfiguration;	// IMP=0x00100000000739e8
- (void)_setAirPlaySecurityConfiguration;	// IMP=0x00100000000737c1
- (void)unsetAside;	// IMP=0x00100000000737af
- (void)remove;	// IMP=0x0010000000073743
- (void)setAside;	// IMP=0x0010000000073731
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x001000000007371c

@end

