//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MCProfile;

@interface MCDNSSettingsPayloadHandler
{
    MCProfile *_profile;	// 32 = 0x20
}

+ (id)internalErrorWithUnderlyingError:(id)arg1;	// IMP=0x0040000000081945
+ (id)internalError;	// IMP=0x0010000000081931
- (void).cxx_destruct;	// IMP=0x0020000000081a04
- (void)remove;	// IMP=0x00100000000819fe
- (void)unsetAside;	// IMP=0x00100000000819f8
- (void)setAside;	// IMP=0x00100000000819f2
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x00100000000819ea
- (id)initWithPayload:(id)arg1 profileHandler:(id)arg2;	// IMP=0x00100000000818a2

@end

