//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MCKeybagUnlockAssertion : NSObject
{
}

+ (void)releaseAssertion;	// IMP=0x004000000007d663
+ (void)holdAssertion;	// IMP=0x001000000007d5c2
+ (id)assertionHoldQueue;	// IMP=0x001000000007d56b
- (void)dealloc;	// IMP=0x004000000007d752
- (id)init;	// IMP=0x001000000007d702

@end

