//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCNewAPNPayloadHandler
{
}

- (void)didRemoveOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x0040000000043d36
- (void)didInstallOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x0010000000043d24
- (void)_sendNotifications;	// IMP=0x0010000000043c1c
- (void)unsetAside;	// IMP=0x0010000000043bb0
- (void)setAside;	// IMP=0x0010000000043b44
- (void)remove;	// IMP=0x0010000000043a82
- (void)_remove;	// IMP=0x00100000000439be
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x00100000000436b7
- (_Bool)_hasAPNManagedPreferences;	// IMP=0x0010000000043627
- (_Bool)_install;	// IMP=0x0010000000043581
- (void)_notifyCoreTelephonyOfAPNChange;	// IMP=0x00100000000434bf

@end

