//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface MCProfileDaemonManagedConfigurationHelper : NSObject
{
}

- (void)removeApplicationWithBundleID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0020000000080d75
- (void)removeProfileWithIdentifier:(id)arg1 async:(_Bool)arg2;	// IMP=0x0010000000080c71

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

