//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSInputStream.h>

@class NSFileHandle;

@interface ACLSFileHandleInputStream : NSInputStream
{
    NSFileHandle *_fileHandle;	// 8 = 0x8
    long long _fileOffset;	// 16 = 0x10
    long long _fileEndOffset;	// 24 = 0x18
    unsigned long long _status;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000007b71
@property unsigned long long status; // @synthesize status=_status;
@property long long fileEndOffset; // @synthesize fileEndOffset=_fileEndOffset;
@property long long fileOffset; // @synthesize fileOffset=_fileOffset;
@property(retain) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
- (_Bool)hasBytesAvailable;	// IMP=0x0010000000007ac5
- (_Bool)getBuffer:(char **)arg1 length:(unsigned long long *)arg2;	// IMP=0x0010000000007abd
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;	// IMP=0x0010000000007a54
- (void)_unscheduleFromCFRunLoop:(struct __CFRunLoop *)arg1 forMode:(struct __CFString *)arg2;	// IMP=0x0010000000007a4e
- (_Bool)_setCFClientFlags:(unsigned long long)arg1 callback:(CDUnknownFunctionPointerType)arg2 context:(CDStruct_e097db04 *)arg3;	// IMP=0x0010000000007a46
- (void)_scheduleInCFRunLoop:(struct __CFRunLoop *)arg1 forMode:(struct __CFString *)arg2;	// IMP=0x0010000000007a40
- (id)streamError;	// IMP=0x0010000000007a38
- (unsigned long long)streamStatus;	// IMP=0x00100000000079f2
- (void)close;	// IMP=0x00100000000079dd
- (void)open;	// IMP=0x00100000000079c8
- (id)initWithFileHandle:(id)arg1 fileOffset:(long long)arg2 length:(long long)arg3;	// IMP=0x0010000000007921

@end

