//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CPLPrequeliteClientCache
{
}

- (_Bool)deleteRecordsForScopeIndex:(long long)arg1 maxCount:(long long)arg2 deletedCount:(long long *)arg3 error:(id *)arg4;	// IMP=0x0020000000068542
- (void)fillRelatedIdentifiersInChange:(id)arg1;	// IMP=0x00100000000682be
- (id)statusPerScopeIndex;	// IMP=0x001000000006825c
- (id)statusDictionary;	// IMP=0x00100000000680f9
- (id)status;	// IMP=0x0010000000067f8b
- (_Bool)_updateRelatedIdentifier:(id)arg1 forRecordWithIdentifier:(id)arg2;	// IMP=0x0010000000067ea5
- (_Bool)_deleteBadRelations;	// IMP=0x0010000000067dd9
- (id)_badContainerRelationsIdentifiers;	// IMP=0x0010000000067cd5
- (unsigned long long)countOfRecordsWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;	// IMP=0x0010000000067b80
- (_Bool)hasRecordWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;	// IMP=0x0010000000067a2b
- (id)recordsWithRelatedScopedIdentifier:(id)arg1 class:(Class)arg2;	// IMP=0x0010000000067530
- (id)recordsWithRelatedScopedIdentifier:(id)arg1;	// IMP=0x001000000006706d
- (_Bool)hasRecordWithScopedIdentifier:(id)arg1;	// IMP=0x0010000000066f44
- (id)relatedScopedIdentifierForRecordWithScopedIdentifier:(id)arg1;	// IMP=0x0010000000066d95
- (id)recordWithScopedIdentifier:(id)arg1;	// IMP=0x0010000000066a5f
- (_Bool)deleteRecordWithScopedIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000006680c
- (_Bool)updateRecord:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000066400
- (_Bool)addRecord:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000065fca
- (_Bool)upgradeStorageToVersion:(long long)arg1;	// IMP=0x0010000000065d44
- (_Bool)initializeStorage;	// IMP=0x0010000000065bc6
- (id)initWithAbstractObject:(id)arg1;	// IMP=0x0010000000065b97

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

