//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSUUID;

@interface MILaunchServicesOperation : NSObject
{
    NSUUID *_operationUUID;	// 8 = 0x8
    unsigned long long _serialNumber;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000000cf1e
- (void).cxx_destruct;	// IMP=0x002000000000d386
@property(readonly, nonatomic) unsigned long long serialNumber; // @synthesize serialNumber=_serialNumber;
@property(readonly, nonatomic) NSUUID *operationUUID; // @synthesize operationUUID=_operationUUID;
- (id)description;	// IMP=0x001000000000d2c3
- (unsigned long long)hash;	// IMP=0x001000000000d261
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000d152
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000000d08d
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000000cf26
- (id)initWithOperationUUID:(id)arg1 serialNumber:(unsigned long long)arg2;	// IMP=0x001000000000cea7

@end

