//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSSet, NSString, NSURL;

@interface MILaunchServicesRegisterOperation
{
    NSString *_bundleID;	// 8 = 0x8
    unsigned long long _domain;	// 16 = 0x10
    NSSet *_personaUniqueStrings;	// 24 = 0x18
    NSURL *_mountPoint;	// 32 = 0x20
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00200000000464e0
- (MISSING_TYPE *).cxx_destruct;	// IMP=0x0020000000046ecb
@property(readonly, nonatomic) NSURL *mountPoint; // @synthesize mountPoint=_mountPoint;
@property(readonly, nonatomic) NSSet *personaUniqueStrings; // @synthesize personaUniqueStrings=_personaUniqueStrings;
@property(readonly, nonatomic) unsigned long long domain; // @synthesize domain=_domain;
@property(readonly, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (id)description;	// IMP=0x0010000000046c87
- (void)updatePersonaUniqueStrings:(id)arg1;	// IMP=0x0010000000046c53
- (unsigned long long)hash;	// IMP=0x0010000000046b5e
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000004696a
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000046818
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000464e8
- (id)initWithBundleID:(id)arg1 domain:(unsigned long long)arg2 personas:(id)arg3 mountPoint:(id)arg4 operationUUID:(id)arg5 serialNumber:(unsigned long long)arg6;	// IMP=0x00100000000463cf

@end

