//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC9appstored19AppDownloadDoneTask
{
    MISSING_TYPE *bag;	// 8 = 0x8
    MISSING_TYPE *store;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0040000000026570
- (id)initWithoutKeepAlive;	// IMP=0x0010000000026510
- (void)main;	// IMP=0x0010000000023d60
- (id)init;	// IMP=0x0010000000022ad0

@end

