//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC9appstored13LaunchHistory : NSObject
{
    MISSING_TYPE *twentyEightDays;	// 8 = 0x8
    MISSING_TYPE *fiveMinutes;	// 16 = 0x10
    MISSING_TYPE *lockedThing;	// 24 = 0x18
}

+ (id)shared;	// IMP=0x00200000000118d0
- (void).cxx_destruct;	// IMP=0x0040000000014210
- (id)init;	// IMP=0x0010000000014150
- (id)getBiomeLaunchesWithLogKey:(id)arg1 dateInterval:(id)arg2 latestLaunchOnly:(_Bool)arg3;	// IMP=0x0010000000014070
- (id)syncLaunchesWithLogKey:(id)arg1;	// IMP=0x0010000000013ec0
- (id)syncIfNeededWithLogKey:(id)arg1;	// IMP=0x0010000000012e70
- (id)getLaunchesWithLogKey:(id)arg1 dateInterval:(id)arg2;	// IMP=0x0010000000012600
- (void)clearLaunchHistoryWithBundleIDs:(id)arg1;	// IMP=0x00100000000120e0

@end

