//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SQLiteDatabase;

@interface Environment : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    SQLiteDatabase *_userDatabase;	// 16 = 0x10
    SQLiteDatabase *_systemDatabase;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000038d1b
- (id)init;	// IMP=0x0010000000038ac6

@end

