//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AppInstallsDatabaseStore, NSString, RequestThrottle, TaskQueue;
@protocol OS_dispatch_queue;

@interface InstallationService : NSObject
{
    id _bagChangedNotification;	// 8 = 0x8
    AppInstallsDatabaseStore *_databaseStore;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 24 = 0x18
    RequestThrottle *_requestThrottle;	// 32 = 0x20
    TaskQueue *_taskQueue;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000005a4a9
- (void)installTestFlightApps:(id)arg1 onPairedDevice:(id)arg2 withReplyHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000005a307
- (void)installScreenSyncApps:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000059905
- (void)installEnterpriseApps:(id)arg1 onPairedDevice:(id)arg2 withReplyHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000005983b
- (void)installAppReviewApps:(id)arg1 withReplyHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000059617
- (id)_init;	// IMP=0x001000000005955f
- (void)dealloc;	// IMP=0x00100000000594ea
- (id)init;	// IMP=0x00100000000594d8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

