//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMapTable, NSMutableDictionary, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface JobManagerListener
{
    NSMapTable *_clients;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    NSMutableDictionary *_progress;	// 24 = 0x18
    _Bool _progressDirty;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000013ffac
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000013e61d
- (void)_handleLegacyNotifications:(id)arg1;	// IMP=0x001000000013daf2
- (void)resumeJobsWithIDs:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000013d86e
- (void)registerJobManagerWithOptions:(id)arg1 replyBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000013d4a7
- (void)pauseJobsWithIDs:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000013d210
- (void)getJobsWithIDs:(id)arg1 usingReplyBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000013ceb1
- (void)getJobsUsingReplyBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000013cc9b
- (void)finishJobsWithIDs:(id)arg1 replyBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000013ca17
- (void)cancelJobsWithIDs:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000013c699
- (id)init;	// IMP=0x001000000013c593

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

