//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class LibraryQueryPlanner, NSDictionary, NSString, ProgressCache;
@protocol LibraryCatalogObserver, OS_dispatch_queue;

@interface LaunchServicesCatalog : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    id <LibraryCatalogObserver> _observer;	// 16 = 0x10
    LibraryQueryPlanner *_planner;	// 24 = 0x18
    ProgressCache *_progressCache;	// 32 = 0x20
    NSDictionary *_systemAppMappingByBundleID;	// 40 = 0x28
    NSDictionary *_systemAppMappingByItemID;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0020000000125857
@property __weak id <LibraryCatalogObserver> observer; // @synthesize observer=_observer;
- (void)_handleBagInvalidatedNotification:(id)arg1;	// IMP=0x00100000001257d0
- (void)_handleBagChangedNotification:(id)arg1;	// IMP=0x0010000000125770
- (void)_handleAppUnregisteredNotification:(id)arg1;	// IMP=0x00100000001253b8
- (void)_handleAppRegisteredNotification:(id)arg1;	// IMP=0x001000000012505e
- (id)resultsWithItemIDs:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000124bfe
- (id)resultsWithBundleIDs:(id)arg1 error:(id *)arg2;	// IMP=0x001000000012493d
- (id)resultsMatchingPredicate:(id)arg1 error:(id *)arg2;	// IMP=0x0000000000124771
- (void)launchApp:(id)arg1 withResultHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000124143
- (void)launchApp:(id)arg1 onPairedDevice:(id)arg2 withResultHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000012412e
- (void)launchApp:(id)arg1 extensionType:(long long)arg2 withResultHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000123cd5
- (void)executeQueryForUpdatesReloadingFromServer:(_Bool)arg1 logKey:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x001000000012357b
- (void)executeQuery:(id)arg1 excludingBundleIDs:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x001000000012335c
- (void)applicationsDidUninstall:(id)arg1;	// IMP=0x0010000000123168
- (void)applicationsDidInstall:(id)arg1;	// IMP=0x00100000001227f7
- (void)dealloc;	// IMP=0x0010000000121ec4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

