//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface OSVersion : NSObject
{
    struct _OSVersion _version;	// 8 = 0x8
}

- (_Bool)isEqual:(id)arg1;	// IMP=0x002000000006c6a4
- (unsigned long long)hash;	// IMP=0x001000000006c687
- (id)description;	// IMP=0x001000000006c67d

@end

