//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, RestoreBootstrapInfo, TaskQueue;
@protocol OS_dispatch_queue;

@interface RestoreManager : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    TaskQueue *_restoreQueue;	// 16 = 0x10
    _Bool _bootstrapDeviceMonitorAdded;	// 24 = 0x18
    _Bool _bootstrapNetworkMonitorAdded;	// 25 = 0x19
    _Bool _bootstrapBagMonitorAdded;	// 26 = 0x1a
    RestoreBootstrapInfo *_bootstrapInfo;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000d2a41
- (void)authenticateTask:(id)arg1 handleDialogRequest:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000d27cf
- (void)_handleMonitorStateDidChangeNotification:(id)arg1;	// IMP=0x00100000000d1322
- (void)_bootstrapWhenReadyWithInfo:(id)arg1;	// IMP=0x00100000000d03f0
- (id)init;	// IMP=0x00100000000c9999

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

