//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SKANGhostbackEntity
{
}

+ (id)defaultProperties;	// IMP=0x0040000000074093
+ (Class)memoryEntityClass;	// IMP=0x0010000000074082
+ (id)databaseTable;	// IMP=0x0010000000074075
- (_Bool)canUpdateWithRestrictedConversionValue:(long long)arg1;	// IMP=0x0040000000074168

@end

