//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface SoftwareUpdateListener
{
}

- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00200000001a02e3
- (void)shouldUseModernUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a0186
- (void)updateAllWithOrder:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000019fead
- (void)updateAllWithJobResults:(CDUnknownBlockType)arg1;	// IMP=0x001000000019fbf0
- (void)reloadManagedUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019fa2d
- (void)reloadFromServerWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019f86d
- (void)reloadFromServerInBackgroundWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019f547
- (void)removeUpdateBulletins;	// IMP=0x001000000019f453
- (void)showApplicationBadgeForPendingUpdates;	// IMP=0x001000000019f325
- (void)showApplicationUpdatesBulletin;	// IMP=0x001000000019f231
- (void)refreshUpdatesWithCompletionBlock:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000019f112
- (void)refreshUpdateCountWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019ee6a
- (void)migrateUpdatesStoreWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019eddb
- (void)hideApplicationBadgeForPendingUpdates;	// IMP=0x001000000019ecad
- (void)getManagedUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019eaed
- (void)getUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019e92d
- (void)getUpdatesMetricsWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019e87d
- (void)getUpdatesIncludingMetricsWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019e6bd
- (void)clearExpiredUpdateHistoryWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019e59e
- (id)init;	// IMP=0x001000000019e56f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

