//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SQLitePredicate : NSObject
{
}

- (_Bool)isEqual:(id)arg1;	// IMP=0x00400000001456b4
- (unsigned long long)hash;	// IMP=0x001000000014569a
- (id)SQLJoinClausesForEntityClass:(Class)arg1;	// IMP=0x0010000000145692
- (id)SQLForEntityClass:(Class)arg1;	// IMP=0x001000000014568a
- (void)applyBinding:(id)arg1 atIndex:(inout int *)arg2;	// IMP=0x0010000000145684
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000145679

@end

