//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface XPCServiceCatalog : NSObject
{
    CDUnknownBlockType _AppStoreServiceProvider;	// 8 = 0x8
    CDUnknownBlockType _diagnosticServiceProvider;	// 16 = 0x10
    CDUnknownBlockType _CrossfireServiceProvider;	// 24 = 0x18
    CDUnknownBlockType _fairPlayServiceProvider;	// 32 = 0x20
    CDUnknownBlockType _IAPHistoryServiceProvider;	// 40 = 0x28
    CDUnknownBlockType _installationServiceProvider;	// 48 = 0x30
    CDUnknownBlockType _libraryServiceProvider;	// 56 = 0x38
    CDUnknownBlockType _MetricsServiceProvider;	// 64 = 0x40
    CDUnknownBlockType _ManagedAppServiceProvider;	// 72 = 0x48
    CDUnknownBlockType _OcelotServiceProvider;	// 80 = 0x50
    CDUnknownBlockType _PurchaseHistoryServiceProvider;	// 88 = 0x58
    CDUnknownBlockType _PurchaseServiceProvider;	// 96 = 0x60
    CDUnknownBlockType _RepairServiceProvider;	// 104 = 0x68
    CDUnknownBlockType _RestoreServiceProvider;	// 112 = 0x70
    CDUnknownBlockType _UpdatesServiceProvider;	// 120 = 0x78
    struct _ASDServiceEntitlement _AppStoreServiceEntitlement;	// 128 = 0x80
    struct _ASDServiceEntitlement _diagnosticServiceEntitlement;	// 144 = 0x90
    struct _ASDServiceEntitlement;	// 160 = 0xa0
    struct _ASDServiceEntitlement _fairPlayEntitlement;	// 176 = 0xb0
    struct _ASDServiceEntitlement _IAPHistoryServiceEntitlement;	// 192 = 0xc0
    struct _ASDServiceEntitlement _installationServiceEntitlement;	// 208 = 0xd0
    struct _ASDServiceEntitlement _libraryServiceEntitlement;	// 224 = 0xe0
    struct _ASDServiceEntitlement _MetricsServiceEntitlement;	// 240 = 0xf0
    struct _ASDServiceEntitlement _ManagedAppServiceEntitlement;	// 256 = 0x100
    struct _ASDServiceEntitlement _OcelotServerEntitlement;	// 272 = 0x110
    struct _ASDServiceEntitlement _PurchaseHistoryServiceEntitlement;	// 288 = 0x120
    struct _ASDServiceEntitlement _PurchaseServiceEntitlement;	// 304 = 0x130
    struct _ASDServiceEntitlement _RepairServiceEntitlement;	// 320 = 0x140
    struct _ASDServiceEntitlement _RestoreServiceEntitlement;	// 336 = 0x150
    struct _ASDServiceEntitlement _UpdatesServiceEntitlement;	// 352 = 0x160
}

- (void).cxx_destruct;	// IMP=0x0020000000094853

@end

