//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDate, NSMutableArray, NSMutableDictionary, NSObject, VCPDatabaseWriter;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface MADPhotosOCRAssetProcessingTask
{
    NSMutableArray *_assetEntries;	// 8 = 0x8
    VCPDatabaseWriter *_analysisDatabase;	// 16 = 0x10
    _Bool _allowDownload;	// 24 = 0x18
    NSObject<OS_dispatch_group> *_downloadGroup;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_downloadStateQueue;	// 40 = 0x28
    NSMutableDictionary *_downloadRequestIDs;	// 48 = 0x30
    NSDate *_downloadStateChange;	// 56 = 0x38
    int _downloadStatus;	// 64 = 0x40
    NSObject<OS_dispatch_group> *_computeGroup;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_computeQueue;	// 80 = 0x50
    int _status;	// 88 = 0x58
}

+ (id)taskWithAnalysisDatabase:(id)arg1;	// IMP=0x004000000006096a
- (void).cxx_destruct;	// IMP=0x0020000000066c92
- (void)publish;	// IMP=0x0010000000066c64
- (int)_publish;	// IMP=0x001000000006597d
- (void)process;	// IMP=0x001000000006594f
- (int)_process;	// IMP=0x0010000000064ca6
- (void)processAssetEntry:(id)arg1 resource:(id)arg2 resourceURL:(id)arg3;	// IMP=0x001000000006392e
- (id)remoteResourceForAsset:(id)arg1 withAcceptableResources:(id)arg2;	// IMP=0x00100000000636bf
- (id)localResourceForAsset:(id)arg1 withAcceptableResources:(id)arg2;	// IMP=0x001000000006353c
- (id)acceptableResourcesForAsset:(id)arg1 withResources:(id)arg2;	// IMP=0x0010000000062ef4
- (void)prepare;	// IMP=0x0010000000062ecd
- (int)_prepare;	// IMP=0x001000000006290f
- (void)download;	// IMP=0x0010000000061892
- (void)cancelRemainingDownloadsWithStatus:(int)arg1;	// IMP=0x001000000006159f
- (double)downloadInactiveTimeInterval;	// IMP=0x0010000000061433
- (int)removeDownloadRequestIDForAsset:(id)arg1;	// IMP=0x001000000006117b
- (void)addDownloadRequestID:(int)arg1 forAsset:(id)arg2;	// IMP=0x0010000000060fe7
- (void)addPhotosAsset:(id)arg1 withPreviousStatus:(unsigned long long)arg2 attempts:(unsigned long long)arg3 andAttemptDate:(id)arg4;	// IMP=0x0010000000060c38
- (int)status;	// IMP=0x0010000000060c28
- (unsigned long long)count;	// IMP=0x0010000000060c0b
- (void)dealloc;	// IMP=0x00100000000609c7
- (id)initWithAnalysisDatabase:(id)arg1;	// IMP=0x00100000000607f8

@end

