//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSISO8601DateFormatter;

@interface BMDateFormatterVendor : NSObject
{
    NSISO8601DateFormatter *_dateFormatter;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x004000000004150d
- (void).cxx_destruct;	// IMP=0x0020000000041570
- (id)dateFormatter;	// IMP=0x0010000000041562
- (id)init;	// IMP=0x00100000000414b7

@end

