//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BMSyncDatabase;

@interface BMSyncDatabaseTransactionBatcher : NSObject
{
    BMSyncDatabase *_database;	// 8 = 0x8
    unsigned long long _batchSize;	// 16 = 0x10
    unsigned long long _currentBatchCount;	// 24 = 0x18
    _Bool _transactionError;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000003f2d4
- (_Bool)markAllOperationsComplete;	// IMP=0x001000000003f28b
- (_Bool)markOperationComplete;	// IMP=0x001000000003f23c
- (_Bool)markOperationStarted;	// IMP=0x001000000003f1fa
- (_Bool)_commitTransaction;	// IMP=0x001000000003f17a
- (_Bool)executeOperationWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000003efe6
- (id)initWithDatabase:(id)arg1 transcationBatchSize:(unsigned long long)arg2;	// IMP=0x001000000003ef6f

@end

