//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemPanelUI/TVSPRendererFormatProvider.h>

@interface CountdownRendererFormatProvider : TVSPRendererFormatProvider
{
}

- (_Bool)isFocusable;	// IMP=0x004000000008dfb0
- (double)cornerRadius;	// IMP=0x001000000008df90
- (id)init;	// IMP=0x001000000008df30

@end

