//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIWindowSceneDelegate-Protocol.h"

@class BSAnimationSettings, NSString, PBSystemUIServiceDismissMenuOptions, PBSystemUIServicePresentMenuOptions, PBSystemUIServiceSystemState, PBSystemUIServiceWindowScene;

@protocol PBSystemUIServiceWindowSceneDelegate <UIWindowSceneDelegate>

@optional
- (void)windowScene:(PBSystemUIServiceWindowScene *)arg1 didReceiveUpdatedSystemState:(PBSystemUIServiceSystemState *)arg2 previousState:(PBSystemUIServiceSystemState *)arg3 withAnimationSettings:(BSAnimationSettings *)arg4;
- (void)windowScene:(PBSystemUIServiceWindowScene *)arg1 playbackControlsStateDidChangeWithAnimationSettings:(BSAnimationSettings *)arg2;
- (void)windowScene:(PBSystemUIServiceWindowScene *)arg1 handleExternalGesture:(NSString *)arg2;
- (void)windowScene:(PBSystemUIServiceWindowScene *)arg1 didReceiveDismissMenuRequestWithOptions:(PBSystemUIServiceDismissMenuOptions *)arg2;
- (void)windowScene:(PBSystemUIServiceWindowScene *)arg1 didReceivePresentMenuRequestWithOptions:(PBSystemUIServicePresentMenuOptions *)arg2;
@end

