//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSLayoutConstraint, UIColor;

@interface TVSSRecordingIndicatorView : UIView
{
    NSLayoutConstraint *_widthConstraint;	// 8 = 0x8
    long long _displayLocation;	// 16 = 0x10
    long long _indicatorShape;	// 24 = 0x18
    unsigned long long _menuMode;	// 32 = 0x20
    UIColor *_indicatorColor;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000010b5e0
@property(retain, nonatomic) UIColor *indicatorColor; // @synthesize indicatorColor=_indicatorColor;
@property(nonatomic) unsigned long long menuMode; // @synthesize menuMode=_menuMode;
@property(nonatomic) long long indicatorShape; // @synthesize indicatorShape=_indicatorShape;
@property(nonatomic) long long displayLocation; // @synthesize displayLocation=_displayLocation;
- (void)_updateWidthConstraint;	// IMP=0x001000000010b4c0
- (_Bool)isOpaque;	// IMP=0x001000000010b2d0
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x001000000010aef0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000010acb0

@end

