//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, UIViewController;
@protocol TVSSBannerPresentable, TVSSMenuModeBannerContextTransitionObserver;

@interface TVSSMenuModeBannerContext : NSObject
{
    _Bool _shouldAnimateTransition;	// 8 = 0x8
    _Bool _supportsInteractiveMode;	// 9 = 0x9
    long long _bannerPresentationState;	// 16 = 0x10
    UIViewController<TVSSBannerPresentable> *_transitioningBannerPresentable;	// 24 = 0x18
    id <TVSSMenuModeBannerContextTransitionObserver> _transitionObserver;	// 32 = 0x20
    NSString *_dismissalReason;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000ec700
@property(readonly, nonatomic) NSString *dismissalReason; // @synthesize dismissalReason=_dismissalReason;
@property(readonly, nonatomic) __weak id <TVSSMenuModeBannerContextTransitionObserver> transitionObserver; // @synthesize transitionObserver=_transitionObserver;
@property(readonly, nonatomic) UIViewController<TVSSBannerPresentable> *transitioningBannerPresentable; // @synthesize transitioningBannerPresentable=_transitioningBannerPresentable;
@property(readonly, nonatomic) _Bool supportsInteractiveMode; // @synthesize supportsInteractiveMode=_supportsInteractiveMode;
@property(readonly, nonatomic) _Bool shouldAnimateTransition; // @synthesize shouldAnimateTransition=_shouldAnimateTransition;
@property(readonly, nonatomic) long long bannerPresentationState; // @synthesize bannerPresentationState=_bannerPresentationState;
- (unsigned long long)hash;	// IMP=0x00100000000ec250
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000ebc40
- (id)debugDescription;	// IMP=0x00100000000ebb60
- (id)description;	// IMP=0x00100000000ebac0
- (id)initWithBannerPresentationState:(long long)arg1 transitioningBannerPresentable:(id)arg2 shouldAnimateTransition:(_Bool)arg3 supportsInteractiveMode:(_Bool)arg4 transitionObserver:(id)arg5 dismissalReason:(id)arg6;	// IMP=0x00100000000eb660
- (id)initWithBannerPresentationState:(long long)arg1;	// IMP=0x00100000000eb5d0
- (id)init;	// IMP=0x00100000000eb570

@end

