//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, TVSSNetworkController;

@interface TVSSNetworkStateMenuItemProvider
{
    TVSSNetworkController *_networkController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000002c1d0
- (id)log;	// IMP=0x001000000002c110
- (id)newMenuItem;	// IMP=0x001000000002c030
- (_Bool)shouldShowMenuItem;	// IMP=0x001000000002bfb0
- (void)networkController:(id)arg1 didChangeNetworkState:(id)arg2;	// IMP=0x001000000002bf30
- (void)dealloc;	// IMP=0x001000000002beb0
- (id)initWithNetworkController:(id)arg1;	// IMP=0x001000000002b8a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

