//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSystemPanelUI/TVSPRenderer.h>

@class UIActivityIndicatorView;

@interface TVSSSubtitleActivityRenderer : TVSPRenderer
{
    UIActivityIndicatorView *_activityIndicatorView;	// 8 = 0x8
}

+ (id)rendererWithIdentifier:(id)arg1 subtitle:(id)arg2;	// IMP=0x0040000000092cb0
- (void).cxx_destruct;	// IMP=0x0020000000093820
- (id)layoutConstraintsWithSubviews:(id)arg1 contentView:(id)arg2;	// IMP=0x0010000000093570
- (void)applyStylingsWithAnimator:(id)arg1;	// IMP=0x0010000000093440
- (void)configureContentView:(id)arg1;	// IMP=0x0010000000092f30
- (id)initWithIdentifier:(id)arg1 format:(long long)arg2 content:(id)arg3 overrideStylings:(id)arg4;	// IMP=0x0010000000092da0

@end

