//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CLBarometerCalibrationAbsoluteAltitude, CLBarometerCalibrationBiasEstimator, CLBarometerCalibrationSourceAggregator, CLElevationThresholdManager, NSMutableArray, NSString;

@interface CLBarometerCalibrationSim : NSObject
{
    array_c343414b fDataBuffers;	// 8 = 0x8
    struct array<CLBarometerCalibrationContextManager *, 10UL> _contextManagers;	// 440 = 0x1b8
    CLBarometerCalibrationSourceAggregator *_sourceAggregator;	// 520 = 0x208
    CLBarometerCalibrationBiasEstimator *_biasEstimator;	// 528 = 0x210
    CLBarometerCalibrationAbsoluteAltitude *_latestAbsoluteAltitude;	// 536 = 0x218
    unsigned int _prevElevationAscended;	// 544 = 0x220
    unsigned int _prevElevationDescended;	// 548 = 0x224
    int _sameElevationCounter;	// 552 = 0x228
    double _lastEstimatedBias;	// 560 = 0x230
    double _lastEstimatedBiasTimestamp;	// 568 = 0x238
    _Bool _currentUnderDEM;	// 576 = 0x240
    _Bool _inVisit;	// 577 = 0x241
    float _fCurrentPressureCalibration;	// 580 = 0x244
    _Bool _fWetState;	// 584 = 0x248
    struct ElevationAlertCurrentBounds _currentElevationThreshold;	// 588 = 0x24c
    CLElevationThresholdManager *_thresholdManager;	// 600 = 0x258
    NSMutableArray *_absoluteAltimeterSimDB;	// 608 = 0x260
    void *_aopAltimeter;	// 616 = 0x268
    _Bool _inOutdoorWorkout;	// 624 = 0x270
    double _lastAltitude;	// 632 = 0x278
    double _lastAltitudeAccuracy;	// 640 = 0x280
    double _lastAltitudeTime;	// 648 = 0x288
}

- (id).cxx_construct;	// IMP=0x0010000000bd4944
- (void).cxx_destruct;	// IMP=0x0010000000bd491c
@property(nonatomic, getter=getLastAltitudeTime) double lastAltitudeTime; // @synthesize lastAltitudeTime=_lastAltitudeTime;
@property(nonatomic, getter=getLastAltitudeAccuracy) double lastAltitudeAccuracy; // @synthesize lastAltitudeAccuracy=_lastAltitudeAccuracy;
@property(nonatomic, getter=getLastAltitude) double lastAltitude; // @synthesize lastAltitude=_lastAltitude;
@property(nonatomic, getter=isInOutdoorWorkout) _Bool inOutdoorWorkout; // @synthesize inOutdoorWorkout=_inOutdoorWorkout;
- (void)unregisterClient:(basic_string_d1f930f6)arg1 forElevationThreshold:(struct CLBarometerCalibrationElevationThreshold)arg2;	// IMP=0x0010000000bd48aa
- (void)registerClient:(basic_string_d1f930f6)arg1 forElevationThreshold:(struct CLBarometerCalibrationElevationThreshold)arg2;	// IMP=0x0010000000bd48a4
- (void)feedSubmersionState:(unsigned char)arg1;	// IMP=0x0010000000bd478c
- (float)getSurfacePressure;	// IMP=0x0010000000bd477e
- (void)surfacePressureCalibrationAtTime:(double)arg1 andPressure:(double)arg2 andLocation:(_Bool)arg3;	// IMP=0x0010000000bd4612
- (void)announceMostRecentForcedGPS:(double)arg1;	// IMP=0x0010000000bd45f9
- (id)latestAbsoluteAltitude;	// IMP=0x0010000000bd45ec
- (_Bool)isInVisit;	// IMP=0x0010000000bd45e0
- (_Bool)feedLoiData:(struct RoutineVisit)arg1;	// IMP=0x0010000000bd42bd
- (void)onMotionStateObserverNotification:(int)arg1 activityType:(int)arg2;	// IMP=0x0010000000bd3e46
- (_Bool)inOutdoorWorkout;	// IMP=0x0010000000bd3e3a
- (void)updateCompanionConnected:(_Bool)arg1;	// IMP=0x0010000000bd3e34
- (void)dealloc;	// IMP=0x0010000000bd3d97
- (void)releaseAndClearManager:(id *)arg1;	// IMP=0x0010000000bd3d62
- (void)releaseContextManagersForNotification:(unsigned long long)arg1;	// IMP=0x0010000000bd3d33
- (void)initContextManagersForNotification:(unsigned long long)arg1;	// IMP=0x0010000000bd3c7e
- (void)updateEstimatedWeatherWithCumulativeAscendingDelta:(unsigned int)arg1 andDescendingDelta:(unsigned int)arg2 andIosTimestamp:(double)arg3;	// IMP=0x0010000000bd3c65
- (void)updateBiasUncertaintyWithPressure:(double)arg1 andTime:(double)arg2 andLat:(double)arg3 andLon:(double)arg4;	// IMP=0x0010000000bd3c4c
- (id)copyCurrentBias;	// IMP=0x0010000000bd3c33
- (void)submersionMeasurementUpdate:(id)arg1;	// IMP=0x0010000000bd3c2d
- (void)submersionStateUpdate:(id)arg1;	// IMP=0x0010000000bd3c27
- (void)alertElevationAlertClientsOnChange;	// IMP=0x0010000000bd3c21
- (void)absoluteAltitudeUpdate:(id)arg1;	// IMP=0x0010000000bd3b66
- (void)stopTrack:(id)arg1;	// IMP=0x0010000000bd3ad4
- (void)startTrack:(id)arg1;	// IMP=0x0010000000bd3ace
- (void)didUpdateDataBuffer:(unsigned long long)arg1;	// IMP=0x0010000000bd3a7f
- (void)feedPrefilteredLocationData:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x0010000000bd381c
- (void)feedLocationData:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x0010000000bd311a
- (void)feedCumulativeAscendingDelta:(unsigned int)arg1 andDescendingDelta:(unsigned int)arg2 andIosTimestamp:(double)arg3;	// IMP=0x0010000000bd3036
- (void)feedPressureKF:(const struct CMKFFilteredPressureSample *)arg1;	// IMP=0x0010000000bd2f3d
- (void)feedPressureData:(const Sample_b71dd899 *)arg1 andTempDerivative:(float)arg2 andWetState:(_Bool)arg3;	// IMP=0x0010000000bd2e03
- (id)initWithAOPAltimeter:(void *)arg1;	// IMP=0x0010000000bd2c70
- (void)updateElevationBiasBetweenStartTime:(double)arg1 andEndTime:(double)arg2 andNextTrackStartTime:(double)arg3;	// IMP=0x0010000000a8b384

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

