//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CLBatchedAccelerometerBufferWrapper : NSObject
{
    struct vector<CMAccel800, std::allocator<CMAccel800>> _buffer;	// 8 = 0x8
}

- (id).cxx_construct;	// IMP=0x002000000084f812
- (void).cxx_destruct;	// IMP=0x001000000084f7f6
- (const void *)buffer;	// IMP=0x001000000084f7ec
- (void)dealloc;	// IMP=0x001000000084f7bd
- (id)initWithMovedBuffer:(void *)arg1;	// IMP=0x001000000084f76b

@end

