//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface CLFallModelSelector : NSObject
{
    NSMutableDictionary *fSelectionFeatures;	// 8 = 0x8
    struct FallModel fTripFallModel;	// 16 = 0x10
    struct FallModel fSlipFallModel;	// 812 = 0x32c
    struct FallModel fOtherFallModel;	// 1608 = 0x648
    struct FallThresholds fThresholds;	// 2404 = 0x964
}

- (id).cxx_construct;	// IMP=0x0020000000215bb4
- (_Bool)fillFallThresholds:(struct FallThresholds *)arg1;	// IMP=0x0010000000215b2f
- (_Bool)fillOtherFallModel:(struct FallModel *)arg1;	// IMP=0x0010000000215900
- (_Bool)fillSlipFallModel:(struct FallModel *)arg1;	// IMP=0x00100000002156d1
- (_Bool)fillTripFallModel:(struct FallModel *)arg1;	// IMP=0x00100000002154ba
- (_Bool)selectModels;	// IMP=0x0010000000213768
- (_Bool)setSelectionFeatureValue:(id)arg1 value:(id)arg2;	// IMP=0x0010000000213746
- (void)dealloc;	// IMP=0x001000000021370b
- (id)init;	// IMP=0x00100000002136c2

@end

