//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLLocationAwarenessProviderAdapter
{
}

+ (id)getSilo;	// IMP=0x0040000000af7a8d
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000af7a74
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000af7a17
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000af7c7a
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000af7c4d
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000af7c25
- (void *)adaptee;	// IMP=0x0010000000af7bf2
- (void)endService;	// IMP=0x0010000000af7bd7
- (void)beginService;	// IMP=0x0010000000af7b26
- (id)init;	// IMP=0x0010000000af7ae9
- (void)onScenarioTrigger:(id)arg1;	// IMP=0x0010000000af7e71

// Remaining properties
// Error: Property attributes should begin with the type ('T') attribute, property name: debugDescription
// Property attributes: (null)

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

