//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface CLStreamedLocationInternal : PBCodable
{
    double _rawCoordinateLatitude;	// 8 = 0x8
    double _rawCoordinateLongitude;	// 16 = 0x10
    struct {
        unsigned int rawCoordinateLatitude:1;
        unsigned int rawCoordinateLongitude:1;
    } _has;	// 24 = 0x18
}

@property(nonatomic) double rawCoordinateLongitude; // @synthesize rawCoordinateLongitude=_rawCoordinateLongitude;
@property(nonatomic) double rawCoordinateLatitude; // @synthesize rawCoordinateLatitude=_rawCoordinateLatitude;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000a1b9c6
- (unsigned long long)hash;	// IMP=0x0010000000a1b7ca
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000a1b73d
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000a1b6b8
- (void)copyTo:(id)arg1;	// IMP=0x0010000000a1b671
- (void)writeTo:(id)arg1;	// IMP=0x0010000000a1b601
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000a1b5f4
- (id)dictionaryRepresentation;	// IMP=0x0010000000a1b356
- (id)description;	// IMP=0x0010000000a1b2df
@property(nonatomic) _Bool hasRawCoordinateLongitude;
@property(nonatomic) _Bool hasRawCoordinateLatitude;
- (void)mergeIntoDaemonLocation:(struct CLDaemonLocation *)arg1;	// IMP=0x001000000069de5b
- (id)initWithDaemonLocation:(const struct CLDaemonLocation *)arg1;	// IMP=0x001000000069dded

@end

