//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class TSKPreviewViewController;

@interface TVSettingsMusicViewController : TSKViewController
{
    TSKPreviewViewController *_appPreviewViewController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000001f647
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x001000000001f5fd
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x001000000001f536
- (id)loadSettingGroups;	// IMP=0x001000000001e4ba
- (void)dealloc;	// IMP=0x001000000001e437
- (id)initWithStyle:(long long)arg1;	// IMP=0x001000000001e3a6

@end

