//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, TSKBoolFormatter;

@interface TVSettingsScreenSaverToggleViewModel : NSObject
{
    _Bool _disabled;	// 8 = 0x8
    NSString *_offIdentifier;	// 16 = 0x10
    NSString *_onIdentifier;	// 24 = 0x18
    TSKBoolFormatter *_toggleFormatter;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000e9a8c
@property(readonly, nonatomic, getter=isDisabled) _Bool disabled; // @synthesize disabled=_disabled;
@property(readonly, nonatomic) TSKBoolFormatter *toggleFormatter; // @synthesize toggleFormatter=_toggleFormatter;
@property(readonly, copy, nonatomic) NSString *onIdentifier; // @synthesize onIdentifier=_onIdentifier;
@property(readonly, copy, nonatomic) NSString *offIdentifier; // @synthesize offIdentifier=_offIdentifier;
- (id)initWithOffSettingsOption:(id)arg1 onSettingsOption:(id)arg2 disabled:(_Bool)arg3;	// IMP=0x00100000000e9905

@end

