//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSFormatter.h>

@interface TVSettingsDisplayResolutionFormatter : NSFormatter
{
}

- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;	// IMP=0x004000000008658e
- (id)stringForObjectValue:(id)arg1;	// IMP=0x0010000000086579

@end

