//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class NSString, TVPiCloudPhotosWelcomeViewController;

@interface TVSettingsScreenSaverTypesViewController : TSKViewController
{
    TVPiCloudPhotosWelcomeViewController *_iCloudWelcomeViewController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000041719
@property(retain, nonatomic) TVPiCloudPhotosWelcomeViewController *iCloudWelcomeViewController; // @synthesize iCloudWelcomeViewController=_iCloudWelcomeViewController;
- (void)turnOnWelcomeSectionType:(long long)arg1;	// IMP=0x00100000000413fb
- (void)_openiCloudPhotosTypesViewControllerAnimated:(_Bool)arg1;	// IMP=0x001000000004138f
- (void)_openSettings;	// IMP=0x001000000004126b
- (void)_goToPhotoSettingsIfPossible;	// IMP=0x0010000000040fc5
- (void)selectedItem:(id)arg1;	// IMP=0x0010000000040dd1
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0010000000040d75
- (id)loadSettingGroups;	// IMP=0x001000000004072a
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00100000000406bc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000040642
- (id)title;	// IMP=0x0010000000040631
- (void)dealloc;	// IMP=0x0010000000040573
- (id)initWithStyle:(long long)arg1;	// IMP=0x001000000004049d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

