//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class TVSettingsVPNConfiguration;

@interface TVSettingsVPNDomainsViewController : TSKViewController
{
    TVSettingsVPNConfiguration *_configuration;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000adcbc
@property(retain, nonatomic) TVSettingsVPNConfiguration *configuration; // @synthesize configuration=_configuration;
- (id)loadSettingGroups;	// IMP=0x00100000000adbaa
- (id)title;	// IMP=0x00100000000adb99
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00100000000adb31

@end

