//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class NSArray, NSString, _TVSettingsImageLoaderQueue;

@interface TVSettingsParadeView : UIView
{
    _Bool _pausedForResignActive;	// 8 = 0x8
    _Bool _paused;	// 9 = 0x9
    _Bool _shuffled;	// 10 = 0xa
    _Bool _inOrder;	// 11 = 0xb
    NSArray *_imageProxies;	// 16 = 0x10
    _TVSettingsImageLoaderQueue *_loaderQueue;	// 24 = 0x18
    NSArray *_shuffledImageProxies;	// 32 = 0x20
    NSArray *_positionKeyframes;	// 40 = 0x28
    NSArray *_depthKeyframes;	// 48 = 0x30
    NSArray *_transformKeyframes;	// 56 = 0x38
    struct CGRect _animationBounds;	// 64 = 0x40
    struct CGRect _maximumImageBounds;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x002000000001d844
@property(retain, nonatomic) NSArray *transformKeyframes; // @synthesize transformKeyframes=_transformKeyframes;
@property(retain, nonatomic) NSArray *depthKeyframes; // @synthesize depthKeyframes=_depthKeyframes;
@property(retain, nonatomic) NSArray *positionKeyframes; // @synthesize positionKeyframes=_positionKeyframes;
@property(nonatomic) struct CGRect maximumImageBounds; // @synthesize maximumImageBounds=_maximumImageBounds;
@property(nonatomic) struct CGRect animationBounds; // @synthesize animationBounds=_animationBounds;
@property(copy, nonatomic) NSArray *shuffledImageProxies; // @synthesize shuffledImageProxies=_shuffledImageProxies;
@property(retain, nonatomic) _TVSettingsImageLoaderQueue *loaderQueue; // @synthesize loaderQueue=_loaderQueue;
@property(nonatomic, getter=isInOrder) _Bool inOrder; // @synthesize inOrder=_inOrder;
@property(nonatomic, getter=isShuffled) _Bool shuffled; // @synthesize shuffled=_shuffled;
@property(nonatomic, getter=isPaused) _Bool paused; // @synthesize paused=_paused;
@property(copy, nonatomic) NSArray *imageProxies; // @synthesize imageProxies=_imageProxies;
- (id)_sublayerWithAnimation:(id)arg1;	// IMP=0x001000000001d575
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;	// IMP=0x001000000001d3e9
- (void)_stopAnimations;	// IMP=0x001000000001d283
- (void)_updateAnimationForLayer:(id)arg1 timeOffset:(double)arg2;	// IMP=0x001000000001caf8
- (void)_updateAnimations;	// IMP=0x001000000001c931
- (void)_updateKeyframes;	// IMP=0x001000000001c604
- (id)_createLayerForImage:(struct CGImage *)arg1;	// IMP=0x001000000001c531
- (id)_imageProxiesToLoad;	// IMP=0x001000000001c503
- (unsigned long long)_maximumImageCount;	// IMP=0x001000000001c4f8
- (_Bool)isPreviewPaused;	// IMP=0x001000000001c42a
- (void)setPreviewPaused:(_Bool)arg1;	// IMP=0x001000000001c418
- (void)_applicationDidFinishSuspensionNotification:(id)arg1;	// IMP=0x001000000001bff6
- (void)_applicationWillEnterForegroundNotification:(id)arg1;	// IMP=0x001000000001bfb1
- (void)didMoveToSuperview;	// IMP=0x001000000001bf68
- (void)layoutSubviews;	// IMP=0x001000000001bea9
- (void)dealloc;	// IMP=0x001000000001bdb1
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000001bb14

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

