//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSOperation.h>

@class NSCondition, NSError, NSMutableArray, NSTimer;

@interface GTFuture_replayer : NSOperation
{
    NSTimer *_timeout;	// 8 = 0x8
    NSCondition *_condition;	// 16 = 0x10
    _Bool _resolved;	// 24 = 0x18
    _Bool _cancelled;	// 25 = 0x19
    id _result;	// 32 = 0x20
    NSError *_error;	// 40 = 0x28
    NSMutableArray *_notifyList;	// 48 = 0x30
    NSMutableArray *_inflightDependencies;	// 56 = 0x38
    _Bool _started;	// 64 = 0x40
    CDUnknownBlockType _completion;	// 72 = 0x48
    long long _priority;	// 80 = 0x50
}

+ (_Bool)logPerformance;	// IMP=0x004000000003f007
+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;	// IMP=0x001000000003ef8f
+ (id)futureWithResult:(id)arg1 error:(id)arg2;	// IMP=0x001000000003ef3e
+ (id)future;	// IMP=0x001000000003ef24
- (id)_dependencies_NOLOCK;	// IMP=0x002000000003eae8
- (_Bool)_waitForDependencies_REQUIRESLOCK;	// IMP=0x001000000003ea5c
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x001000000003e9cd
- (void)_addDependency_REQUIRESLOCK:(id)arg1;	// IMP=0x001000000003e8bf
- (void)notifyGroup:(id)arg1;	// IMP=0x001000000003e7d9
- (void)notifyOnQueue:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x001000000003e6e3
- (void)resolveWithFuture:(id)arg1;	// IMP=0x001000000003e5c6
- (void)timeoutAfter:(double)arg1 label:(id)arg2;	// IMP=0x001000000003e4ea
- (void)setError:(id)arg1;	// IMP=0x001000000003e4d0
- (void)cancel;	// IMP=0x001000000003e420
- (id)error;	// IMP=0x001000000003e3eb
- (void)setResult:(id)arg1;	// IMP=0x001000000003e3d1
- (void)_setResult:(id)arg1 error:(id)arg2 notify_NOLOCK:(_Bool)arg3;	// IMP=0x001000000003e160
- (int)intResult;	// IMP=0x001000000003e116
- (unsigned int)uint32Result;	// IMP=0x001000000003e0cc
- (_Bool)boolResult;	// IMP=0x001000000003e084
- (void)requestResult:(CDUnknownBlockType)arg1;	// IMP=0x001000000003e056
- (void)addResultHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000003def9
- (id)result;	// IMP=0x001000000003dec4
- (void)waitUntilResolved;	// IMP=0x001000000003dc3f
- (void)start;	// IMP=0x001000000003dc2d
- (id)dependencies;	// IMP=0x001000000003dc1b
- (void)addDependency:(id)arg1;	// IMP=0x001000000003dbc6
- (void)waitUntilFinished;	// IMP=0x001000000003db44
- (void)_start_NOLOCK;	// IMP=0x001000000003daaf
- (void)setCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000003da52
- (CDUnknownBlockType)completionBlock;	// IMP=0x001000000003d9ee
- (void)setQueuePriority:(long long)arg1;	// IMP=0x001000000003d99e
- (long long)queuePriority;	// IMP=0x001000000003d94f
- (_Bool)isFinished;	// IMP=0x001000000003d8ec
- (_Bool)isExecuting;	// IMP=0x001000000003d887
- (_Bool)isAsynchronous;	// IMP=0x001000000003d87f
- (_Bool)isCancelled;	// IMP=0x001000000003d830
- (void)dealloc;	// IMP=0x001000000003d6c6
- (id)init;	// IMP=0x001000000003d604

@end

