//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GTReplayFetchThreadgroup
{
    unsigned int _index;	// 8 = 0x8
    CDUnion_afa92939 _dispatchUID;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000000380e
@property(nonatomic) unsigned int index; // @synthesize index=_index;
@property(nonatomic) CDUnion_afa92939 dispatchUID; // @synthesize dispatchUID=_dispatchUID;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000000038c1
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000003816

@end

