//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AMSPushHandler, APSConnection, NSArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface AMSDPushService : NSObject
{
    struct os_unfair_lock_s _connectionLock;	// 8 = 0x8
    NSArray *_classConsumers;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_connectionQueue;	// 24 = 0x18
    NSMutableDictionary *_connections;	// 32 = 0x20
    NSArray *_instanceConsumers;	// 40 = 0x28
    APSConnection *_productionConnection;	// 48 = 0x30
    AMSPushHandler *_pushHandler;	// 56 = 0x38
    NSMutableDictionary *_pushTokens;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_registerTaskQueue;	// 72 = 0x48
    struct MGNotificationTokenStruct *_deviceNameChangedToken;	// 80 = 0x50
}

+ (_Bool)isConnectionEntitled:(id)arg1;	// IMP=0x0020000000034c02
+ (id)sharedService;	// IMP=0x0010000000034bad
- (void).cxx_destruct;	// IMP=0x0020000000039d4c
@property(nonatomic) struct MGNotificationTokenStruct *deviceNameChangedToken; // @synthesize deviceNameChangedToken=_deviceNameChangedToken;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *registerTaskQueue; // @synthesize registerTaskQueue=_registerTaskQueue;
@property(readonly, nonatomic) NSMutableDictionary *pushTokens; // @synthesize pushTokens=_pushTokens;
@property(readonly, nonatomic) AMSPushHandler *pushHandler; // @synthesize pushHandler=_pushHandler;
@property(retain, nonatomic) APSConnection *productionConnection; // @synthesize productionConnection=_productionConnection;
@property(retain, nonatomic) NSArray *instanceConsumers; // @synthesize instanceConsumers=_instanceConsumers;
@property(readonly, nonatomic) NSMutableDictionary *connections; // @synthesize connections=_connections;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *connectionQueue; // @synthesize connectionQueue=_connectionQueue;
@property(readonly, nonatomic) struct os_unfair_lock_s connectionLock; // @synthesize connectionLock=_connectionLock;
@property(retain, nonatomic) NSArray *classConsumers; // @synthesize classConsumers=_classConsumers;
- (id)_startConnectionWithEnvironment:(id)arg1;	// IMP=0x001000000003954d
- (void)_shutDownConnection:(id)arg1 forEnvironment:(id)arg2;	// IMP=0x00100000000394b8
- (id)_postPushTokensWithOptions:(long long)arg1;	// IMP=0x0010000000037784
- (id)_postPushTokensIfNeeded;	// IMP=0x0010000000037770
- (id)_pushTokenForEnvironment:(id)arg1;	// IMP=0x00100000000376f4
- (id)_pushEnvironmentFromBag:(id)arg1;	// IMP=0x0010000000037391
- (id)_pushEnvironmentForAccount:(id)arg1;	// IMP=0x0010000000037332
- (id)_establishConnectionsIfNeeded;	// IMP=0x001000000003658c
- (void)_establishConnectionsAndPostPushTokens;	// IMP=0x001000000003639a
- (id)_connectionForEnvironment:(id)arg1;	// IMP=0x001000000003631e
- (id)_bagForAccount:(id)arg1;	// IMP=0x00100000000362c0
- (id)_sandboxPushAccounts;	// IMP=0x001000000003621f
- (id)_productionPushAccounts;	// IMP=0x0010000000036189
- (void)_deviceNameChanged;	// IMP=0x0010000000035eed
- (void)_bagChanged;	// IMP=0x0010000000035dad
- (void)connectionDidReconnect:(id)arg1;	// IMP=0x0010000000035c74
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;	// IMP=0x001000000003574d
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;	// IMP=0x0010000000035232
- (void)connection:(id)arg1 didChangeConnectedStatus:(_Bool)arg2;	// IMP=0x0010000000035099
- (void)registerTokensIfNeeded;	// IMP=0x0010000000034f59
- (void)registerAllTokens;	// IMP=0x0010000000034c8c
- (void)dealloc;	// IMP=0x0010000000034b67
- (id)init;	// IMP=0x001000000003453d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

