//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionViewLayout.h>

@class NSMutableArray, NSMutableDictionary;
@protocol PBWorkspaceGeometry;

@interface PBAppSwitcherFocusLayout : UICollectionViewLayout
{
    id <PBWorkspaceGeometry> _workspaceGeometry;	// 8 = 0x8
    NSMutableArray *_insertedIndexPaths;	// 16 = 0x10
    NSMutableArray *_deletedIndexPaths;	// 24 = 0x18
    NSMutableDictionary *_finalIndexPathByOriginalIndexPath;	// 32 = 0x20
    long long _numberOfItemsBeforeUpdate;	// 40 = 0x28
    long long _numberOfItems;	// 48 = 0x30
    double _screenHeight;	// 56 = 0x38
    long long _swipeIndex;	// 64 = 0x40
    double _swipeUpOffset;	// 72 = 0x48
}

+ (double)contentOffsetAdjustmentForLastItem;	// IMP=0x00400000001a768d
+ (Class)invalidationContextClass;	// IMP=0x00100000001a74f4
+ (Class)layoutAttributesClass;	// IMP=0x00100000001a74d2
- (void).cxx_destruct;	// IMP=0x00200000001a89ee
@property(readonly, nonatomic) double swipeUpOffset; // @synthesize swipeUpOffset=_swipeUpOffset;
@property(readonly, nonatomic) long long swipeIndex; // @synthesize swipeIndex=_swipeIndex;
@property(readonly, nonatomic) double screenHeight; // @synthesize screenHeight=_screenHeight;
@property(readonly, nonatomic) long long numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(readonly, nonatomic) long long numberOfItemsBeforeUpdate; // @synthesize numberOfItemsBeforeUpdate=_numberOfItemsBeforeUpdate;
@property(readonly, copy, nonatomic) NSMutableDictionary *finalIndexPathByOriginalIndexPath; // @synthesize finalIndexPathByOriginalIndexPath=_finalIndexPathByOriginalIndexPath;
@property(readonly, copy, nonatomic) NSMutableArray *deletedIndexPaths; // @synthesize deletedIndexPaths=_deletedIndexPaths;
@property(readonly, copy, nonatomic) NSMutableArray *insertedIndexPaths; // @synthesize insertedIndexPaths=_insertedIndexPaths;
@property(readonly, nonatomic) id <PBWorkspaceGeometry> workspaceGeometry; // @synthesize workspaceGeometry=_workspaceGeometry;
- (double)_scrollProgress;	// IMP=0x00100000001a888c
- (id)_attributesForIndexPath:(id)arg1 scrollProgress:(double)arg2 swipeOffset:(double)arg3 swipeIndex:(long long)arg4 allowMask:(_Bool)arg5;	// IMP=0x00100000001a8119
- (void)finalizeCollectionViewUpdates;	// IMP=0x00100000001a809f
- (void)prepareForCollectionViewUpdates:(id)arg1;	// IMP=0x00100000001a7cc6
- (void)invalidateLayoutWithContext:(id)arg1;	// IMP=0x00100000001a7b6a
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;	// IMP=0x00100000001a7a1f
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;	// IMP=0x00100000001a7948
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x00100000001a78da
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x00100000001a76a7
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;	// IMP=0x00100000001a7592
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;	// IMP=0x00100000001a756f
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x00100000001a7567
- (struct CGSize)collectionViewContentSize;	// IMP=0x00100000001a7516
- (id)initWithWorkspaceGeometry:(id)arg1;	// IMP=0x00100000001a73b9

@end

