//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, UISApplicationSupportService;

@interface PBApplicationSupportServiceDelegate : NSObject
{
    UISApplicationSupportService *_service;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000fb0f2
@property(readonly, nonatomic) UISApplicationSupportService *service; // @synthesize service=_service;
- (void)destroyScenesWithPersistentIdentifiers:(id)arg1 animationType:(unsigned long long)arg2 destroySessions:(_Bool)arg3 forClient:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00100000000fadbd
- (id)service:(id)arg1 initializeClient:(id)arg2;	// IMP=0x00100000000fa841
- (void)requestPasscodeUnlockUIForClient:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000fa7ae
- (id)init;	// IMP=0x00100000000fa6d7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

