//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BSServiceConnectionListener, NSString, PBSXPCServiceConfiguration;

@interface PBBasicServiceListener : NSObject
{
    BSServiceConnectionListener *_listener;	// 8 = 0x8
    PBSXPCServiceConfiguration *_configuration;	// 16 = 0x10
    CDUnknownBlockType _serviceBuilder;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000128283
@property(copy, nonatomic) CDUnknownBlockType serviceBuilder; // @synthesize serviceBuilder=_serviceBuilder;
@property(retain, nonatomic) PBSXPCServiceConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) BSServiceConnectionListener *listener; // @synthesize listener=_listener;
- (_Bool)_checkEntitlementsForProcess:(id)arg1;	// IMP=0x00100000001281bc
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;	// IMP=0x0010000000127d8e
- (void)invalidate;	// IMP=0x0010000000127cf8
- (void)activate;	// IMP=0x0010000000127b70
- (id)initWithConfiguration:(id)arg1 serviceBuilder:(CDUnknownBlockType)arg2;	// IMP=0x0010000000127acb
- (void)dealloc;	// IMP=0x0010000000127a1a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

