//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class NSString, PBMediaPlayerView, PBSHeadphoneBannerRequest, UIImageView;
@protocol BNPresentableContext;

@interface PBHeadphoneBannerViewController : UIViewController
{
    PBSHeadphoneBannerRequest *_request;	// 8 = 0x8
    PBMediaPlayerView *_mediaPlayerView;	// 16 = 0x10
    UIImageView *_imageView;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000012ad82
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) PBMediaPlayerView *mediaPlayerView; // @synthesize mediaPlayerView=_mediaPlayerView;
@property(retain, nonatomic) PBSHeadphoneBannerRequest *request; // @synthesize request=_request;
- (void)presentableDidDisappearAsBanner:(id)arg1 withReason:(id)arg2;	// IMP=0x001000000012acf2
@property(readonly, nonatomic) UIViewController *viewController;
- (_Bool)providesHostedContent;	// IMP=0x001000000012ace1
@property(readonly, copy, nonatomic) NSString *requesterIdentifier;
@property(readonly, copy, nonatomic) NSString *requestIdentifier;
- (void)viewDidLoad;	// IMP=0x001000000012a52c
- (id)initWithRequest:(id)arg1;	// IMP=0x001000000012a4ba

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic, getter=isDraggingDismissalEnabled) _Bool draggingDismissalEnabled;
@property(readonly, nonatomic, getter=isDraggingInteractionEnabled) _Bool draggingInteractionEnabled;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long presentableBehavior;
@property(nonatomic) __weak id <BNPresentableContext> presentableContext;
@property(readonly, nonatomic) long long presentableType;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isTouchOutsideDismissalEnabled) _Bool touchOutsideDismissalEnabled;

@end

