//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@protocol PBSplitViewInwardSizing <NSObject>
@property(nonatomic) struct UIEdgeInsets safeAreaInsets;
- (void)setSafeAreaInsetBottom:(double)arg1;
- (void)setSafeAreaInsetTop:(double)arg1;
@end

