//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TelephonyUtilities/TUCallCenter.h>

@interface TUCallCenter (PineBoard)
+ (_Bool)isCurrentJoinedConservationGroupFaceTime;	// IMP=0x001000000002657b
@end

