//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString, RPNearFieldMessagePayload;

@interface RPTransportServiceHandoverMessage : NSObject
{
    NSString *_version;	// 8 = 0x8
    NSString *_applicationLabel;	// 16 = 0x10
    RPNearFieldMessagePayload *_payload;	// 24 = 0x18
    NSArray *_transportServicesMetadata;	// 32 = 0x20
}

+ (id)messageWithMetadata:(id)arg1 applicationLabel:(id)arg2 payload:(id)arg3 version:(id)arg4;	// IMP=0x0040000000065ac0
- (void).cxx_destruct;	// IMP=0x0020000000066024
@property(readonly, nonatomic) NSArray *transportServicesMetadata; // @synthesize transportServicesMetadata=_transportServicesMetadata;
@property(readonly, nonatomic) RPNearFieldMessagePayload *payload; // @synthesize payload=_payload;
@property(readonly, nonatomic) NSString *applicationLabel; // @synthesize applicationLabel=_applicationLabel;
@property(readonly, nonatomic) NSString *version; // @synthesize version=_version;
- (id)descriptionWithLevel:(int)arg1;	// IMP=0x0010000000065d1d
- (id)description;	// IMP=0x0010000000065d06
- (id)transportServicesMetadataDictionaryRepresentation;	// IMP=0x0010000000065b6d
- (id)initWithMetadata:(id)arg1 applicationLabel:(id)arg2 payload:(id)arg3 version:(id)arg4;	// IMP=0x00100000000659bf

@end

