//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface RMStoreHelper : NSObject
{
}

+ (_Bool)isSingletonStoreType:(long long)arg1;	// IMP=0x0040000000098268
+ (_Bool)isInteractiveStoreType:(long long)arg1;	// IMP=0x001000000009825c
+ (_Bool)isDataSeparatedStoreForManagementSource:(id)arg1;	// IMP=0x00100000000981a8
+ (long long)storeScope;	// IMP=0x001000000009819d
+ (id)descriptorForStoreType:(long long)arg1;	// IMP=0x001000000009817e

@end

