//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDDisableLostModeOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000003b916
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000003b8e4

@end

