//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <DeviceManagement/DMFDevice.h>

@interface DMDDeviceController : DMFDevice
{
}

+ (id)shared;	// IMP=0x002000000003ad67
- (id)deviceType;	// IMP=0x002000000003b0e1
- (id)deviceWithKeys:(id)arg1;	// IMP=0x001000000003ae3a
@property(readonly, nonatomic) DMFDevice *currentDevice;

@end

