//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDDeactivateConfigurationOrganizationOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000039a65
+ (id)requiredEntitlements;	// IMP=0x001000000003992e
+ (id)whitelistedClassesForRequest;	// IMP=0x00100000000398fc
- (void)runWithRequest:(id)arg1;	// IMP=0x0040000000039946
- (unsigned long long)queueGroup;	// IMP=0x001000000003993b

@end

