//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AWDSupportFramework/AWDCoreRoutineLMPScoreBoard.h>

@class NSString;

@interface AWDCoreRoutineLMPScoreBoard (MetricManager)
@property(readonly, copy) NSString *description;
- (_Bool)valid:(id *)arg1;	// IMP=0x00200000000fc4a6
- (id)_init;	// IMP=0x00200000000fc477
- (long long)metricId;	// IMP=0x00200000000fc46c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

