//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GeoServices/GEONavigationGuidanceState.h>

@interface GEONavigationGuidanceState (RTNavigationManagerExtension)
- (id)description;	// IMP=0x006000000041551a
@end

