//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreData/NSFetchRequest.h>

@interface NSFetchRequest (RTExtensions)
+ (id)boundingBoxPredicatesForLocation:(id)arg1 distance:(double)arg2 locationProperties:(id)arg3 error:(id *)arg4;	// IMP=0x00600000000f9493
+ (id)formatStringForPropertyPath:(id)arg1;	// IMP=0x00600000000f936f
+ (id)locationPropertiesForEntityName:(id)arg1;	// IMP=0x00600000000f897e
- (_Bool)setupBoundingBoxFetchRequestForLocation:(id)arg1 distance:(double)arg2 entityCanBeLocationShifted:(_Bool)arg3 locationShifter:(id)arg4 resultExpansionPredicates:(id)arg5 resultFilteringPredicates:(id)arg6 error:(id *)arg7;	// IMP=0x00100000000f9ca1
@end

