//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreRoutine/RTLocationOfInterestVisit.h>

@class NSString;

@interface RTLocationOfInterestVisit (RTCoreDataTransformable)
+ (id)createWithLearnedLocationOfInterestVisitMO:(id)arg1;	// IMP=0x00100000001740a7
+ (id)createWithManagedObject:(id)arg1;	// IMP=0x0010000000173f7f
- (id)initWithLearnedVisit:(id)arg1;	// IMP=0x001000000047ac49

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

