//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SafetyMonitor/SMSessionManagerState.h>

@class NSString;

@interface SMSessionManagerState (RTCoreDataTransformable)
+ (id)createWithSMSessionManagerStateMO:(id)arg1;	// IMP=0x00100000003c4e0f
+ (id)createWithManagedObject:(id)arg1;	// IMP=0x00100000003c4ce7
- (id)managedObjectWithContext:(id)arg1;	// IMP=0x00100000003c53f7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

