//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MISSING_TYPE, NSUUID;

@protocol DDDevicePickerContentPresenter <NSObject>
- (MISSING_TYPE *)sendClientDebugError: /* Error: Ran out of types for this method. */;
- (void)didSucceedWithEndpointUUID:(NSUUID *)arg1 agentUUID:(NSUUID *)arg2;
- (void)devicePickerDidCancelWithReason:(long long)arg1;
@end

