//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GKAcceptedInviteManager, NSMutableDictionary, NSString;
@protocol PBSBulletinServiceInterface;

@interface GKBulletinController : NSObject
{
    NSMutableDictionary *_bulletins;	// 8 = 0x8
    GKAcceptedInviteManager *_acceptedInviteManager;	// 16 = 0x10
    NSString *_defaultSoundPath;	// 24 = 0x18
    id <PBSBulletinServiceInterface> _bulletinServiceProxy;	// 32 = 0x20
}

+ (id)sharedController;	// IMP=0x00200000001cafce
+ (void)startBulletinController;	// IMP=0x00100000001cac96
+ (id)bulletinQueue;	// IMP=0x00100000001c8468
- (void).cxx_destruct;	// IMP=0x00100000001ceebf
@property(retain, nonatomic) id <PBSBulletinServiceInterface> bulletinServiceProxy; // @synthesize bulletinServiceProxy=_bulletinServiceProxy;
@property(retain) NSString *defaultSoundPath; // @synthesize defaultSoundPath=_defaultSoundPath;
@property(retain) GKAcceptedInviteManager *acceptedInviteManager; // @synthesize acceptedInviteManager=_acceptedInviteManager;
@property(retain, nonatomic) NSMutableDictionary *bulletins; // @synthesize bulletins=_bulletins;
- (void)bulletinService:(id)arg1 didDismissBulletin:(id)arg2 withReason:(unsigned long long)arg3;	// IMP=0x00100000001ce11b
- (id)callAction:(id)arg1 forBulletinDictionary:(id)arg2;	// IMP=0x00100000001cdb1f
- (void)clearBulletin:(id)arg1;	// IMP=0x00100000001cd863
- (void)removeAllBulletins;	// IMP=0x00100000001cd467
- (void)expireBulletin:(id)arg1;	// IMP=0x00100000001cd1ab
- (void)withdrawBulletin:(id)arg1;	// IMP=0x00100000001cceef
- (void)presentBulletin:(id)arg1;	// IMP=0x00100000001cc6d4
- (id)bulletinFromGKBulletin:(id)arg1;	// IMP=0x00100000001cbee6
- (void)launchBulletin:(id)arg1;	// IMP=0x00100000001cb50d
- (id)init;	// IMP=0x00100000001cb1b0
- (void)dealloc;	// IMP=0x00100000001cb16c
- (void)clearChallengeBulletinsForChallengeID:(id)arg1;	// IMP=0x00100000001ca60c
- (void)clearTurnBasedBulletinsForMatchID:(id)arg1;	// IMP=0x00100000001ca386
- (void)loadBulletins;	// IMP=0x00100000001c9509
- (void)updateSavedBulletins;	// IMP=0x00100000001c8e0c
- (void)clearSavedBulletins;	// IMP=0x00100000001c8799
- (id)bulletinStorageFilePathForEnvironment:(long long)arg1;	// IMP=0x00100000001c8608
- (id)getBulletinsOfType:(Class)arg1;	// IMP=0x00100000001c8136

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

