//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKChallengeReceivedBulletin
{
}

+ (void)loadBulletinsForPushNotification:(id)arg1 withHandler:(CDUnknownBlockType)arg2;	// IMP=0x00400000001bce72
- (void)handleDeclineAction;	// IMP=0x00400000001be7fb
- (void)handleAction:(id)arg1;	// IMP=0x00100000001be4de
- (unsigned long long)launchEventType;	// IMP=0x00100000001be4d6
- (void)assembleBulletin;	// IMP=0x00100000001bdf61
- (void)notifyClient:(id)arg1;	// IMP=0x00100000001bddb9
- (id)init;	// IMP=0x00100000001bce43

@end

