//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSService, NSMutableArray;

@interface GKFireworksPseudonymManager : NSObject
{
    _Bool _inFlightProvision;	// 8 = 0x8
    IDSService *_service;	// 16 = 0x10
    NSMutableArray *_provisionBlocks;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000010dd6d
@property(retain, nonatomic) NSMutableArray *provisionBlocks; // @synthesize provisionBlocks=_provisionBlocks;
@property(nonatomic) _Bool inFlightProvision; // @synthesize inFlightProvision=_inFlightProvision;
@property(retain, nonatomic) IDSService *service; // @synthesize service=_service;
- (void)rollPseudonyms;	// IMP=0x001000000010d609
- (void)provisionPseudonymIfNeeded:(CDUnknownBlockType)arg1;	// IMP=0x001000000010c80f
- (id)initWithService:(id)arg1;	// IMP=0x000000000010c70a

@end

