//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKNWDatagramConnectionWrapper
{
}

- (void)readData;	// IMP=0x004000000016bac3
- (void)_sendData:(id)arg1;	// IMP=0x001000000016b7a0
- (id)initWithDatagramConnection:(id)arg1 connectionID:(id)arg2 delegate:(id)arg3 delegateQueue:(id)arg4;	// IMP=0x001000000016b6b9

@end

