//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/SwiftNativeNSObject.h>

@class MISSING_TYPE, NSData, NSDictionary, NSString;

@interface GKPeerDiscovery : SwiftNativeNSObject
{
    MISSING_TYPE *$defaultActor;	// 4277009103 = 0xfeedfacf
    MISSING_TYPE *delegate;	// 112 = 0x70
    MISSING_TYPE *browser;	// 120 = 0x78
    MISSING_TYPE *listener;	// 128 = 0x80
    MISSING_TYPE *localPlayerID;	// 136 = 0x88
    MISSING_TYPE *localPushToken;	// 152 = 0x98
    MISSING_TYPE *pendingInboundConnections;	// 168 = 0xa8
    MISSING_TYPE *acceptedInBoundConnections;	// 176 = 0xb0
    MISSING_TYPE *outboundConnections;	// 184 = 0xb8
}

- (id)init;	// IMP=0x00200000001d5075
- (void)sendDataToParticipant:(NSString *)arg1 deviceID:(NSString *)arg2 data:(NSData *)arg3 completionHandler:(void (^)(NSError *))arg4;	// IMP=0x00100000001d4dd6
- (void)stopListeningWithCompletionHandler:(void (^)(void))arg1;	// IMP=0x00100000001d471a
- (void)startListening:(NSDictionary *)arg1 completionHandler:(void (^)(void))arg2;	// IMP=0x00100000001d45a8
- (void)stopBrowsingWithCompletionHandler:(void (^)(void))arg1;	// IMP=0x00100000001d393c
- (void)startBrowsingWithCompletionHandler:(void (^)(void))arg1;	// IMP=0x00100000001d38bf
- (id)initWithDelegate:(id)arg1 localPlayerID:(id)arg2 localPushToken:(id)arg3;	// IMP=0x00100000001d32ee

@end

