//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CCDError : NSObject
{
}

+ (id)cleanNSError:(id)arg1;	// IMP=0x0040000000007446
+ (id)_cloudConfigErrorResponses;	// IMP=0x0010000000007158
+ (id)cloudConfigErrorInResponse:(id)arg1;	// IMP=0x00100000000070d8
+ (id)_errorStringForResponse:(id)arg1;	// IMP=0x0010000000006fa6
+ (id)nonceExpiredError;	// IMP=0x0010000000006ee9
+ (id)deviceNotEnrolledError;	// IMP=0x0010000000006e2c
+ (id)deviceAlreadyEnrolledError;	// IMP=0x0010000000006d6f
+ (id)deviceNotFoundError;	// IMP=0x0010000000006cb2
+ (id)profileNotFoundError;	// IMP=0x0010000000006bf5
+ (id)profileNotActiveError;	// IMP=0x0010000000006b38
+ (id);	// IMP=0x0010000000006a7b
+ (id)invalidSignatureError;	// IMP=0x00100000000069be
+ (id)serverTrustError;	// IMP=0x0010000000006901
+ (id)serviceBusyError;	// IMP=0x0010000000006844
+ (id)teslaServiceDownError;	// IMP=0x0010000000006787
+ (id)invalidDeviceError;	// IMP=0x00100000000066ca
+ (id)maxRetriesExceededErrorWithUnderlyingError:(id)arg1;	// IMP=0x00100000000064eb
+ (id)badFormatError;	// IMP=0x001000000000642e
+ (id)internalErrorWithCode:(long long)arg1;	// IMP=0x0010000000006367
+ (id)errorWithDomain:(id)arg1 code:(long long)arg2 description:(id)arg3 errorType:(id)arg4;	// IMP=0x00100000000061c3

@end

