//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CCDFeatures : NSObject
{
}

+ (id)depResponseDataFromData:(id)arg1;	// IMP=0x0020000000007ba5
+ (id)depResponseContentTypeFromContentType:(id)arg1;	// IMP=0x0010000000007b47
+ (id)depRemoveEnrollmentURLStringWithURLString:(id)arg1;	// IMP=0x0010000000007ad7
+ (id)depProvisionalEnrollmentURLStringWithURLString:(id)arg1;	// IMP=0x0010000000007a67
+ (id)depDeviceSerialNumberWithValue:(id)arg1;	// IMP=0x00100000000079f7
+ (id)depConfigurationEnrollmentURLStringWithURLString:(id)arg1;	// IMP=0x0010000000007981
+ (_Bool)sentinelExistsAtPath:(id)arg1;	// IMP=0x00100000000078f9
+ (id)stringForDefaultsKey:(id)arg1;	// IMP=0x0010000000007865
+ (_Bool)isAppleInternal;	// IMP=0x0010000000007854

@end

