//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface MockAKSOptionalParameters : PBCodable
{
    NSData *_accessGroups;	// 8 = 0x8
    NSData *_acmHandle;	// 16 = 0x10
    NSData *_externalData;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000000f5af
@property(retain, nonatomic) NSData *acmHandle; // @synthesize acmHandle=_acmHandle;
@property(retain, nonatomic) NSData *externalData; // @synthesize externalData=_externalData;
@property(retain, nonatomic) NSData *accessGroups; // @synthesize accessGroups=_accessGroups;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000000f4bd
- (unsigned long long)hash;	// IMP=0x001000000000f450
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000f370
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000f2ac
- (void)copyTo:(id)arg1;	// IMP=0x001000000000f229
- (void)writeTo:(id)arg1;	// IMP=0x001000000000f1af
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000f023
- (id)dictionaryRepresentation;	// IMP=0x001000000000ef79
- (id)description;	// IMP=0x001000000000eeca
@property(readonly, nonatomic) _Bool hasAcmHandle;
@property(readonly, nonatomic) _Bool hasExternalData;
@property(readonly, nonatomic) _Bool hasAccessGroups;

@end

