//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CKAccountInfo, CKKSCondition, CKKSKeychainView, CKKSLockStateTracker, CKKSNearFutureScheduler, CuttlefishXPCWrapper, NSData, NSOperationQueue, NSString, OTAccountSettings, OTCustodianRecoveryKey, OTCuttlefishAccountStateHolder, OTFollowup, OTInheritanceKey, OctagonAPSReceiver, OctagonStateMachine, SecLaunchSequence, TPPolicyVersion, TPSpecificUser;
@protocol CKKSCloudKitAccountStateTrackingProvider><CKKSOctagonStatusMemoizer, CKKSPeerProvider, OS_dispatch_queue, OTAccountsAdapter, OTAuthKitAdapter, OTDeviceInformationAdapter, OTPersonaAdapter, OTSOSAdapter, OTTapToRadarAdapter, OTTooManyPeersAdapter;

@interface OTCuttlefishContext : NSObject
{
    NSString *_bottleID;	// 8 = 0x8
    NSString *_bottleSalt;	// 16 = 0x10
    NSData *_entropy;	// 24 = 0x18
    long long _resetReason;	// 32 = 0x20
    NSString *_idmsTargetContext;	// 40 = 0x28
    NSString *_idmsCuttlefishPassword;	// 48 = 0x30
    _Bool _notifyIdMS;	// 56 = 0x38
    OTAccountSettings *_accountSettings;	// 64 = 0x40
    _Bool _skipRateLimitingCheck;	// 72 = 0x48
    _Bool _repair;	// 73 = 0x49
    _Bool _initialBecomeUntrustedPosted;	// 74 = 0x4a
    CuttlefishXPCWrapper *_cuttlefishXPCWrapper;	// 80 = 0x50
    OTFollowup *_followupHandler;	// 88 = 0x58
    NSString *_containerName;	// 96 = 0x60
    NSString *_contextID;	// 104 = 0x68
    TPSpecificUser *_activeAccount;	// 112 = 0x70
    NSString *_pairingUUID;	// 120 = 0x78
    CKKSLockStateTracker *_lockStateTracker;	// 128 = 0x80
    OTCuttlefishAccountStateHolder *_accountMetadataStore;	// 136 = 0x88
    OctagonStateMachine *_stateMachine;	// 144 = 0x90
    CKKSNearFutureScheduler *_apsRateLimiter;	// 152 = 0x98
    CKKSNearFutureScheduler *_sosConsistencyRateLimiter;	// 160 = 0xa0
    CKKSKeychainView *_ckks;	// 168 = 0xa8
    id <CKKSCloudKitAccountStateTrackingProvider><CKKSOctagonStatusMemoizer> _accountStateTracker;	// 176 = 0xb0
    id <OTDeviceInformationAdapter> _deviceAdapter;	// 184 = 0xb8
    id <OTAccountsAdapter> _accountsAdapter;	// 192 = 0xc0
    id <OTAuthKitAdapter> _authKitAdapter;	// 200 = 0xc8
    id <OTPersonaAdapter> _personaAdapter;	// 208 = 0xd0
    id <OTSOSAdapter> _sosAdapter;	// 216 = 0xd8
    id <OTTooManyPeersAdapter> _tooManyPeersAdapter;	// 224 = 0xe0
    id <OTTapToRadarAdapter> _tapToRadarAdapter;	// 232 = 0xe8
    CKKSCondition *_pendingEscrowCacheWarmup;	// 240 = 0xf0
    NSObject<OS_dispatch_queue> *_queue;	// 248 = 0xf8
    TPPolicyVersion *_policyOverride;	// 256 = 0x100
    SecLaunchSequence *_launchSequence;	// 264 = 0x108
    NSOperationQueue *_operationQueue;	// 272 = 0x110
    CKAccountInfo *_cloudKitAccountInfo;	// 280 = 0x118
    CKKSCondition *_cloudKitAccountStateKnown;	// 288 = 0x120
    CKKSNearFutureScheduler *_suggestTLKUploadNotifier;	// 296 = 0x128
    CKKSNearFutureScheduler *_requestPolicyCheckNotifier;	// 304 = 0x130
    CKKSNearFutureScheduler *_upgradeUserControllableViewsRateLimiter;	// 312 = 0x138
    CKKSNearFutureScheduler *_fixupRetryScheduler;	// 320 = 0x140
    NSString *_recoveryKey;	// 328 = 0x148
    OTCustodianRecoveryKey *_custodianRecoveryKey;	// 336 = 0x150
    OTInheritanceKey *_inheritanceKey;	// 344 = 0x158
    OctagonAPSReceiver *_apsReceiver;	// 352 = 0x160
    id <CKKSPeerProvider> _octagonAdapter;	// 360 = 0x168
    Class _escrowRequestClass;	// 368 = 0x170
    Class _notifierClass;	// 376 = 0x178
    NSString *_machineID;	// 384 = 0x180
}

- (void).cxx_destruct;	// IMP=0x00200000000df416
@property(retain, nonatomic) NSString *machineID; // @synthesize machineID=_machineID;
@property(nonatomic) _Bool initialBecomeUntrustedPosted; // @synthesize initialBecomeUntrustedPosted=_initialBecomeUntrustedPosted;
@property(readonly) Class notifierClass; // @synthesize notifierClass=_notifierClass;
@property(readonly) Class escrowRequestClass; // @synthesize escrowRequestClass=_escrowRequestClass;
@property(retain) id <CKKSPeerProvider> octagonAdapter; // @synthesize octagonAdapter=_octagonAdapter;
@property(retain) OctagonAPSReceiver *apsReceiver; // @synthesize apsReceiver=_apsReceiver;
@property(retain, nonatomic) OTInheritanceKey *inheritanceKey; // @synthesize inheritanceKey=_inheritanceKey;
@property(retain, nonatomic) OTCustodianRecoveryKey *custodianRecoveryKey; // @synthesize custodianRecoveryKey=_custodianRecoveryKey;
@property(retain, nonatomic) NSString *recoveryKey; // @synthesize recoveryKey=_recoveryKey;
@property(retain) CKKSNearFutureScheduler *fixupRetryScheduler; // @synthesize fixupRetryScheduler=_fixupRetryScheduler;
@property(retain) CKKSNearFutureScheduler *upgradeUserControllableViewsRateLimiter; // @synthesize upgradeUserControllableViewsRateLimiter=_upgradeUserControllableViewsRateLimiter;
@property(retain) CKKSNearFutureScheduler *requestPolicyCheckNotifier; // @synthesize requestPolicyCheckNotifier=_requestPolicyCheckNotifier;
@property(retain) CKKSNearFutureScheduler *suggestTLKUploadNotifier; // @synthesize suggestTLKUploadNotifier=_suggestTLKUploadNotifier;
@property(retain) CKKSCondition *cloudKitAccountStateKnown; // @synthesize cloudKitAccountStateKnown=_cloudKitAccountStateKnown;
@property(retain) CKAccountInfo *cloudKitAccountInfo; // @synthesize cloudKitAccountInfo=_cloudKitAccountInfo;
@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain) SecLaunchSequence *launchSequence; // @synthesize launchSequence=_launchSequence;
@property(retain) TPPolicyVersion *policyOverride; // @synthesize policyOverride=_policyOverride;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain) CKKSCondition *pendingEscrowCacheWarmup; // @synthesize pendingEscrowCacheWarmup=_pendingEscrowCacheWarmup;
@property(readonly) id <OTTapToRadarAdapter> tapToRadarAdapter; // @synthesize tapToRadarAdapter=_tapToRadarAdapter;
@property(readonly) id <OTTooManyPeersAdapter> tooManyPeersAdapter; // @synthesize tooManyPeersAdapter=_tooManyPeersAdapter;
@property(readonly) id <OTSOSAdapter> sosAdapter; // @synthesize sosAdapter=_sosAdapter;
@property(readonly) id <OTPersonaAdapter> personaAdapter; // @synthesize personaAdapter=_personaAdapter;
@property(readonly) id <OTAuthKitAdapter> authKitAdapter; // @synthesize authKitAdapter=_authKitAdapter;
@property(readonly) id <OTAccountsAdapter> accountsAdapter; // @synthesize accountsAdapter=_accountsAdapter;
@property(readonly) id <OTDeviceInformationAdapter> deviceAdapter; // @synthesize deviceAdapter=_deviceAdapter;
@property(readonly) id <CKKSCloudKitAccountStateTrackingProvider><CKKSOctagonStatusMemoizer> accountStateTracker; // @synthesize accountStateTracker=_accountStateTracker;
@property(retain) CKKSKeychainView *ckks; // @synthesize ckks=_ckks;
@property(retain, nonatomic) CKKSNearFutureScheduler *sosConsistencyRateLimiter; // @synthesize sosConsistencyRateLimiter=_sosConsistencyRateLimiter;
@property(retain, nonatomic) CKKSNearFutureScheduler *apsRateLimiter; // @synthesize apsRateLimiter=_apsRateLimiter;
@property(readonly) OctagonStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) OTCuttlefishAccountStateHolder *accountMetadataStore; // @synthesize accountMetadataStore=_accountMetadataStore;
@property(readonly, nonatomic) CKKSLockStateTracker *lockStateTracker; // @synthesize lockStateTracker=_lockStateTracker;
@property(retain, nonatomic) NSString *pairingUUID; // @synthesize pairingUUID=_pairingUUID;
@property(retain) TPSpecificUser *activeAccount; // @synthesize activeAccount=_activeAccount;
@property(readonly) NSString *contextID; // @synthesize contextID=_contextID;
@property(readonly) NSString *containerName; // @synthesize containerName=_containerName;
@property(retain) OTFollowup *followupHandler; // @synthesize followupHandler=_followupHandler;
@property(readonly) CuttlefishXPCWrapper *cuttlefishXPCWrapper; // @synthesize cuttlefishXPCWrapper=_cuttlefishXPCWrapper;
- (void)setAccountSettings:(id)arg1;	// IMP=0x00100000000def9c
- (_Bool)checkAllStateCleared;	// IMP=0x00100000000deeb2
- (void)clearContextState;	// IMP=0x00100000000dee0c
- (void)getAccountMetadataWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00100000000deccd
- (void)rpcResetAccountCDPContentsWithIdmsTargetContext:(id)arg1 idmsCuttlefishPassword:(id)arg2 notifyIdMS:(_Bool)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x00100000000deaee
- (id)egoPeerStatus:(id *)arg1;	// IMP=0x00100000000de948
- (_Bool)machineIDOnMemoizedList:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000de780
- (void)waitForOctagonUpgrade:(CDUnknownBlockType)arg1;	// IMP=0x00100000000ddf63
- (void)checkOctagonHealth:(_Bool)arg1 repair:(_Bool)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00100000000dd7c5
- (_Bool)processMoveRequest:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000dd044
- (_Bool)postConfirmPasscodeCFU:(id *)arg1;	// IMP=0x00100000000dcf06
- (_Bool)leaveTrust:(id *)arg1;	// IMP=0x00100000000dcdc5
- (_Bool)shouldPostConfirmPasscodeCFU:(id *)arg1;	// IMP=0x00100000000dcbb3
- (_Bool)postRepairCFU:(id *)arg1;	// IMP=0x00100000000dca19
- (void)rpcFetchTotalCountOfTrustedPeers:(CDUnknownBlockType)arg1;	// IMP=0x00100000000dc943
- (void)rpcTlkRecoverabilityForEscrowRecordData:(id)arg1 source:(long long)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00100000000dc7d9
- (void)tlkRecoverabilityInOctagon:(id)arg1 source:(long long)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00100000000dc71b
- (void)octagonPeerIDGivenBottleID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000dc68d
- (void)rpcWaitForPriorityViewKeychainDataRecovery:(CDUnknownBlockType)arg1;	// IMP=0x00100000000dc4dd
- (void)rpcAccountWideSettingsWithForceFetch:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000dc254
- (void)rpcFetchAccountSettings:(CDUnknownBlockType)arg1;	// IMP=0x00100000000dbfe6
- (void)rpcFetchTrustedSecureElementIdentities:(CDUnknownBlockType)arg1;	// IMP=0x00100000000dbd05
- (void)rpcRemoveLocalSecureElementIdentityPeerID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000dbb5f
- (void)rpcSetLocalSecureElementIdentity:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000db953
- (void)rpcSetAccountSetting:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000db5d3
- (void)rpcSetUserControllableViewsSyncingStatus:(_Bool)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000db50f
- (void)rpcFetchUserControllableViewsSyncingStatus:(CDUnknownBlockType)arg1;	// IMP=0x00100000000daf9e
- (void)rpcRefetchCKKSPolicy:(CDUnknownBlockType)arg1;	// IMP=0x00100000000dad6c
- (void)fetchEscrowContents:(CDUnknownBlockType)arg1;	// IMP=0x00100000000dac96
- (void)rpcInvalidateEscrowCache:(CDUnknownBlockType)arg1;	// IMP=0x00100000000daafa
- (void)rpcFetchAllViableEscrowRecordsFromSource:(long long)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000da951
- (void)rpcFetchAllViableBottlesFromSource:(long long)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000da7a6
- (void)rpcTrustStatus:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000da0f6
- (void)rpcTrustStatusCachedStatus:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d9f78
- (void)rpcCheckInheritanceKeyWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d9dc2
- (void)rpcRemoveInheritanceKeyWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d9c0c
- (void)rpcStoreInheritanceKeyWithIK:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d9a56
- (void)rpcGenerateInheritanceKeyWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d9910
- (void)rpcCreateInheritanceKeyWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d975a
- (void)rpcCheckCustodianRecoveryKeyWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d95a4
- (void)rpcRemoveCustodianRecoveryKeyWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d93ee
- (void)rpcCreateCustodianRecoveryKeyWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d9238
- (void)rpcRemoveRecoveryKey:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d909a
- (void)rpcIsRecoveryKeySet:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d8efc
- (void)rpcSetRecoveryKey:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d8ce9
- (void)rpcFetchPeerIDByBottleID:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d8cc8
- (void)rpcFetchDeviceNamesByPeerID:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d8caa
- (void)rpcFetchPeerAttributes:(id)arg1 includeSelf:(_Bool)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00100000000d8ad8
- (void)rpcFetchEgoPeerID:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d8984
- (void)rpcStatus:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d7d86
- (id)sosSelvesStatus;	// IMP=0x00100000000d79c5
- (id)sosTrustedPeersStatus;	// IMP=0x00100000000d7722
- (id)ckksPeerStatus:(id)arg1;	// IMP=0x00100000000d7598
- (void)rpcJoin:(id)arg1 vouchSig:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00100000000d726d
- (id)joinStatePathDictionary;	// IMP=0x00100000000d6bfd
- (void)preflightRecoverOctagonUsingRecoveryKey:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d68ef
- (void)preflightJoinWithInheritanceKey:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d64d8
- (void)joinWithInheritanceKey:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d6212
- (void)preflightJoinWithCustodianRecoveryKey:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d5e2c
- (void)joinWithCustodianRecoveryKey:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d5bb7
- (void)joinWithRecoveryKey:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000d58f5
- (void)joinWithBottle:(id)arg1 entropy:(id)arg2 bottleSalt:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x00100000000d55b0
- (void)rpcPrepareIdentityAsApplicantWithConfiguration:(id)arg1 epoch:(unsigned long long)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00100000000d50af
- (id)errorIfNoCKAccount:(id)arg1;	// IMP=0x00100000000d5034
- (long long)checkForCKAccount:(id)arg1;	// IMP=0x00100000000d4b99
- (void)trustedPeerSetChanged:(id)arg1;	// IMP=0x00100000000d485d
- (void)selfPeerChanged:(id)arg1;	// IMP=0x00100000000d4857
- (void)deviceNameUpdated;	// IMP=0x00100000000d472f
- (void)requestTrustedDeviceListRefresh;	// IMP=0x00100000000d46eb
- (id)currentMemoizedLastHealthCheck;	// IMP=0x00100000000d456d
- (int)currentMemoizedAccountState;	// IMP=0x00100000000d444b
- (int)currentMemoizedTrustState;	// IMP=0x00100000000d4329
- (void)setMachineIDOverride:(id)arg1;	// IMP=0x00100000000d42c0
- (void)popTooManyPeersDialogWithEgoPeerStatus:(id)arg1 accountMeta:(id)arg2;	// IMP=0x00100000000d3d82
- (_Bool)waitForReady:(long long)arg1;	// IMP=0x00100000000d3cf8
- (void)notifyContainerChangeWithUserInfo:(id)arg1;	// IMP=0x00100000000d38d1
- (void)notifyContainerChange:(id)arg1;	// IMP=0x00100000000d3882
- (void)handleTTRRequest:(id)arg1;	// IMP=0x00100000000d344c
- (void)handleHealthRequest;	// IMP=0x00100000000d3323
- (id)extractStringKey:(id)arg1 fromDictionary:(id)arg2;	// IMP=0x00100000000d32c0
- (id)becomeReadyOperation;	// IMP=0x00100000000d31e4
- (id)becomeInheritedOperation;	// IMP=0x00100000000d3108
- (id)becomeUntrustedOperation:(id)arg1;	// IMP=0x00100000000d3014
- (void)checkTrustStatusAndPostRepairCFUIfNecessary:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d2f14
- (_Bool)checkForPhonePeerPresence:(id)arg1;	// IMP=0x00100000000d2ca0
- (id)repairAccountIfTrustedByTPHWithIntendedState:(id)arg1;	// IMP=0x00100000000d2b02
- (id)cloudKitAccountNewlyAvailableOperation:(id)arg1;	// IMP=0x00100000000d2a0e
- (id)postRepairCFUAndBecomeUntrusted;	// IMP=0x00100000000d2994
- (id)cuttlefishTrustEvaluation;	// IMP=0x00100000000d280e
- (id)evaluateTPHOctagonTrust;	// IMP=0x00100000000d2794
- (id)evaluateSecdOctagonTrust;	// IMP=0x00100000000d271a
- (id)checkForAccountFixupsOperation:(id)arg1;	// IMP=0x00100000000d2606
- (id)initializingOperation;	// IMP=0x00100000000d252a
- (id)_onqueueNextStateMachineTransition:(id)arg1 flags:(id)arg2 pendingFlags:(id)arg3;	// IMP=0x00100000000cecec
- (void)clearPairingUUID;	// IMP=0x00100000000cecd8
- (void)handlePairingRestart:(id)arg1;	// IMP=0x00100000000ce974
- (void)startOctagonStateMachine;	// IMP=0x00100000000ce937
- (id)operationDependencies;	// IMP=0x00100000000ce6b6
- (id)prepareInformation;	// IMP=0x00100000000ce386
- (void)rpcRemoveFriendsInClique:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ce26f
- (void)rpcLeaveClique:(CDUnknownBlockType)arg1;	// IMP=0x00100000000cdfcb
- (void)rpcResetAndEstablish:(long long)arg1 idmsTargetContext:(id)arg2 idmsCuttlefishPassword:(id)arg3 notifyIdMS:(_Bool)arg4 accountSettings:(id)arg5 reply:(CDUnknownBlockType)arg6;	// IMP=0x00100000000cdd66
- (void)rpcResetAndEstablish:(long long)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000cdd41
- (void)rpcReset:(long long)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000cdaac
- (void)rpcEstablish:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000cd9bc
- (id)establishStatePathDictionary;	// IMP=0x00100000000cd5a7
- (void)localReset:(CDUnknownBlockType)arg1;	// IMP=0x00100000000cd370
- (void)resetOctagonStateMachine;	// IMP=0x00100000000cd19e
- (_Bool)setCDPEnabled:(id *)arg1;	// IMP=0x00100000000ccfec
- (long long)getCDPStatus:(id *)arg1;	// IMP=0x00100000000cce27
- (_Bool)accountNoLongerAvailable:(id *)arg1;	// IMP=0x00100000000ccc20
- (_Bool)idmsTrustLevelChanged:(id *)arg1;	// IMP=0x00100000000ccbd9
- (void)moveToCheckTrustedState;	// IMP=0x00100000000cc9bb
- (_Bool)accountAvailable:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000cc1aa
- (void)cloudkitAccountStateChange:(id)arg1 to:(id)arg2;	// IMP=0x00100000000cbfba
- (void)incompleteNotificationOfMachineIDListChange;	// IMP=0x00100000000cbf3d
- (void)machinesRemoved:(id)arg1 altDSID:(id)arg2;	// IMP=0x00100000000cbba5
- (void)machinesAdded:(id)arg1 altDSID:(id)arg2;	// IMP=0x00100000000cb80d
@property(readonly, copy) NSString *description;
- (void)accountStateUpdated:(id)arg1 from:(id)arg2;	// IMP=0x00100000000cb374
- (void)notifyTrustChanged:(int)arg1;	// IMP=0x00100000000cb1f1
- (void)dealloc;	// IMP=0x00100000000cb1c2
- (void)resetCKKS:(id)arg1;	// IMP=0x00100000000cb1b0
- (void)clearCKKS;	// IMP=0x00100000000cb19c
- (id)initWithContainerName:(id)arg1 contextID:(id)arg2 activeAccount:(id)arg3 cuttlefish:(id)arg4 ckksAccountSync:(id)arg5 sosAdapter:(id)arg6 accountsAdapter:(id)arg7 authKitAdapter:(id)arg8 personaAdapter:(id)arg9 tooManyPeersAdapter:(id)arg10 tapToRadarAdapter:(id)arg11 lockStateTracker:(id)arg12 reachabilityTracker:(id)arg13 accountStateTracker:(id)arg14 deviceInformationAdapter:(id)arg15 apsConnectionClass:(Class)arg16 escrowRequestClass:(Class)arg17 notifierClass:(Class)arg18 cdpd:(id)arg19;	// IMP=0x00100000000ca879

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

