//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface SecDbKeychainMetadataKeyStore : NSObject
{
    int _keybagNotificationToken;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSMutableDictionary *_keysDict;	// 24 = 0x18
}

+ (_Bool)cachingEnabled;	// IMP=0x00400000001cbc06
+ (id)sharedStore;	// IMP=0x00100000001cbb28
+ (void)resetSharedStore;	// IMP=0x00100000001cbaf1
- (void).cxx_destruct;	// IMP=0x00200000001caf04
@property int keybagNotificationToken; // @synthesize keybagNotificationToken=_keybagNotificationToken;
@property(retain) NSMutableDictionary *keysDict; // @synthesize keysDict=_keysDict;
@property(retain) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (id)keyForKeyclass:(int)arg1 keybag:(int)arg2 keySpecifier:(id)arg3 allowWrites:(_Bool)arg4 error:(id *)arg5;	// IMP=0x00100000001caa81
- (id)fetchKeyForClass:(int)arg1 fromDb:(struct __OpaqueSecDbConnection *)arg2 keybag:(int)arg3 specifier:(id)arg4 allowWrites:(_Bool)arg5 error:(id *)arg6;	// IMP=0x00100000001ca7ed
- (_Bool)readKeyDataForClass:(int)arg1 fromDb:(struct __OpaqueSecDbConnection *)arg2 actualKeyclass:(int *)arg3 wrappedKey:(id *)arg4 error:(id *)arg5;	// IMP=0x00100000001ca5c9
- (id)writeKey:(id)arg1 ForKeyclass:(int)arg2 withKeybag:(int)arg3 keySpecifier:(id)arg4 database:(struct __OpaqueSecDbConnection *)arg5 error:(id *)arg6;	// IMP=0x00100000001ca1e4
- (id)newKeyForKeyclass:(int)arg1 withKeybag:(int)arg2 keySpecifier:(id)arg3 database:(struct __OpaqueSecDbConnection *)arg4 error:(id *)arg5;	// IMP=0x00100000001ca100
- (id)validateWrappedKey:(id)arg1 forKeyClass:(int)arg2 actualKeyClass:(int *)arg3 keybag:(int)arg4 keySpecifier:(id)arg5 error:(id *)arg6;	// IMP=0x00100000001c9d33
- (void)_onQueueDropAllKeys;	// IMP=0x00100000001c9cac
- (void)dropAllKeys;	// IMP=0x00100000001c9c61
- (void)_onQueueDropClassAKeys;	// IMP=0x00100000001c9ba3
- (void)dropClassAKeys;	// IMP=0x00100000001c9b58
- (void)dealloc;	// IMP=0x00100000001c9b13
- (id)_init;	// IMP=0x00100000001c99c3

@end

