//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface IXSMoveOrDeleteAlert
{
}

- (void)otherButtonActionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0040000000006742
- (id)otherButtonLabel;	// IMP=0x0010000000006722
- (id)cancelButtonLabel;	// IMP=0x0010000000006702
- (id)defaultButtonLabel;	// IMP=0x00100000000066e2
- (id)message;	// IMP=0x00100000000066c2
- (id)title;	// IMP=0x00100000000065e4
- (id)initWithAppRecord:(id)arg1 bundleIdentifier:(id)arg2 isRemovable:(_Bool)arg3;	// IMP=0x0010000000006577

@end

