//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewController.h>

@class NSMapTable, NSMutableArray, NSString, TVSMDefaultModuleDataSource, TVSMPeopleModuleDataSource, UICollectionViewDiffableDataSource;

@interface TVSMButtonGridCollectionViewController : UICollectionViewController
{
    TVSMPeopleModuleDataSource *_peopleDataSource;	// 8 = 0x8
    TVSMDefaultModuleDataSource *_buttonDataSource;	// 16 = 0x10
    UICollectionViewDiffableDataSource *_diffableDataSource;	// 24 = 0x18
    NSMapTable *_analyticsLocationsByModule;	// 32 = 0x20
    NSMutableArray *_analyticsImpressions;	// 40 = 0x28
    NSString *_currentFocusedIdentifier;	// 48 = 0x30
    struct CGRect _selectedCellFrame;	// 56 = 0x38
}

+ (id)_overlayAnimationSettingsForTransition:(unsigned long long)arg1;	// IMP=0x00200000000215f0
- (void).cxx_destruct;	// IMP=0x0020000000021ab0
@property(retain, nonatomic) NSString *currentFocusedIdentifier; // @synthesize currentFocusedIdentifier=_currentFocusedIdentifier;
@property(readonly, nonatomic) NSMutableArray *analyticsImpressions; // @synthesize analyticsImpressions=_analyticsImpressions;
@property(readonly, nonatomic) NSMapTable *analyticsLocationsByModule; // @synthesize analyticsLocationsByModule=_analyticsLocationsByModule;
@property(readonly, nonatomic) UICollectionViewDiffableDataSource *diffableDataSource; // @synthesize diffableDataSource=_diffableDataSource;
@property(readonly, nonatomic) TVSMDefaultModuleDataSource *buttonDataSource; // @synthesize buttonDataSource=_buttonDataSource;
@property(readonly, nonatomic) TVSMPeopleModuleDataSource *peopleDataSource; // @synthesize peopleDataSource=_peopleDataSource;
@property(readonly, nonatomic) struct CGRect selectedCellFrame; // @synthesize selectedCellFrame=_selectedCellFrame;
- (void)_updateLayoutElementWithOverlayTransition:(unsigned long long)arg1;	// IMP=0x0010000000021340
- (id)tvsm_synchronizedDrawingFence;	// IMP=0x0010000000021200
- (id)_audioRoutingPreferredIndexPath;	// IMP=0x0010000000020d50
- (void)_postPageAnalyticsEvent;	// IMP=0x0010000000020ce0
- (id)_locationAnalyticsForModule:(id)arg1;	// IMP=0x0010000000020c20
- (void)_buildAnalyticsForPeopleModules:(id)arg1 andButtonModules:(id)arg2 withLocations:(id)arg3 impressions:(id)arg4;	// IMP=0x001000000001f200
- (void)_updateSnapshotAnalyticsOnly:(_Bool)arg1;	// IMP=0x001000000001e6a0
- (id)_moduleAtIndexPath:(id)arg1;	// IMP=0x001000000001e530
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x001000000001e2d0
- (void)moduleDidRequestSystemMenuDismissal:(id)arg1 animated:(_Bool)arg2 result:(id)arg3;	// IMP=0x001000000001e210
- (void)moduleDidRequestOverlay:(id)arg1;	// IMP=0x001000000001e070
- (void)moduleDidRequestExpansion:(id)arg1;	// IMP=0x001000000001dc30
- (void)moduleDidRequestDismissal:(id)arg1;	// IMP=0x001000000001db30
- (void)moduleDidPerformAction:(id)arg1;	// IMP=0x001000000001da10
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x001000000001d8c0
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x001000000001d7b0
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x001000000001d700
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x001000000001d600
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x001000000001d5b0
- (id)indexPathForPreferredFocusedViewInCollectionView:(id)arg1;	// IMP=0x001000000001d4c0
- (void)_configureCell:(id)arg1 withModuleAtIndexPath:(id)arg2;	// IMP=0x001000000001d2c0
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x001000000001d250
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000001d1b0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000001d060
- (void)viewDidLoad;	// IMP=0x001000000001caf0
- (void)initialAnimationDidFinish;	// IMP=0x001000000001c8e0
- (void)dealloc;	// IMP=0x001000000001c7e0
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000001c770
- (id)init;	// IMP=0x001000000001c360

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

