//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol FAQueueProvider;

@interface FAHeartbeatActivity : NSObject
{
    id <FAQueueProvider> _queueProvider;	// 8 = 0x8
    long long _timeInterval;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000009c2f
- (id)_familyGrandSlamSignerWithAccountStore:(id)arg1;	// IMP=0x0010000000009b7e
- (id)_grandSlamSignerWithAccountStore:(id)arg1;	// IMP=0x0010000000009aed
- (id)_grandSlamAccountForAccountStore:(id)arg1;	// IMP=0x0010000000009a73
- (id)_primaryAccount;	// IMP=0x0010000000009a1c
- (_Bool)_checkAndDeferActivityIfNeeded:(id)arg1;	// IMP=0x001000000000994b
- (void)_performHeartbeatCheckinForActivity:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000009421
- (void)performHeartbeatCheckinWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000000940a
- (void)checkin;	// IMP=0x001000000000906a
- (void)unregister;	// IMP=0x0010000000009059
- (id)initWithQueueProvider:(id)arg1;	// IMP=0x0010000000008fe0

@end

