//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _NSUndoBlockInvocation
{
    CDUnknownBlockType _handler;	// 32 = 0x20
}

- (void)invoke;	// IMP=0x000000000073d966
- (void)dealloc;	// IMP=0x000000000073d8e9
- (id)initWithTarget:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x000000000073d832

@end

