//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSExpression.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface NSSymbolicExpression : NSExpression
{
    NSString *_token;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0060000000724dd4
- (id)expressionValueWithObject:(id)arg1 context:(id)arg2;	// IMP=0x00000000007250c6
- (unsigned long long)hash;	// IMP=0x00000000007250a9
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000000725062
- (id)constantValue;	// IMP=0x0000000000725051
- (id)predicateFormat;	// IMP=0x0000000000725040
- (void)dealloc;	// IMP=0x0000000000724fdb
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000000724fa4
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000724eab
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000000724de7
- (unsigned long long)expressionType;	// IMP=0x0000000000724ddc
- (id)initWithString:(id)arg1;	// IMP=0x0000000000724d19

@end

