//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSFormatter.h"

@class NSLocale, NSNumberFormatter;

__attribute__((visibility("hidden")))
@interface NSUnitFormatter : NSFormatter
{
    NSNumberFormatter *_numberFormatter;	// 8 = 0x8
    unsigned long long _unitOptions;	// 16 = 0x10
    long long _unitStyle;	// 24 = 0x18
    struct UAMeasureFormat *_formatter;	// 32 = 0x20
    struct UPluralRules *_prules;	// 40 = 0x28
    _Bool _modified;	// 48 = 0x30
    NSLocale *_locale;	// 56 = 0x38
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00100000007a2291
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000000007a2299
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000000007a218d
- (id)initWithCoder:(id)arg1;	// IMP=0x00000000007a1ec3
- (id)stringFromUnit:(id)arg1;	// IMP=0x00000000007a1bb1
- (id)unitStringFromValue:(double)arg1 unit:(unsigned long long)arg2;	// IMP=0x00000000007a17c1
- (id)stringForValue1:(double)arg1 unit1:(unsigned long long)arg2 value2:(double)arg3 unit2:(unsigned long long)arg4;	// IMP=0x00000000007a14d6
- (id)stringForValue:(double)arg1 unit:(unsigned long long)arg2;	// IMP=0x00000000007a1162
- (id)stringForObjectValue:(id)arg1;	// IMP=0x00000000007a0038
- (void)checkIfModified;	// IMP=0x000000000079fd3f
- (int)_determineUnitsToFormat:(int *)arg1 fromMeasurement:(id)arg2;	// IMP=0x000000000079f90b
@property(copy) NSLocale *locale;
@property long long unitStyle;
@property unsigned long long unitOptions;
@property(copy) NSNumberFormatter *numberFormatter;
- (void)dealloc;	// IMP=0x000000000079f636
- (id)init;	// IMP=0x000000000079f5b6

@end

