//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ApplicationWorkspaceInstallPlaceholderOperation
{
}

- (id)_download;	// IMP=0x00400000001c9910
- (void)runWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001c9873
- (_Bool)blocksAppInstallation;	// IMP=0x00100000001c986b
- (id)initWithApplicationHandle:(id)arg1 iconData:(id)arg2;	// IMP=0x00100000001c983c
- (id)initWithApplicationHandle:(id)arg1 forceUpdate:(_Bool)arg2;	// IMP=0x00100000001c980d

@end

