//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface BookAssetDaemonUtility : NSObject
{
}

+ (void)checkAutomaticDownloads;	// IMP=0x004000000018fe4e
+ (void)sendRestoreDownloads:(id)arg1 withReason:(id)arg2;	// IMP=0x001000000018fc9d
+ (void)sendBookStoreDownloads:(id)arg1 withReason:(id)arg2;	// IMP=0x001000000018faec
+ (void)sendBookDownloads:(id)arg1 withReason:(id)arg2;	// IMP=0x001000000018f93b

@end

