//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber;

@interface DaemonBiometricStore : NSObject
{
}

+ (id)_dispatchQueueUpdateToken;	// IMP=0x0040000000185264
+ (void)_resetAccount:(id)arg1 withConnection:(id)arg2;	// IMP=0x001000000018506b
+ (void)_handleMessage:(id)arg1 connection:(id)arg2 withReplyBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000184a57
+ (void)tokenUpdateStateWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001848b4
+ (void)tokenUpdateShouldStartWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001846cc
+ (void)tokenUpdateDidFinishWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001844fd
+ (void)setEnabledWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183dc8
+ (void)setAllowedWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183d11
+ (void)saveIdentityMapWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183b40
+ (void)resetWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183962
+ (void)resetAccountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001837bc
+ (void)isIdentityMapValidWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183620
+ (void)getStateWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000183119
+ (void)getKeyCountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000182db3
+ (void)getIdentityMapCountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000182c52
+ (void)getCurrentACLVersionWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000182bc4
+ (void)getConstraintsDictionaryWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000182b23
+ (void)getCachedBiometricHTTPHeadersWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001823c9
+ (void)getCachedBiometricAuthenticationContextWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000181ec8
+ (void)getAllCachedBiometricHTTPHeadersWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000181640
+ (void)observeXPCServer:(id)arg1;	// IMP=0x0010000000181452
+ (long long)tokenUpdateState;	// IMP=0x0010000000180d87
+ (_Bool)tokenUpdateShouldStartWithLogKey:(id)arg1;	// IMP=0x00100000001804d2
+ (void)tokenUpdateDidFinishWithLogKey:(id)arg1;	// IMP=0x001000000018027a
- (void)_deleteKeychainTokensForAccountIdentifier:(id)arg1;	// IMP=0x0020000000184e1d
- (id)_bootDate;	// IMP=0x0010000000184d78
@property long long biometricState;
- (void)saveIdentityMap:(id)arg1 forAccountIdentifier:(id)arg2;	// IMP=0x00100000001800a9
- (void)registerAccountIdentifier:(id)arg1;	// IMP=0x00100000001800a3
- (void)obliterateBiometricsForAccountIdentifier:(id)arg1;	// IMP=0x001000000017feb9
- (long long)tokenAvailabilityForAccountIdentifier:(id)arg1;	// IMP=0x001000000017feae
@property(readonly) NSNumber *lastRegisteredAccountIdentifier;
- (unsigned long long)keyCountForAccountIdentifier:(id)arg1;	// IMP=0x001000000017fa27
- (_Bool)isIdentityMapValidForAccountIdentifier:(id)arg1;	// IMP=0x001000000017fa1f
@property(readonly) _Bool isBiometricStateEnabled;
- (id)identityMap;	// IMP=0x001000000017f9f2
- (void)clearLastRegisteredAccountIdentifier;	// IMP=0x001000000017f82c
@property(readonly) _Bool canPerformBiometricOptIn;

@end

