//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface DownloadDRMOperation
{
}

- (_Bool)_unprotectMediaAsset:(id *)arg1;	// IMP=0x00200000001d59c8
- (id)_sinfs;	// IMP=0x00100000001d5603
- (_Bool)_decryptAsset:(id *)arg1;	// IMP=0x00100000001d5207
- (_Bool)_checkoutRentalKeys:(id *)arg1;	// IMP=0x00100000001d4bc9
- (void)operation:(id)arg1 updatedProgress:(id)arg2;	// IMP=0x00100000001d4b2d
- (void)run;	// IMP=0x00100000001d486d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

