//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class FairPlayDecryptSession, NSData, NSString;

@interface FairPlayDecryptFileOperation : ISOperation
{
    NSData *_dpInfo;	// 96 = 0x60
    double _lastSnapshotTime;	// 104 = 0x68
    NSString *_path;	// 112 = 0x70
    FairPlayDecryptSession *_fairplayDecryptSession;	// 120 = 0x78
}

- (void)_updateProgressWithByteCount:(long long)arg1;	// IMP=0x0020000000080d08
- (void)_initializeProgressWithFileHandle:(id)arg1;	// IMP=0x0010000000080c5c
- (_Bool)_decryptWithSession:(id)arg1 error:(id *)arg2;	// IMP=0x001000000008061e
- (void)run;	// IMP=0x00100000000801f5
- (void)dealloc;	// IMP=0x001000000008019d
- (id)initWithPath:(id)arg1 dpInfo:(id)arg2;	// IMP=0x00100000000800cb
- (id)init;	// IMP=0x00100000000800b5

@end

